### ISSUE TITLE
docker-compose: could not synchronise with container process

### ISSUE THREAD

**Issue by theodotos** [invoiceninja/dockerfiles#10]
I am trying to test run invoiceninja using the *docker-compose.yml* in the Readme. No customizations in the *docker-compose.yml*.

When I run `docker-compose up` I get:

```
Creating root_db_1
Creating root_app_1
Creating root_web_1
ERROR: Cannot start container 7262703d16de137f3d9cc4636225104a71edd8480570f43cb82e82adf8f25179: [10] System error: could not synchronise with container process
```

Indeed the web container fails to start:

```
# docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS               NAMES
7262703d16de        nginx                       "nginx -g 'daemon off"   34 seconds ago      Created                                 root_web_1
65244c1fb692        invoiceninja/invoiceninja   "/entrypoint.sh php-f"   38 seconds ago      Up 34 seconds       80/tcp, 9000/tcp    root_app_1
6cadcb105ee6        mysql                       "docker-entrypoint.sh"   39 seconds ago      Up 38 seconds       3306/tcp            root_db_1
```

Log says:

```
# docker logs root_web_1
Timestamp: 2016-06-14 10:34:19.298956995 +0300 EEST
Code: System error

Message: not a directory

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@42
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@75
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@255
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@18
---
6: main
Package: runtime
File: proc.go@188
---
7: goexit
Package: runtime
File: asm_amd64.s@1998
```

Docker info:

```
# docker info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 5
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 57
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.784 GiB
Name: adm01mc604
ID: TQD3:UVA5:MKNC:RF5G:7AKF:IYN4:JSDM:LNKO:A6UB:35E6:HEC2:YTFY
WARNING: No swap limit support
```

Any hints?

References
---------------
* https://github.com/invoiceninja/dockerfiles/blob/master/README.md

**Comment by lalop** [comment]
Hello,
this doesn't seam to come from the invoiceninja image.
What version of docker do you use ? What is your os ?

**Comment by lalop** [comment]
Do you put the nginx.conf file on your file system ?

**Comment by theodotos** [comment]
Docker info:

<pre>
# docker info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 5
<strong>Server Version: 1.10.3</strong>
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 57
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.0-22-generic
<strong>Operating System: Ubuntu 16.04 LTS</strong>
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.784 GiB
Name: adm01mc604
ID: TQD3:UVA5:MKNC:RF5G:7AKF:IYN4:JSDM:LNKO:A6UB:35E6:HEC2:YTFY
WARNING: No swap limit support
</pre>

**Comment by lalop** [comment]
ok but did you get the nginx.conf file before ?

**Comment by theodotos** [comment]
Ah you mean I need to configure before I attempt to start the container?

**Comment by lalop** [comment]
If you want to use the docker-compose.yml exemple you must have a nginx.conf file, a default one is given in this repository

**Comment by theodotos** [comment]
Now I see. My bad, I'll give it a try.
