### ISSUE TITLE
`DB_TYPE='mysql'` can probably be removed

### ISSUE THREAD

**Issue by alexanderadam** [invoiceninja/dockerfiles#100]
If I see this correctly, [InvoiceNinja supports **only** MySQL/MariaDB](https://github.com/invoiceninja/invoiceninja/issues/499#issuecomment-211003238) ([1](https://github.com/invoiceninja/invoiceninja/issues/1833#issuecomment-359190052), [2](https://github.com/invoiceninja/invoiceninja/issues/499#issuecomment-211003238), [3](https://github.com/invoiceninja/invoiceninja/issues/2680#issuecomment-466165696), [4](https://github.com/invoiceninja/invoiceninja/issues/477#issuecomment-148935499)).

Meaning: there's no point in giving control over `DB_TYPE` if there is no support for anything else anyway. :wink:

**Comment by lalop** [comment]
:D 
this is a really good point but this has to be changed in the app I think.
@hillelcoren dosn't `mysql` should be wrote directly here https://github.com/invoiceninja/invoiceninja/blob/master/config/database.php#L29 ?

**Comment by hillelcoren** [comment]
Not sure I follow, the code looks correct to me. The default is MySQL but can be overwritten by setting a value in the .env file.

**Comment by lalop** [comment]
ok so this comment isn't up to date https://github.com/invoiceninja/invoiceninja/issues/499

**Comment by hillelcoren** [comment]
Sorry, I didn't understand. v1 will only support MySQL, @turbo124 thoughts on v2?

**Comment by turbo124** [comment]
@hillelcoren the aim for V2 will be to support all native laravel DB drivers.

**Comment by lalop** [comment]
ok but for v1 this variable is useless, maybe you can remove it ?

**Comment by hillelcoren** [comment]
I have a feeling that will break things...

**Comment by lalop** [comment]
I was misunderstanding DB_TYPE, it's not the database driver it's the default database connection for a multi-database setup.
So this env is usefull in some case I image although I don't know this kind of setup.

**Comment by alexanderadam** [comment]
Okay, nevermind. I will close this then if removing the need of an environment variable that has no function would break things.
