### ISSUE TITLE
Unable to upload image for expenses

### ISSUE THREAD

**Issue by nordge1** [invoiceninja/dockerfiles#101]
I am thinking this may be a permissions issue but thought I would get some advise.

Under expenses, I am unable to either drop and drop or browse upload an image of the receipt. After I try and upload I get a brief 1mb upload in the upload section then nothing, If I try and save the expense. It says please wait fro the upload to complete. 

Any help would be greatly appreciated.

**Comment by hillelcoren** [comment]
Maybe it's related to the file size, do smaller images work? 

Are there any error details in storage/logs/laravel-error.log

**Comment by codedge** [comment]
@nordge1 Do you still experience this issue?
What docker setup do you run - with `docker-compose` or only the PHP docker image with some extra web server in front?

**Comment by codedge** [comment]
Closing this for now. @nordge1 please open another issue if you still facing issues.
