### ISSUE TITLE
alpine image: `Class LaravelCrawlerDetect does not exist`

### ISSUE THREAD

**Issue by alexanderadam** [invoiceninja/dockerfiles#102]
I'm trying to setup InvoiceNinja with Docker (`invoiceninja:alpine` to be more specific) but I'm running in to this exception instead:

![Screenshot_20190611_110526](https://user-images.githubusercontent.com/372620/59258752-d7e9ed00-8c38-11e9-8221-96b6d46c0439.png)

I found [this forum thread](https://www.invoiceninja.com/forums/topic/class-laravelcrawlerdetect-does-not-exist/) but the hints in it doesn't help in my case.

Calling `php artisan optimize` within the container showed
```
Generating optimized class loader
The compiled services file has been removed.
```

but the error still appears (calling `php artisan clear-compiled` before didn't make a difference).
I tried to call `composer install` but it doesn't seem to work within the container. Should it usually be available in container? Or do I need to call it differently here (a specific path or something like that)?

I didn't try to change the source code tough because I thought if must be something else if it is working everywhere else.

The directory `bootstrap/cache/` is empty (besides the `.gitignore`).

Command `$ docker logs invoiceninja-app` only shows `11/Jun/2019:09:24:02 +0000 "GET /index.php" 500` for any request.

Do you have any advice how to debug this or even an idea for a bugfix?

It might be related to [#2598](https://github.com/invoiceninja/invoiceninja/issues/2598) or [#1071](https://github.com/invoiceninja/invoiceninja/issues/1071) but I would guess that tooling and dependencies should be properly baked in the Docker image, right?

**UPDATE:** this error does only appear with the Alpine image!

**Comment by codedge** [comment]
@alexanderadam We updated the `alpine` image. I wasn't able to reproduce the issue you got. Please check again and let us know if you still encountering problems.

For now I close this issue here. Feel free to open a new one.

**Comment by alexanderadam** [comment]
Thank you but in the meantime I moved away to another FOSS invoicing/time tracking solution.

**Comment by kreativmonkey** [comment]
this error is already there. I have a fresh ubuntu v server running and installing docker and the docker compose. when i use the alpine-4.5.7 i've got the same error message up to 4.5.20. i don't tested the versions lower than 4.5.7!
