### ISSUE TITLE
docker-compose web page not responding

### ISSUE THREAD

**Issue by bryanhonof** [invoiceninja/dockerfiles#105]
Hello,

I have a little problem with setting up a self-hosted solution for invoiceninja with docker-compose.

## Problem Description

When I run ```docker-compose up``` everything seems to pass fine without any errors or weird messages but when I try to access the web page on ```localhost:8000``` I get no response (it just keeps loading).
I also tried running ```docker system prune && docker volume prune``` to start from a clean slate but that did not seem to resolve the issue.
I did notice when I close the browser tab I get a 499 in the compose output.

## Docker Versions

```
docker --version
Docker version 19.03.1-ce, build 74b1e89e8a
```
```
docker-compose --version
docker-compose version 1.23.1, build b02f1306
```
## .env & compose output files

[.env.txt](https://github.com/invoiceninja/dockerfiles/files/3463669/default.env.txt)
[docker-compose.log](https://github.com/invoiceninja/dockerfiles/files/3463660/docker-compose.log)

I hope this is enough info, since I honestly do not know how to access the internal error log file of invoiceninja.

If I need to supply anything else just let me know.

**Comment by codedge** [comment]
Can you please post your `docker-compose.yml`?

**Comment by codedge** [comment]
Closing this. Please create a new issue when facing this issue again.
