### ISSUE TITLE
'how to import a mysqldump' in docker-compose instance of invoiceninja.

### ISSUE THREAD

**Issue by ravigupta-art** [invoiceninja/dockerfiles#107]
Referring to the issue here: https://github.com/invoiceninja/invoiceninja/issues/2942

How do I import the 'mysqldump' in docker-compose installation?

**Comment by lalop** [comment]
This depend of your database image, if you use the official mysql image please refer to its documentation https://hub.docker.com/_/mysql/
The "Initializing a fresh instance" should help

**Comment by lalop** [comment]
I close this issue since it's not related to invoiceninja dockerfile
