### ISSUE TITLE
Add support for ARMv7 (raspberry pi 4)

### ISSUE THREAD

**Issue by ravigupta-art** [invoiceninja/dockerfiles#108]
Currently the invoiceninja/dockerfiles installation is not possible on raspberry pi 4 (ARMv7).
The reason is that there is no image named 'mysql:5' to pull from the dockerhub for ARMv7.

This variable is set in the docker-compose.yml file as:
`services:`
 ` db:`
`    image: mysql:5`

If I make the changes as:
`    image: armv7/armhf-mysql:5.5`
On doing so, the image is pulled but the app which is built exits with error.

I think we need to make changes so docker installation works on raspberrypi 4 as well.

**Comment by lalop** [comment]
I don't use this kind of hardware, do you know what kind of changes sould be applied ?
We are open to pr by the way

**Comment by ravigupta-art** [comment]
Hi. Yes, I was able to get it working on the particular hardware. I will be youtube video about this, I hope this might help someone who wants to get it working on the particular hardware. 

I believe Invoiceninja and Raspberry Pi 4b would be perfect match for anyone who is willing to install Invoiceninja on a local machine.

**Comment by lalop** [comment]
this sounds good.
Did you have to update Dockerfile or docker-compose.yaml for that ?

**Comment by ravigupta-art** [comment]
yes, just the docker-compose.yaml file I think. I will write the complete steps soon. Also, I will send in the pull request with the changes I made. The community review would help in approving the changes.

**Comment by alexdmejias** [comment]
@ravigupta-art do you have an update on this?

**Comment by ravigupta-art** [comment]
Yes, I have. I got busy with my art work. The current COVID-19 situation has affected the work flow. But, as mentioned above, substituting the `image: mysql:5` with `image: armv7/armhf-mysql:5.5` does the trick.

Caveat here is that we are pulling mysql image from an unreliable source. As promised, I wish to make the video about it as soon as possible.

**Comment by jpmurray** [comment]
I tried to go the mariadb way and even them don't seem to have an image for armv7 yet, so I want to just confirm, using the image @ravigupta-art said, `armv7/armhf-mysql:5.5` works perfectly fine when pulling on a Raspi 4 !

**Comment by ravigupta-art** [comment]
> I tried to go the mariadb way and even them don't seem to have an image for armv7 yet, so I want to just confirm, using the image @ravigupta-art said, `armv7/armhf-mysql:5.5` works perfectly fine when pulling on a Raspi 4 !

Yes, also I found other mysql images on docker hub that could be more reliable. I really want to write an entire article on the process to make it easy for everyone, but just can't able to find time. Let me finish up the illustrations for the new book I am working on, I will address this soon.

**Comment by shadekh** [comment]
I tried the suggested fix, but the compose exited with an error while setting up pi_server_1. Does anyone have an idea what I am doing wrong?
I am on a raspberry pi 4 headless, fresh install of docker and docker compose. Ran the docker compose yml with the mysql modification

![image](https://user-images.githubusercontent.com/66863419/84562574-0120ea00-ad73-11ea-9028-c7600a72c9ff.png)

**Comment by karneaud** [comment]
@shadekh  looks like the it could not find the Caddyfile. Also be sure that the images support ARM for RPI

**Comment by hartraft** [comment]
There is an ARMv7 image that you can use for caddy
```yobasystems/alpine-caddy:armhf```

I don't know much about yobasystems.

**Comment by turbo124** [comment]
#183
