### ISSUE TITLE
Upgrade from stretch to buster for the Dockerfile

### ISSUE THREAD

**Issue by arthurlogilab** [invoiceninja/dockerfiles#109]
Debian buster has been release, it might be a good idea to migrate to debian buster in place of stretch.

**Comment by lalop** [comment]
we use strech cause of freetype issue, I don't know if this is fixed.

**Comment by codedge** [comment]
@lalop 
What is that freetype issue, I mean is there any issue/reference to that?

**Comment by lalop** [comment]
not sure anymore, but I think this is related to https://github.com/docker-library/php/issues/865#issuecomment-511583850

**Comment by codedge** [comment]
We are currently working on some newer, more up to date images which will be based on `alpine`. Please start using this as we plan to phase out the debian-based images. You can use `invoiceninja/invoiceninja:alpine` already.
