### ISSUE TITLE
Versioning problem

### ISSUE THREAD

**Issue by Mzngit** [invoiceninja/dockerfiles#110]
The latest version tag appears to be incorrect. Also, the version in the docker file is 4.5.14,which is the prior version.
Thanks.

**Comment by lalop** [comment]
oups good point, my mistake.
Thank you

**Comment by Mzngit** [comment]
Sorry but after upgrade to invoiceninja/invoiceninja:latest, Docker container ENV variables is correct, stating version 4.5.15
However, the version on the bottom of the actual app once loaded via the web still reads 4.5.14.
