### ISSUE TITLE
Issue Defining Volume Variables 

### ISSUE THREAD

**Issue by ghost** [invoiceninja/dockerfiles#113]
When I define the paths to my volumes at the top of the file I get this error after running `docker-compose up -d`

`In file './docker-compose.yml', volume must be a mapping, not a string.`

**Comment by MayNiklas** [comment]
Did you found a fix? 
How looks your .yml file?
I'm really trying to get it to work while also mounting the storage paths into my hosts folder...

**Comment by codedge** [comment]
@ghost @MayNiklas If you still have issues with that please post your `docker-compose.yml` files.

**Comment by codedge** [comment]
Closing this. @ghost let us know if you still encounter issues.
