### ISSUE TITLE
Dockerfile doesn't copy things over properly

### ISSUE THREAD

**Issue by smcpeck** [invoiceninja/dockerfiles#119]
Trying to use the docker image, but can't get things to populate the `/var/www/app/` directory properly.

It looks, to me, that the following line in the Dockerfile: `&& mv /var/www/ninja /var/www/app  \` should actually be `&& mv /var/www/ninja/* /var/www/app  \` as the way it currently is just results in a folder being created as `/var/www/app/ninja`.

Happy to do a PR and fix this, but just wanted to start the discussion here in case I'm missing something.

**Comment by lalop** [comment]
If you run `docker run --rm invoiceninja/invoiceninja ls -all /var/www/app` you only see a folder ninja ?

**Comment by smcpeck** [comment]
Well, the Dockerfile cleans up after itself further down, so it's unclear what's going on exactly.  I've moved to a custom/generic php container to just run the code from a bind mount, so I've gotten passed this issue, but feel it is probably a stumbling block still with the official image out of the box.

**Comment by codedge** [comment]
I think this is solved. If you @smcpeck still have issues with the current version please let us know in a separate issue.
When using IN please stick to the `alpine` version.
