### ISSUE TITLE
Docker compose example doesn't work

### ISSUE THREAD

**Issue by marinus** [invoiceninja/dockerfiles#12]
Tried the example docker compose using Docker version 1.12.0, build 8eab29e
Docker compose does start up but could can't browse.
`
invoice-ninja$ docker-compose up
Starting invoiceninja_db_1
Recreating invoiceninja_app_1
Recreating invoiceninja_web_1
Attaching to invoiceninja_db_1, invoiceninja_app_1, invoiceninja_web_1
db_1   | 2016-07-31T18:11:47.575708Z 0 [Note] mysqld (mysqld 5.7.13) starting as process 1 ...
db_1   | 2016-07-31T18:11:47.578590Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1   | 2016-07-31T18:11:47.578611Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1   | 2016-07-31T18:11:47.578616Z 0 [Note] InnoDB: Uses event mutexes
db_1   | 2016-07-31T18:11:47.578620Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1   | 2016-07-31T18:11:47.578625Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1   | 2016-07-31T18:11:47.578630Z 0 [Note] InnoDB: Using Linux native AIO
db_1   | 2016-07-31T18:11:47.578793Z 0 [Note] InnoDB: Number of pools: 1
db_1   | 2016-07-31T18:11:47.578874Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1   | 2016-07-31T18:11:47.583059Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1   | 2016-07-31T18:11:47.588532Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1   | 2016-07-31T18:11:47.590563Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1   | 2016-07-31T18:11:47.602359Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1   | 2016-07-31T18:11:47.609462Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1   | 2016-07-31T18:11:47.609523Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1   | 2016-07-31T18:11:47.638395Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1   | 2016-07-31T18:11:47.639046Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1   | 2016-07-31T18:11:47.639055Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
app_1  | [31-Jul-2016 18:11:47] NOTICE: fpm is running, pid 1
db_1   | 2016-07-31T18:11:47.639746Z 0 [Note] InnoDB: 5.7.13 started; log sequence number 12129524
db_1   | 2016-07-31T18:11:47.640414Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
app_1  | [31-Jul-2016 18:11:47] NOTICE: ready to handle connections
db_1   | 2016-07-31T18:11:47.640956Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1   | 2016-07-31T18:11:47.641859Z 0 [Note] InnoDB: Buffer pool(s) load completed at 160731 18:11:47
db_1   | 2016-07-31T18:11:47.642242Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
db_1   | 2016-07-31T18:11:47.642256Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1   | 2016-07-31T18:11:47.642284Z 0 [Note] IPv6 is available.
db_1   | 2016-07-31T18:11:47.642292Z 0 [Note]   - '::' resolves to '::';
db_1   | 2016-07-31T18:11:47.642307Z 0 [Note] Server socket created on IP: '::'.
db_1   | 2016-07-31T18:11:47.645677Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2016-07-31T18:11:47.645696Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1   | 2016-07-31T18:11:47.647800Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2016-07-31T18:11:47.653909Z 0 [Note] Event Scheduler: Loaded 0 events
db_1   | 2016-07-31T18:11:47.654295Z 0 [Note] mysqld: ready for connections.
db_1   | Version: '5.7.13'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
app_1  | 172.17.0.4 -  31/Jul/2016:18:12:51 +0000 "GET /index.php" 500
web_1  | 172.17.0.1 - - [31/Jul/2016:18:12:51 +0000] "GET / HTTP/1.1" 500 8983 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
`

Here's the compose file.
`db:
  image: mysql
  environment:
    MYSQL_DATABASE: ninja
    MYSQL_ROOT_PASSWORD: mdp

app:
  image: invoiceninja/invoiceninja
  links:
    - db:mysql

web:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - app
  volumes_from:
    - app
  ports:
    - 80`

**Comment by lalop** [comment]
hello, 
did you clone the repos ?
as you can see in the docker-compose.yml, the file nginx.conf is mounted from the host, is it present into the folder that contains docker-compose.yml ?

**Comment by marinus** [comment]
Yes. I cloned the repo and added the compose file to the same directory.

**Comment by lalop** [comment]
I did a new image can you test with this one please ?

**Comment by marinus** [comment]
Thanks for the update, I have some debugging information to share.
[ninja1.txt](https://github.com/invoiceninja/dockerfiles/files/393152/ninja1.txt)

**Comment by lalop** [comment]
This erroris fixed in the last invoiceninja image, please pull it.

**Comment by marinus** [comment]
A docker pull resolved the issue.
