### ISSUE TITLE
[Question] Purpose of phantomjs

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/dockerfiles#124]
The readme says the alpine image doesn't work with phantomjs.

I assume phantomjs is used during testing, etc. I'm not building from source or doing any custom development - I just want to spin up the image and use it.

Is phantomjs needed in my use case?

(I'd like to use the alpine image if possible, as it's much "lighter" on a small server.)

**Comment by lonix1** [comment]
I have discovered that it's needed for generating PDFs.

@lalop I wonder why ghostscript is not used instead? It's more robust and works on every platform (I think also alpine).

Most importantly: phantomjs was abandoned in 2018. 😢

**Comment by lalop** [comment]
This is a legacy dependency and should be removed on invoiceninja 2

**Comment by lonix1** [comment]
That is really nice to know. Getting it to work is not fun or easy.
