### ISSUE TITLE
[Bug] Alpine image doesn't set ownership for /var/www/app/

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/dockerfiles#126]
I struggled to get the alpine image to start. I discovered it does not set ownership for the files.

This is in the [debian image](https://github.com/invoiceninja/dockerfiles/blob/4.5.17/Dockerfile#L67):
````Dockerfile
chown -R www-data:www-data /var/www/app/storage /var/www/app/bootstrap /var/www/app/public/logo /var/www/app/.env /var/www/app/docker-backup-storage /var/www/app/docker-backup-public
````

The [alpine image](https://github.com/invoiceninja/dockerfiles/blob/4.5.17/alpine/Dockerfile#L49) is missing that line.

Also, surely it would be better to do this: `chown -R www-data:www-data /var/www/app/` instead of the above, since it is the parent of all those subdirectories?

**Comment by lonix1** [comment]
Until this is resolved, here is my workaround for those who need it:

````docker
entrypoint: /bin/sh -c '
  chown -R www-data:www-data /var/www/app/ &&
  find /var/www/app/ -type d -exec chmod 2755 {} + &&
  find /var/www/app/ -type f -exec chmod 0664 {} + &&
  /usr/local/bin/invoice-entrypoint php-fpm'
````

This hijacks the entrypoint - sets ownership and permissions (including gid bit), then runs original entrypoint.

Only note that this is very slow, takes about half a minute to start the image, so don't be alarmed. But restarting a container doesn't happen every day.

**Comment by lalop** [comment]
@lonix1 can you make a pr with a definitive fix ?

**Comment by lonix1** [comment]
This workaround works. But, I also tried the debian image and had the same problem (and used the same workaround). So maybe I have an underlying problem with my environment / config.

However... if someone else has this ownership/permission problem then my workaround is good.

What I would like to know... is it enough to change `/var/www/app/`? I see you set many directories individually - why not do it the easy way like I did? I'm worried you did it that way for a reason and maybe I will break something?

**Comment by codedge** [comment]
@lonix1 We did some changes to the `alpine` image and  this problem should not appear anymore. I'll close this problem for now. Feel free to open anothe issue if you encounter any problem.

**Comment by IronicBadger** [comment]
v5, no matter what I tried (`chown -R 777` or `chmod -R www-data:www-data`) including the fixes above I could not get beyond 

`2020-06-03T02:38:33.811121491Z chown: /var/www/app/public: Operation not permitted`

This was for all files in `/var/www/app` not just the one line above. Reverted back to the `4.5.18` and issue went away.

**Comment by causefx** [comment]
any update on @IronicBadger's issue

**Comment by IronicBadger** [comment]
Maybe we should open a new issue as I can't reopen this one.
