### ISSUE TITLE
Invoice Design not showing in Firefox

### ISSUE THREAD

**Issue by danielgroen** [invoiceninja/dockerfiles#128]
I am on Version v4.5.17 of Invoice Ninja and on my Firefox browser the invoice design window is greyed out: see screenshot below. Altough on Google Chrome it does work.
_(The JS console does not show any errors)._

My Firefox version is 74.0.

![image](https://user-images.githubusercontent.com/6578052/77248416-7f209980-6c39-11ea-84ab-ff5d8a035b79.png)

**Comment by hillelcoren** [comment]
https://support.mozilla.org/en-US/questions/985483

**Comment by danielgroen** [comment]
Thanks!
