### ISSUE TITLE
Can't force clear text connection for troubleshooting

### ISSUE THREAD

**Issue by marinus** [invoiceninja/dockerfiles#13]
I'm testing out the docker version and I need to connect it to an SMTP server.
I've connected the most popular docker smtp server from dockerhub called namshi/smtp.
Although I can make connections using openssl to it invoiceninja is refusing.
I'm using docker application linking to enable networking between containers.

smtp_1 | 306 LOG: MAIN smtp_1 | 306 TLS error on connection from ninja ([172.17.0.5]) [172.17.0.4] (gnutls_handshake): A TLS fatal alert has been received. smtp_1 | 306 LOG: smtp_connection MAIN smtp_1 | 306 SMTP connection from ninja ([172.17.0.5]) [172.17.0.4] closed by EOF

If I downgrade to SSL I can see it's trying to make a binary connection, which also fails.

smtp_1 | 307 LOG: MAIN REJECT smtp_1 | 307 SMTP protocol synchronization error (input sent without waiting for greeting): rejected connection from H=ninja [172.17.0.4] input="\026\003\001\002"

If there a way to force a plain clear text connection?

I've tried a couple of things like editing .env file but I have had no success.
[docker-compose.yml.zip](https://github.com/invoiceninja/dockerfiles/files/398715/docker-compose.yml.zip)

**Comment by lalop** [comment]
I closed this issue since the answer is on the invoiceninja repos https://github.com/invoiceninja/invoiceninja/issues/1027
