### ISSUE TITLE
Email settings (SMTP) can't be changed

### ISSUE THREAD

**Issue by danielgroen** [invoiceninja/dockerfiles#130]
Hi,

When i am trying to change my email settings to my own email settings and hitting the save button, the page reloads and everything in the emailsettings form on `/settings/system_settings` does change back to it's old state. See below the form field where i am talking about.

Although when i change everything to my server and send a testmail, it got delivered so the functionalities does work, it just appears to reset the form every time.

i am currently on Ubuntu 18.04

I don't know if this is a known issue or a duplicate but i could'nt find any one with this problem.
![image](https://user-images.githubusercontent.com/6578052/77518531-3e659200-6e7e-11ea-8ef2-94739afdd90a.png)

**Comment by hillelcoren** [comment]
You can manually modify the .env file instead of using the UI

**Comment by danielgroen** [comment]
Ah Thank you.

I now see that i just copied the .env.example with all the standard MAIL parameters.

Is it an idea to or:
-  Have the MAIL parameters in the .env.example but commented out
-  Have the fields that are overritten by the .env file grayed out in the UI

I also saw that there is no .gitignore in the repo that ignores the .env file, but maybe that is an unnecessary rfc because nobody can push the code.

Thanks for the Fast reply Though!

**Comment by hillelcoren** [comment]
I think this may be an issue related to running the app using Docker which is preventing it from being able to update the .env file
