### ISSUE TITLE
Volume does not what the comment says it does

### ISSUE THREAD

**Issue by publicarray** [invoiceninja/dockerfiles#131]
TL:DR I propose to remove the Volume statment
 
https://github.com/invoiceninja/dockerfiles/blob/9060027999eea89ca5afc393a0c35e8e295a4db3/Dockerfile#L78-L79

This creates a new volume for persistence.

I wanted to create a volume one folder up `/var/www/app/` but it took me longer than I like to admit to find out why the `/var/www/app/public` was empty in the other container. The `/var/www/app/public` folder was in a different anonymous volume. Mounts should mostly be done by the user with `-v` or `- volumes` in docker-compose.

**Comment by lalop** [comment]
Isn't this required to mount the public folder into the web container https://github.com/invoiceninja/dockerfiles/blob/master/docker-compose/docker-compose.yml

**Comment by publicarray** [comment]
Since you don't know my setup how do you know what is required? At the moment I use openlitespeed in a container to execute the php scripts so It needs access to the vendor folder. in the future I want to migrate and use openlitespeed more as a proxy and use FastCGI

**Comment by lalop** [comment]
I don't know openlitespeed, anyway this image is build to handle the most common use case

**Comment by publicarray** [comment]
Removing the line will have no impact to the common use case as they should already create a volume for app/public so that is a named volume to share the folder with a reverse proxy.
A discussion on when or when not to use VOLUME: https://stackoverflow.com/questions/41935435/understanding-volume-instruction-in-dockerfile#41935728
I argue this is not the correct use case unless there are user files stored there. Maybe related to #129

**Comment by lalop** [comment]
Public hasn't to be a volume in common use case, only the upload folder i think
