### ISSUE TITLE
The buy now buttons won't add

### ISSUE THREAD

**Issue by danielgroen** [invoiceninja/dockerfiles#133]
Hi,

When i want to add "Buy now buttons", and hit the save button, nothing appears. is there any known issue for this.

![image](https://user-images.githubusercontent.com/6578052/78374882-518a0780-75cc-11ea-9e44-7f8118ae708f.png)

**Comment by hillelcoren** [comment]
You need to copy/paste the link, the app generates them it doesn't save them

**Comment by danielgroen** [comment]
Okay, well i thought you could add "buy" buttons at the client dashboard.
I will clarify:

i am a webdeveloper and i'd like to sell hours.
isnt it an idea to have these "buy" buttons also on the client portal?

**Comment by hillelcoren** [comment]
The links/buttons are designed to be used other places online not in the portal

**Comment by danielgroen** [comment]
Okay then!

I was just wondering if it was an idea to also implement them at the client portal which i think would be nice but it was just a suggestion :-) !

**Comment by hillelcoren** [comment]
I guess you could use them in the portal with the custom messages feature?

**Comment by codedge** [comment]
@hillelcoren @lalop  there something left here to do regarding Docker?
