### ISSUE TITLE
Styling updates

### ISSUE THREAD

**Issue by danielgroen** [invoiceninja/dockerfiles#135]
Hi,

i would like to help you guys with some styling updates of the platform itself!
please let me know if there is any need.

I just see that some things can be a bit more pixel perfect. Although i've seen your old design which i very like because it looks very clean

![image](https://user-images.githubusercontent.com/6578052/78377872-7d0ef100-75d0-11ea-8710-1105faa62684.png)

**Comment by hillelcoren** [comment]
Not sure all these issues belong on the dockerfile project?

**Comment by danielgroen** [comment]
Yup sorry, this is more for the invoiceninja/invoiceninja repo. Anyways i am closing this one
