### ISSUE TITLE
update docker hub with new release(s)

### ISSUE THREAD

**Issue by killarny** [invoiceninja/dockerfiles#136]
The latest changes in this repo are for version 4.5.18 of [invoiceninja/invoiceninja](https://github.com/invoiceninja/invoiceninja), but it appears that there have been a number of releases since then according to [the release list for that repo](https://github.com/invoiceninja/invoiceninja/releases) with 5.0.4 released just a couple of days ago.

**Comment by hillelcoren** [comment]
v5.x is a completer rewrite, it will need a separate dockerfile.  

https://www.invoiceninja.com/forums/topic/the-new-invoice-ninja-alpha/

**Comment by gerroon** [comment]
@hillelcoren Can the old database from 4x be used in 5x?

**Comment by hillelcoren** [comment]
No, we've built a tool to migrate the data
