### ISSUE TITLE
Empty logs

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/dockerfiles#137]
Has anyone here managed to get logs in `/var/www/app/storage/logs`? That directory is always empty for me.

- the container's php-fpm master processes run as root
- the container's pool ("www") processes run as www-data or 82
- the container's log directory is `www-data:www-data` and `775`

**Comment by codedge** [comment]
Is there anything in particular you like to see in the logs?

IN runs in production mode and with `APP_DEBUG=0` which means only serious errors will be logged.
So if your IN installation runs without problems why should there be any log file?

**Comment by lonix1** [comment]
You're assuming my installation "runs without problems". 😉

When facing problems I kept reading that I should check my log files. But I don't have any.

**Comment by codedge** [comment]
Can you name a use case (that you face) where you have a serious problem with IN and therefore should habe a log file in the `storage/logs` folder?

**Comment by lonix1** [comment]
I struggled to get my installation working due to nginx configuration problems. Others faced similar problems and were told to "check their log files".

So I tried to check my log files and discovered I don't have any.

**Comment by lalop** [comment]
If you don't override the log variable the log should go in the docker output
https://github.com/invoiceninja/dockerfiles/blob/master/Dockerfile#L73

**Comment by lonix1** [comment]
@lalop Interesting, thanks.

That line shows `ENV LOG errorlog` - what is `errorlog`?

If it is redirected to docker's output / error, I assume output would be redirected to `/dev/stdout` and errors to `/dev/stderr`?

**Comment by codedge** [comment]
`errorlog` from the [Laravel docs](https://laravel.com/docs/5.6/logging) means

> A ErrorLogHandler based Monolog driver

**Comment by codedge** [comment]
@lalop 
> If you don't override the log variable the log should go in the docker output

What happens if the docker container runs detached/in background? I suppose the only way to get the logs then is to do `docker logs`?

**Comment by lalop** [comment]
@codedge exact, the log goes to the standard docker output

**Comment by lalop** [comment]
@lonix1 can we close this ?

**Comment by lonix1** [comment]
ok thanks

**Comment by lonix1** [comment]
@codedge I am using `docker-compose.yml`, and when I added this:

````yml
environment
  LOG=single
````

...and forced some errors, then indeed I found `laravel-error.log` and `stacktrace.log` in the directory `/var/www/app/storage/logs`.

I was thinking that this is not the expected behavior. In all FAQs and other issues, @hillelcoren always says to "check your logs". That means that it is expected that the app would generate logs.

I propose that if the non-docker app automatically generated logs, then the dockerised app should also generate logs (without changing any config settings). Which means that the `Dockerfile` should be edited to contain `LOG=single`.

What do you think @hillelcoren? It would reduce surprise, and improve problem solving in the issues.

**Comment by hillelcoren** [comment]
I'm all for anything which makes it easier for users to have access to their logs.

**Comment by codedge** [comment]
@lalop and me had a discussion about this yesterday evening. There is still an open PR #142 to update the documentation and explain how to view the logs when running IN in Docker.

Logs are always generated, they are just elsewhere. Let me finish this PR and get this merged in.
Then things should be clearer.
