### ISSUE TITLE
Moving cronjobs into main docker image

### ISSUE THREAD

**Issue by codedge** [invoiceninja/dockerfiles#141]
I just came across that in the `docker-compose` setup there is a separate `cron` container to run the cronjob for sending _reminders_ and _invoices_.

@lalop  Is there any particular reason why the cronjob does only exist for `docker-compose` and not for php docker images? 
I would vote for moving the cron into the docker images itself. Cronjobs can easily be run by the `alpine` or `debian`-based images and not one need to take care about settuing them up.

This would bring two advantages:

* We are going to have proper cronjobs inside the php docker images, for non-`docker-compose`
* We would not need another container just for running cronjobs w/ `docker-compose`

**Comment by lalop** [comment]
There is no particular reason, the docker image version of cron in the way it's done on dc is more a lack of documentation then any thing else.
Any way the cron system is pretty rudimentary and some work on this is welcome.

I built this first system regarding how this is handled on other project.
On docker one of the main principle is to have one process per container. Having cronjobs running in background breaks this rule.
For exemple on the official nextcloud image there is a second container https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb-cron-redis/fpm/docker-compose.yml
In the other hand I see the simplicity for the hand user.

I'm not a guru of anything but I would prefer to stay as much standard as possible.
Do you have any counter exemple ?

**Comment by codedge** [comment]
I got your point and I think it is good to leave cronjobs out of the containers / in a separate container. But I'd like to unify the cron script / tasks to have a central place / script to maintain these for both version, with `docker-compose` and without.

I think we also need to update the documentation here on the docker repo about this to give people an immediate hint how to deal with the docker.

So goals summarized:

* Better documentation for cronjobs
* Central file for maintaining cronjobs
  * Idea, `config/invoiceninja-cronjob` file which can either
    1. be mounted into separate cron container
    2. be us used for running cronjobs from the host system if not in `docker-compose` context

OPTIONAL (for `docker-compose` only):
Smaller container for running cronjobs in `docker-compose` setup. Maybe the `php-cli-alpine` image which is only 30MB

If the responsibility for cronjobs are not within the containers, why not always let them run from host system, so no extra container at all?

**Comment by hillelcoren** [comment]
FYI...  in the next version we plan to use Laravel's scheduling feature which should make the crons a bit easier to manage. 

https://laravel.com/docs/7.x/scheduling

**Comment by codedge** [comment]
That's a good thing, but still you need to some set a cronjob, and only if it is for running a single line to start the scheduler :)

**Comment by codedge** [comment]
IN 4 cronjobs are still handled via the `docker-compose.yml`. For IN 5 the cronjobs are moved inside the container.
How cronjobs work for IN with docker is documented in the [wiki](https://github.com/invoiceninja/dockerfiles/wiki/cronjobs).
