### ISSUE TITLE
Support `_FILE` env vars for secret configuration

### ISSUE THREAD

**Issue by decentral1se** [invoiceninja/dockerfiles#149]
Hi folks, thanks for the great work, I've got a favour to ask. 

I'm deploying `invoiceninja` on docker swarm and everything runs smoothly until I realise that I *must* provide a writable `/var/www/app/.env` file. Now, I use a [docker config](https://docs.docker.com/compose/compose-file/#configs) for this file which can never be writable (`tmpfs`, for the purposes of rollback). I can't specify secrets from the `environment` stanza because of [a Docker swarm design decision](https://docs.docker.com/engine/swarm/secrets/#how-docker-manages-secrets) soooo, I am wondering if it would be possible to follow the style of mariadb with their support of secrets:

> https://github.com/docker-library/docs/blob/master/mariadb/README.md#docker-secrets

They offer `_FILE` for the environment variables. So, concretely, you'd provide:

- `DB_PASSWORD` + `DB_PASSWORD_FILE`
- `APP_KEY` + `APP_KEY_FILE`
- `APP_SECRET` + `APP_SECRET_FILE`

This would allow me to specify a  `docker-compose.yml` which can be deployed on Docker swarm with:

```yaml
invoiceninja:
    environment:
        API_SECRET_FILE=/var/run/secrets/api-secret-file-v1
```

I guess you'd also need to change settings logic to not allow these to be changed if using the `_FILE` variables? Unsure. I don't know if you have many swarm deployments which might justify this work but this change would allow them. Otherwise, we have to store secrets in the `docker-compose.yml` configuration which is no bueno.

**Comment by codedge** [comment]
This is connected to #125 

I think we can have a look into that.

**Comment by decentral1se** [comment]
Aha, yes, https://github.com/invoiceninja/dockerfiles/issues/125 is very much related. I guess this ticket is the counter-part upstream in IN which highlights that there are actually application code changes required (that's why I didn't open on dockerfiles side).

If some work does go into this (:partying_face:) I can support by manually testing it!
