### ISSUE TITLE
Error after setup

### ISSUE THREAD

**Issue by peXed** [invoiceninja/dockerfiles#15]
Hello!

I'm trying to get the docker image running. So far, I made it to the setup screen and I could run the setup.

After this, I always get "Whoops, looks like something went wrong." and in the laravel-error.log I get:

`[2016-09-15 11:27:19] production.ERROR: ErrorException: fopen(/var/www/app/storage/version.txt): failed to open stream: Permission denied in /var/www/app/app/Http/Middleware/StartupCheck.php:58 Stack trace: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'fopen(/var/www/...', '/var/www/app/ap...', 58, Array) #1 /var/www/app/app/Http/Middleware/StartupCheck.php(58): fopen('`

Is there something wrong with the permissions in the image or did I something wrong?

Thanks in advance!

**Comment by peXed** [comment]
Ok. I fixed it by my self. Guess there is something wrong in the docker image.
I just did the following:
```
php artisan cache:clear 
chmod -R 777 app/storage 
composer dump-autoload
```

**Comment by lalop** [comment]
Hello @peXed ,
I don't have any permission issue.
How do you run this image ?
Are you using docker inside a vm ?

**Comment by peXed** [comment]
I run it inside a rancher environment.

**Comment by lalop** [comment]
I can't reproduce this issue for the moment.
Did you have the problem on other platform ?

**Comment by peXed** [comment]
No. This was the first time I ran into any chmod related issue.

**Comment by lalop** [comment]
So I imagine this is related to Rancher
