### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by Mzngit** [invoiceninja/dockerfiles#150]
Hi,
Latest update to 4.6.0 results in version listed in the Docker container info as blank. Also, when loading up the invoiceninja page, the version listed on the bottom of each page is still 4.5.18.
Finally, when do you anticipate version 5.0.4 being ready to be deployed as a Docker container? I understand that the database will need to migrated as well, and thus what is the process for doing so?
Thanks in advance.

**Comment by codedge** [comment]
Which image do you use? `alpine`?

**Comment by codedge** [comment]
@Mzngit the issue with the improper version has been fixed. When you pull the images now, IN `4.6.0` runs.

> Docker container info as blank
That problem should be fixed as well. 

About docker for version 5, I cannot tell. It is in planning, but no final date.

**Comment by codedge** [comment]
⚠️ Do not use the `4.6.0`. There were some misunderstandings - `4.6.0` was not meant to be a release. The release was revoked from both repos, invoiceninja and dockerfiles.
