### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by kilabyte** [invoiceninja/dockerfiles#153]
Following the docker-compose it installs successfully with no errors but when i go to the address its just a blank screen. any ideas?

**Comment by codedge** [comment]
Do you see any error when running `docker-compose logs -f` and refreshing the page?

**Comment by kilabyte** [comment]
nope none

**Comment by codedge** [comment]
Can you also insert your `docker-compose.yml` here? I guess you set an `APP_KEY`, right?

**Comment by kilabyte** [comment]
Ya I don't even get that page in chrome. It's just blank. I'll post my compose one sec. And it's a fresh install

**Comment by codedge** [comment]
I see. Can you add `APP_DEBUG=1` to the env var of the app container? That should some info displayed on the screen - hopefully.

**Comment by hillelcoren** [comment]
If you haven't already please check the web server error logs

**Comment by codedge** [comment]
@kilabyte If you start from scratch, ou can also check out the new _5.0.4_ version which is now available for docker. 
The `docker-compose.yml` has been adjusted to use the new version. The configuration is the same, meaning the env vars. 

Happy to help if you encounter problems.

**Comment by kilabyte** [comment]
tried with the new docker compose, fresh install and get the same thing. if i try through https and 443 i get ERR_CONNECTION_CLOSED. However using firefox i can get it to load the page but now i get SQLState connection refused

![image](https://user-images.githubusercontent.com/487948/83165465-6661b380-a0c2-11ea-9d25-e24f10e7fb37.png)

**Comment by codedge** [comment]
Hmm.. there are multiple things:

1. You set the port to `444` in your `docker-compose.yml`. So you need to call it via `localhost:443`.
2. Please run `docker-compose down -v` to also clear the originally created db container and then run `docker-compose up -d`
3. When now opening IN, you will still get an error - but you can manually go to `/setup` to process the installation routine

**Comment by kilabyte** [comment]
ya but im using http not https so should i use 81 on the localhost?

**Comment by codedge** [comment]
Well, the webserver has an automatic redirect to https, even on localhost. Any reason why you use custom ports 81/444? Are the other ones (80/443) already occupied?

So in any case you should be able to get some message, even some error message, on your custom 444 port when running locally with Chrome.

**Comment by kilabyte** [comment]
im gonna try on a vm in another cluster and see with the default ports

**Comment by kilabyte** [comment]
so i spun up a new ubuntu vm and clone this repo added the api key and i dont see a blank screen anymore but i do see error 500 internal server but no errors from the logs

**Comment by kilabyte** [comment]
i guess it NEEDS to have a certificate i cant just run it with localhost?

**Comment by kilabyte** [comment]
now it doesnt load at all firefox or chrome just keep saying waiting for localhost...

**Comment by kilabyte** [comment]
there we go a clean install worked. Ok so i guess i cant have the external ports different then 80 or 443?
