### ISSUE TITLE
bash/cron issue in latest docker image

### ISSUE THREAD

**Issue by grahamPegNetwork** [invoiceninja/dockerfiles#157]
When running my script to pull/update invoiceninja I discovered that the latest (or base?) image appears to have a problem with cron.

I am using a minor variation of the docker-compose file but with a system nginx reverse proxy rather than caddy.

The image I have been using is invoiceninja/invoiceninja (I believe this results in invoiceninja:latest)

System: Debian Buster, latest docker via official repos and docker-compose. (Invoiceninja has been running stable for around a year)

Process for updating: (or switching versions)
```
docker-compose stop
docker-compose pull
docker-compose up --build -d
```
Result: (truncated)
```
Creating invoiceninja_cron_1 ... error
.......
ERROR: for cron  Cannot start service cron: b'OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \\"bash\\": executable file not found in $PATH": unknown'
ERROR: Encountered errors while bringing up the project.

```
I googled around a bit with no significant results, and finally attempted downgrading to version 4.5.17 and 4.5.18 (via updating image in docker-compose) worked fine. 
```image: invoiceninja/invoiceninja:4.5.18
```

Repeating the process with invoiceninja and invoiceninja:latest reproduces the error while numbered versions are working as expected.

My suspicion is that latest has a minor bug resulting in BASH not being available. For now I will be pinning to 4.5.18, but let me know if I can provide any additional information.

**Comment by codedge** [comment]
The `latest` tag includes the version 5 of Invoice Ninja. To stick to version 4, please use `alpine-4` or `4.5.18`.
ℹ️ The `4.5.18` tag is the one suitable for you, I guess. It uses debian under the hood, which uses `bash` and therefore has no problems with the cron command referenced inside the docker-compose file.

As all upcoming version are based on Alpine Linux, the cron command needs to be adjusted.
We are going to release an updated version of the `docker-compose.yml` file which will work with both versions, v4 and v5, at the end of the week.

Thanks for finding the issue. 👍 😃
