### ISSUE TITLE
Add dockerhub tag `4` (like alpine-4)

### ISSUE THREAD

**Issue by oliverpool** [invoiceninja/dockerfiles#158]
My docker install is set to auto update to the latest version. It recently upgraded to v5, which broke my install (see https://github.com/invoiceninja/invoiceninja/issues/3767).

So I wanted to stay on the v4, but there is not tag `4` on dockerhub:
https://hub.docker.com/r/invoiceninja/invoiceninja/tags (there is however a `4-alpine` tag).

In the meantime, I am using the `4.5.18` tag, and everything works fine.
Could you add a `4` tag tracking the latest `4.*` version on debian? (4.5.18 currently)

Thank you!

**Comment by oliverpool** [comment]
I just saw #156 (Remove debian versions).

So I should probably switch to `alpine-4`, is this correct?

**Comment by codedge** [comment]
Yes, correct. Please either use `4.5.18` to pin an exact version or use `alpine-4`. The `alpine-4` will always provide the latest 4.x release
