### ISSUE TITLE
Suggestion: Add Cronjobs to docker image

### ISSUE THREAD

**Issue by peXed** [invoiceninja/dockerfiles#16]
Hello!

After I solved the first, small problems, I have to say invoice ninja seems to be awesome! :+1: 

But I have a suggestion, it would be awesome if the cronjobs for invoiceninja would be included in the docker image as well.

Cheers,
Dom

**Comment by peXed** [comment]
@lalop Thanks. That would be even a better solution! 👍

**Comment by lalop** [comment]
@peXed you will find this in docker-compse.yml
