### ISSUE TITLE
Running the container with only http on internal network

### ISSUE THREAD

**Issue by BusinessVisionEnforced** [invoiceninja/dockerfiles#166]
In the previous version i could just start the container in http only and run the application on an internal IP address.

It looks like this is not possible anymore with caddy installed?
Is there a way to disable caddy?
I'm using docker compose and a reverse proxy in front of it to handle the SSL things.

Would like to see a that i would be possible to just start the container again with only HTTP.

**Comment by codedge** [comment]
The current `docker-compose.yml` provides a setup for IN 5 w/ Caddy in front.

Options:
- Modify the `docker-compose.yml` file to use IN 4 w/o Caddy
- Don't use docker-compose and justbring up the IN container only. For that all steps are described in the readme

The last option could be the one with any web server (Nginx, Apache, ... ) in front just serving the content. 

Does that help?

**Comment by BusinessVisionEnforced** [comment]
Hi Codedge! 
thnx for you response:)

Well i have portainer and use it to automaticaly enroll invoice ninja instances for customers running on the same server all with there own containers.

Is it possible to make it work with docker compose?

**I used this and it worked previously:**

######
version: '3.6'

volumes:
  db:
  storage:
  logo:
  public:

# uncomment if you want to use external network (example network: "web")
#networks:
#  web:
#    external: true

services:
  db:
    image: mysql:5.7
    env_file: .env
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - default

  app:
    image: invoiceninja/invoiceninja
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      -  storage:/var/www/app/storage
      -  logo:/var/www/app/public/logo
      -  public:/var/www/app/public
    networks: 
      - default  

  web:
    image: nginx:1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      -  storage:/var/www/app/storage
      -  logo:/var/www/app/public/logo
      -  public:/var/www/app/public
    expose: # Expose ports without publishing them to the host machine - theyâ€™ll only be accessible to linked services.
      - "80"
    depends_on:
      - app
    ports: # Delete if you want to use reverse proxy
      - 80
    networks:
#      - web        # uncomment if you want to use  external network (reverse proxy for example)
      - default

  cron:
    image: invoiceninja/invoiceninja
    env_file: .env
    volumes:
      -  storage:/var/www/app/storage
      -  logo:/var/www/app/public/logo
      -  public:/var/www/app/public
    entrypoint: |
      sh -c 'sh -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1d
      done
      EOF'
    networks:
      - default

######
**Now i tried this one but wont work because i dont have an DNS full URL only an ip adress and a port..**
#######
version: '3.7'

services:
  server:
    image: caddy:alpine
    restart: always
    environment: 
      - APP_URL=https://localhost
    volumes:
      # Vhost configuration
      - ./Caddyfile:/etc/caddy/Caddyfile

      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
      -  public:/var/www/app/public
      -  storage:/var/www/app/storage
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/app/public:/var/www/app/public:rw,delegated
      # - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    ports: 
      - 8080:80
      - 4443:443
    networks:
      - invoiceninja

  app:
    image: invoiceninja/invoiceninja:5
    restart: always
    environment: 
      - APP_URL=https://192.168.5.70:8080
      - APP_KEY=PQcBXR/kZ9y7eh6nxJRmLwFssmP+I9mrcnkSXbK44sM=
      - MULTI_DB_ENABLED=false
      - DB_HOST1=db
    volumes:
      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
      -  public:/var/www/app/public
      -  storage:/var/www/app/storage
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/app/public:/var/www/app/public:rw,delegated
      # - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    networks: 
      - invoiceninja  

  db:
    image: mysql:5
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_DATABASE=db-ninja-01
    volumes:
      - mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - invoiceninja

 
  # cron:
  #   image: invoiceninja/invoiceninja
  #   volumes:
  #     -  storage:/var/www/app/storage
  #     -  logo:/var/www/app/public/logo
  #     -  public:/var/www/app/public
  #   entrypoint: |
  #     bash -c 'bash -s <<EOF
  #     trap "break;exit" SIGHUP SIGINT SIGTERM
  #     sleep 300s
  #     while /bin/true; do
  #       ./artisan ninja:send-invoices
  #       ./artisan ninja:send-reminders
  #       sleep 1d
  #     done
  #     EOF'
  #   networks:
  #     - invoiceninja

volumes:
  mysql-data:
  public:
  storage:

networks:
  invoiceninja:

**Comment by codedge** [comment]
It looks like that there is no official domain passed to Caddy, instead it uses the IP 172.18.0.4. I think when you pass an individual TLD domain, for which  Caddy can obtain a proper certificate, then these errors should not appear.

The _APP_URL_ env var is responsible for setting the correct domain.


```yml
server:
    image: caddy:alpine
    restart: always
    environment: 
      - APP_URL=https://localhost
    volumes:
```

You can of course just exchange Caddy with nginx. If that one runs better with your setup feel free to update the `docker-compose` you are using. IN is not bound to Caddy, it works with any server in front.

**Comment by BusinessVisionEnforced** [comment]
Hi Codedge,

Thank you for the response!

I'v tried to replace the caddy server to nginx but still get some errors.

Can you send me an example compose file with nginx server that works? 

Thank you in advance!

**Comment by BusinessVisionEnforced** [comment]
Hi all,

Is there anyone how could help me out here?

Thnx!

**Comment by codedge** [comment]
Sorry for the long wait. I wrote some [guides](https://github.com/invoiceninja/dockerfiles/wiki) for setting up IN 4 and 5.
There is also a guide for using nginx, and a sample vhost file. 

Can you check if that helps?

**Comment by gururise** [comment]
I followed the NGINX guide, and after installing everything, I end up with the default, "WELCOME TO NGINX" screen.

**Comment by codedge** [comment]
@BusinessVisionEnforced We weree able to solve the nginx issues for @gururise. 
Let me know if you encounter any problems with the setup described in the wiki.
