### ISSUE TITLE
Failed to parse dotenv file due to unexpected whitespace

### ISSUE THREAD

**Issue by karneaud** [invoiceninja/dockerfiles#170]
Trying to get this up on Docker( based on offical invoiceninja image) running PHP 7.3 with 5.0.12-release and I get the subject error

> The environment file is invalid!
> Failed at [''--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi'']

Turns out  for some reason setup is writing EVERY ENV variable available into the .env file causing this invalid response.

Why is it doing this?

**Comment by turbo124** [comment]
I think this may get better quality responses here

**Comment by karneaud** [comment]
I'm not sure it would as I do not think it is related is it? As a workaround I had to

```
  if (!$this->failsafeMailCheck($request)) {
            $mail_driver = 'log';
        }

        $_ENV['APP_KEY'] = config('app.key');
        $_ENV['APP_URL'] = $request->input('url');
        $_ENV['APP_DEBUG'] = $request->input('debug') ? 'true' : 'false';
        $_ENV['REQUIRE_HTTPS'] = $request->input('https') ? 'true' : 'false';
        $_ENV['DB_TYPE'] = 'mysql';
        $_ENV['DB_HOST1'] = $request->input('host');
        $_ENV['DB_DATABASE1'] = $request->input('database');
        $_ENV['DB_USERNAME1'] = $request->input('db_username');
        $_ENV['DB_PASSWORD1'] = $request->input('db_password');
        $_ENV['MAIL_DRIVER'] = $mail_driver;
        $_ENV['MAIL_PORT'] = $request->input('mail_port');
        $_ENV['MAIL_ENCRYPTION'] = $request->input('encryption');
        $_ENV['MAIL_HOST'] = $request->input('mail_host');
        $_ENV['MAIL_USERNAME'] = $request->input('mail_username');
        $_ENV['MAIL_FROM_NAME'] = $request->input('mail_name');
        $_ENV['MAIL_FROM_ADDRESS'] = $request->input('mail_address');
        $_ENV['MAIL_PASSWORD'] = $request->input('mail_password');
        $_ENV['NINJA_ENVIRONMENT'] = 'selfhost';
        $_ENV['SELF_UPDATER_REPO_VENDOR'] = 'invoiceninja';
        $_ENV['SELF_UPDATER_REPO_NAME'] = 'invoiceninja';
        $_ENV['SELF_UPDATER_USE_BRANCH'] = 'v2';
        $_ENV['SELF_UPDATER_MAILTO_ADDRESS'] = $request->input('mail_address');
        $_ENV['SELF_UPDATER_MAILTO_NAME'] = $request->input('mail_name');
        $_ENV['DB_CONNECTION'] = 'db-ninja-01';

        $config = [];

        $defaults = ['APP_KEY', 'APP_URL','APP_DEBUG','REQUIRE_HTTPS','DB_TYPE','DB_HOST1','DB_DATABASE1','DB_USERNAME1','DB_PASSWORD1','MAIL_DRIVER','MAIL_PORT','MAIL_ENCRYPTION','MAIL_HOST','MAIL_USERNAME','MAIL_FROM_NAME','MAIL_FROM_ADDRESS','MAIL_PASSWORD','NINJA_ENVIRONMENT','SELF_UPDATER_REPO_VENDOR','SELF_UPDATER_REPO_NAME','SELF_UPDATER_USE_BRANCH','SELF_UPDATER_MAILTO_ADDRESS','SELF_UPDATER_MAILTO_NAME','DB_CONNECTION'];
        $filePath = base_path().'/.env';
        

        try { 
            $fp = fopen($filePath, "rw");
            $members = array();
            
            while (!feof($fp)) {
                    $members[] = fgets($fp);
            }
            
            foreach ($defaults as $val) {
                $key = $val;
                $val = $_ENV[$key];
                if (is_array($val) || is_array($key)) {
                    continue;
                }
                if (preg_match('/\s/', $val)) {
                    $val = "'{$val}'";
                }
                $config[] = "{$key}={$val}";
            }

            $config = array_merge($members, $config);
            $config = join("\n", $config);

            /* Write the .env file */
            
            // $fp = fopen($filePath, 'w');
            fwrite($fp, $config);
            fclose($fp);
```

perhaps the can be a way to filter the necessary ENV VARS and also MERGE custom VARS as necessary?

**Comment by codedge** [comment]
Hi @karneaud 

The error `The environment file is invalid!` does not occur in the default setup. 
I am unsure if this is problem with Docker. The docker setup does not modify any IN file.

What new env variables are you trying to set?

**Comment by hillelcoren** [comment]
As the error says one thing to check for is any unexpected whitespace, for example:

`FIELD=some value`

vs

`FIELD="some value"`

**Comment by codedge** [comment]
Correct, this `FIELD=some value` is invalid in `.env` files. Always quote whitespace as show above.
@karneaud As I wrote, we need to know what are you trying to achieve, which env var you want to set, and how you do that. Please also paste the Docker/docker-compose commands you use and/or your `docker-compose.yml` file.

**Comment by karneaud** [comment]
Well i've been at this for 2 weeks trying to get the version to install and it tries to write EVERY ENV variable to the.env. My workaround just limits it to the necessary ones

**Comment by codedge** [comment]
Sorry, but I still have no clue where the problem is. About what env vars you talk? What are the _necessary_ ones? Can you provide code sample/env files/docker commands you run... anything that explains the issue in detail?

Which step of you leads to which result/error?



If not I think we're unable to provide help.
