### ISSUE TITLE
Cannot run container as non-root

### ISSUE THREAD

**Issue by micah** [invoiceninja/dockerfiles#171]
Hi,

Because of the chown in the Dockerfile, it is not possible to run your container as non-root. This is a generally regarded good practice, and many things are moving that direction.  It would be great if this could be resolved :)

**Comment by codedge** [comment]
Hi @micah 

I am not sure if I understand right. Yes, it is definitely possible to run it as non-root. The user on the host system is totally independent from the user inside the container.

Which `chown` do you mean? Can you paste a link to the exact line?

And what is the exact error message?

**Comment by micah** [comment]
I'm using the docker image invoiceninja/invoiceninja, so I'm not sure which version that is, this is what I see on startup:

```
ninja[14583]: chown: /var/www/app/storage/migrations/.gitignore: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/migrations: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/migrations: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/debugbar/.gitignore: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/debugbar: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/debugbar: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/app/.gitignore: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/app: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/app: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/import/.gitignore: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/import: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/import: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/framework/cache/.gitignore: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/framework/cache: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/framework/cache: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/framework/.gitignore: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/framework/views/.gitignore: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/framework/views: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/framework/views: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/framework/.DS_Store: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/framework/sessions/.gitignore: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/framework/sessions: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/framework/sessions: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/framework: Operation not permitted
ninja[14583]: chown: /var/www/app/storage/framework: Operation not permitted
....
```

**Comment by micah** [comment]
It seems to be in the entrypoint.sh:

```
chown -R invoiceninja:www-data /var/www/app/storage /var/www/app/public /var/www/app/bootstrap
```

**Comment by codedge** [comment]
Do you use `docker-compose` or how do you run the image?

**Comment by SinisterCrayon** [comment]
I'm having this exact same issue too when using any bind-mounted directories no matter what permissions I set on them. Using volumes seems to work but is a long way from how I want this to function in my setup as I use bind-mounts for everything else. Even tried doing setgid to see if that would work but to no avail.

**Comment by codedge** [comment]
@SinisterCrayon  Can you show the user and group and permissions for the bind-mounted directories? What is the output of `ls -la <bind-mounted dir>`?

**Comment by MegaphoneJon** [comment]
@codedge I'm having the same problem as @SinisterCrayon.  This problem started when I switched from the `4.5.17` tag to `alpine-4`.  Here is the relevant portion of `docker-compose.yml`:

```yml
  invoiceninja:
    image: invoiceninja/invoiceninja:alpine-4
    container_name: invoiceninja
    env_file: invoiceninja/env
    volumes:
      - "./invoiceninja/public:/var/www/app/public"
      - "./invoiceninja/storage:/var/www/app/storage"
    depends_on:
      - db
    restart: always
```

I saw the note in the `README` to change the file owner/group to `1000:101`.  I do this, but when I start the container, I get the error mentioned above, and the files have the owner group changed to `1000:82`.

**Comment by codedge** [comment]
Thanks for the info @MegaphoneJon . I'll have a look

**Comment by vogelfreiheit** [comment]
I am seeing this issue too, and it also broke the upgrade in a similar way as @MegaphoneJon 's. I filed a separate issue as it manifests as a database configuration issue for me.

**Comment by MegaphoneJon** [comment]
@codedge This is still tagged as "Needs Feedback" - could you let us know what feedback is still needed?  I can replicate this perfectly and can provide what's needed.

Because the migration path to v5 requires upgrading to the latest v4 release, this feels important to resolve as a way to get folks off of unsupported versions.

**Comment by turbo124** [comment]
This should be resolved in the latest dockerfile, if you following the quickstart - and include the ```chown -R 1500:1500 docker/``` you shouldn't see this issue.
