### ISSUE TITLE
Docker-compose file not working

### ISSUE THREAD

**Issue by RafVandelaer** [invoiceninja/dockerfiles#176]
When I use the vanilla docker-compose.yml file from the GitHub page of InvoiceNinja, I get the following error. I have changed al the variables according to the Readme. Does anyone know what causes this error?

ERROR: for test_server_1  Cannot start service server: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/***/test/config/caddy/Caddyfile\\\" to rootfs \\\"/var/lib/docker/overlay2/1f1454ea8eee1d6433ee4eda9a7cc313cbe2a2c54a6bb707d8edf9b95898772b/merged\\\" at \\\"/var/lib/docker/overlay2/1f1454ea8eee1d6433ee4eda9a7cc313cbe2a2c54a6bb707d8edf9b95898772b/merged/etc/caddy/Caddyfile\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for server  Cannot start service server: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/****/test/config/caddy/Caddyfile\\\" to rootfs \\\"/var/lib/docker/overlay2/1f1454ea8eee1d6433ee4eda9a7cc313cbe2a2c54a6bb707d8edf9b95898772b/merged\\\" at \\\"/var/lib/docker/overlay/1f1454ea8eee1d6433ee4eda9a7cc313cbe2a2c54a6bb707d8edf9b95898772b/merged/etc/caddy/Caddyfile\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by codedge** [comment]
Somewhere in your `docker-compose.yml` it seems you have modified the path for the `Caddyfile` to `/home/***/test/config/caddy/Caddyfile\` - but this folder does not exist on your host system.

I don't know where this path `/home/***/test/config/caddy/Caddyfile\` comes from but it is not in the vanilla version of thee `docker-compose.yml`.

**Comment by RafVandelaer** [comment]
I blanked out my username for security reasons.
Yesterday I tested it on a virtual ubuntu server. The output stayed the same with the following yml being used:


[docker-compose.yml](https://github.com/invoiceninja/dockerfiles/files/4993889/docker-compose.txt)

**Comment by codedge** [comment]
Is it possible that you did not clone this repo before? 

To run a fresh installation with docker-compose please do:

1. Create a new folder, e. g. `/home/test/my-new-in-setup`
2. Clone this repository with `git clone https://github.com/invoiceninja/dockerfiles.git .`
3. Run docker-compose with `docker-compose up -d`

The error you described comes from the fast that you do not have the [config folder of this repo](https://github.com/invoiceninja/dockerfiles/tree/master/config) here aside the docker-compose.yml file.

**Comment by RafVandelaer** [comment]
This fixes the problem! Thanks!!

**Comment by theobouwman** [comment]
@codedge I still have this problem when using a fresh clone of the project...
