### ISSUE TITLE
Oops, something doesn't look right! "I could not find NPM anywhere. Is it installed?" (same with Node)

### ISSUE THREAD

**Issue by oezh** [invoiceninja/dockerfiles#178]
Installed in new host (clean ubuntu 20.04, cloning this git) with docker-compose using tag invoiceninja/invoiceninja:5.0.13 when I open https://mydomain.com/setup I get a screen checking for dependencies and 2 are missing: NPM an Node

<img width="693" alt="Screen Shot 2020-07-29 at 11 58 30 PM" src="https://user-images.githubusercontent.com/60199744/88883111-181f7c80-d1f9-11ea-84d8-71ea67c4b1c3.png">

How do I install those?

**Comment by codedge** [comment]
This is a thing that needs to be fixed inside the image. I'll try to provide a fix asap. This is the same issue as in #168

**Comment by botzill** [comment]
same issue here, thx!
