### ISSUE TITLE
Server Error 500 | SQLSTATE[HY000] [1044]

### ISSUE THREAD

**Issue by w4tzmann** [invoiceninja/dockerfiles#190]
After fixing the Redirect / HTTPS error in # 180, I run into a new problem :(
Opening the website brings me a 500 | Server failure
After enabling debugging, it looks like a SQL connection problem:

> SQLSTATE[HY000] [1044] Access denied for user 'ninja'@'%' to database 'ninja' (SQL: select * from information_schema.tables where table_schema = ninja and table_name = accounts and table_type = 'BASE TABLE')
> (3/3) QueryException
> SQLSTATE[HY000] [1044] Access denied for user 'ninja'@'%' to database 'ninja' (SQL: select * from information_schema.tables where table_schema = ninja and table_name = accounts and table_type = 'BASE TABLE')
> 
> in Connection.php line 669
> at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = \'BASE TABLE\'', array('ninja', 'accounts'), object(Closure))
> in Connection.php line 629
> at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = \'BASE TABLE\'', array('ninja', 'accounts'), object(Closure))
> in Connection.php line 338
> at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = \'BASE TABLE\'', array('ninja', 'accounts'))
> in MySqlBuilder.php line 18
> at MySqlBuilder->hasTable('accounts')
> in Facade.php line 261
> at Facade::__callStatic('hasTable', array('accounts'))
> in Handler.php line 60
> at Handler->report(object(QueryException))
> in HandleExceptions.php line 92
> at HandleExceptions->handleException(object(QueryException))
> (2/3) PDOException
> SQLSTATE[HY000] [1044] Access denied for user 'ninja'@'%' to database 'ninja'
> 
> in PDOConnection.php line 31
> at PDOConnection->__construct('mysql:host=db;port=3306;dbname=ninja', 'ninja', 'ninja', array(0, 2, 0, false, false))
> in Connector.php line 67
> at Connector->createPdoConnection('mysql:host=db;port=3306;dbname=ninja', 'ninja', 'ninja', array(0, 2, 0, false, false))
> in Connector.php line 46
> at Connector->createConnection('mysql:host=db;port=3306;dbname=ninja', array('driver' => 'mysql', 'host' => 'db', 'database' => 'ninja', 'username' => 'ninja', 'password' => 'ninja', 'port' => '3306', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'prefix_indexes' => true, 'strict' => false, 'engine' => 'InnoDB ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8', 'name' => 'db-ninja-01'), array(0, 2, 0, false, false))
> in MySqlConnector.php line 24
> at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'db', 'database' => 'ninja', 'username' => 'ninja', 'password' => 'ninja', 'port' => '3306', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'prefix_indexes' => true, 'strict' => false, 'engine' => 'InnoDB ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8', 'name' => 'db-ninja-01'))
> in ConnectionFactory.php line 182
> at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
> at call_user_func(object(Closure))
> in Connection.php line 924
> at Connection->getPdo()
> in Connection.php line 959
> at Connection->getReadPdo()
> in Connection.php line 404
> at Connection->getPdoForSelect(true)
> in Connection.php line 330
> at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = \'BASE TABLE\'', array('ninja', 'accounts'))
> in Connection.php line 662
> at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = \'BASE TABLE\'', array('ninja', 'accounts'), object(Closure))
> in Connection.php line 629
> at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = \'BASE TABLE\'', array('ninja', 'accounts'), object(Closure))
> in Connection.php line 338
> at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = \'BASE TABLE\'', array('ninja', 'accounts'))
> in MySqlBuilder.php line 18
> at MySqlBuilder->hasTable('accounts')
> in Facade.php line 261
> at Facade::__callStatic('hasTable', array('accounts'))
> in Handler.php line 60
> at Handler->report(object(QueryException))
> in HandleExceptions.php line 92
> at HandleExceptions->handleException(object(QueryException))
> (1/3) PDOException
> SQLSTATE[HY000] [1044] Access denied for user 'ninja'@'%' to database 'ninja'
> 
> in PDOConnection.php line 27
> at PDO->__construct('mysql:host=db;port=3306;dbname=ninja', 'ninja', 'ninja', array(0, 2, 0, false, false))
> in PDOConnection.php line 27
> at PDOConnection->__construct('mysql:host=db;port=3306;dbname=ninja', 'ninja', 'ninja', array(0, 2, 0, false, false))
> in Connector.php line 67
> at Connector->createPdoConnection('mysql:host=db;port=3306;dbname=ninja', 'ninja', 'ninja', array(0, 2, 0, false, false))
> in Connector.php line 46
> at Connector->createConnection('mysql:host=db;port=3306;dbname=ninja', array('driver' => 'mysql', 'host' => 'db', 'database' => 'ninja', 'username' => 'ninja', 'password' => 'ninja', 'port' => '3306', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'prefix_indexes' => true, 'strict' => false, 'engine' => 'InnoDB ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8', 'name' => 'db-ninja-01'), array(0, 2, 0, false, false))
> in MySqlConnector.php line 24
> at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'db', 'database' => 'ninja', 'username' => 'ninja', 'password' => 'ninja', 'port' => '3306', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'prefix_indexes' => true, 'strict' => false, 'engine' => 'InnoDB ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8', 'name' => 'db-ninja-01'))
> in ConnectionFactory.php line 182
> at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
> at call_user_func(object(Closure))
> in Connection.php line 924
> at Connection->getPdo()
> in Connection.php line 959
> at Connection->getReadPdo()
> in Connection.php line 404
> at Connection->getPdoForSelect(true)
> in Connection.php line 330
> at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = \'BASE TABLE\'', array('ninja', 'accounts'))
> in Connection.php line 662
> at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = \'BASE TABLE\'', array('ninja', 'accounts'), object(Closure))
> in Connection.php line 629
> at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = \'BASE TABLE\'', array('ninja', 'accounts'), object(Closure))
> in Connection.php line 338
> at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = \'BASE TABLE\'', array('ninja', 'accounts'))
> in MySqlBuilder.php line 18
> at MySqlBuilder->hasTable('accounts')
> in Facade.php line 261
> at Facade::__callStatic('hasTable', array('accounts'))
> in Handler.php line 60
> at Handler->report(object(QueryException))
> in HandleExceptions.php line 92
> at HandleExceptions->handleException(object(QueryException))
> 

For testing purposes, I'll use the standard database credentials.

Ping from app to db works.

My docker-compose.yml ist still the old

**Comment by codedge** [comment]
It seems IN cannot connect to the database. Just to comparee with you (and the values in your `docker-compose.yml`) - you connect with these credentials from IN to you database:

Explcitly set in your docker-compose.yml:
* `DB_HOST1`: db - that is the db container

Default values, if not explicitly set in your `docker-compose.yml`
* `DB_USERNAME1`: `ninja`
* `DB_PASSWORD1`: `ninja`
* `DB_DATABASE1`: `ninja`

I suppose something changed with the default values, as the database created in your mysql container is `db-ninja-01` (see `MYSQL_DATABASE=db-ninja-01`).

So what you can do is to set thse values
* `DB_USERNAME1`: `ninja`
* `DB_PASSWORD1`: `ninja`
* `DB_DATABASE1`: `ninja`

explicitly in your `app` container to override the default values. Your environment vars of your `app` container then look like this:

```yml
environment:
      - APP_URL=https://invoiceninja.tld
      - APP_KEY=%key%
      - MULTI_DB_ENABLED=false
      - DB_HOST1=db
      - DB_USERNAME1=ninja
      - DB_PASSWORD1=ninja
      - DB_DATABASE1=ninja

```

**Comment by w4tzmann** [comment]
Thanks!
Setting these environment parameters brings me to the next:

> The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.


But I'm a little confused, because in the provided docker-compse.yml the databasename is set to `MYSQL_DATABASE=db-ninja-01

**Comment by codedge** [comment]
The first error is because you did not correctly set an application key - check [here](https://github.com/invoiceninja/dockerfiles/wiki/debugging-&-faq#missing-or-wrong-application-key) for more information.

The thing with the database you are completely correct. You need to set it to `DB_DATABASE1=db-ninja-01`, besically the same as in your mysql container. I will fix this in my comment.

**Comment by w4tzmann** [comment]
ok I  missed the "base64:" prefix

Thank you very much for your assistent, in is up and running now!
