### ISSUE TITLE
Other problem with PDF (phatonjs)

### ISSUE THREAD

**Issue by Punkado** [invoiceninja/dockerfiles#204]
Hello!

I have a invoice ninja installation, in docker, running more then one year and since some months, i am having a lot of problems in the PDF invoice by email. I always used the PHANTOMJS_CLOUD_KEY="a-demo-key-with-low-quota-per-ip-address" and it is not working anymore. I also create account and put my own key, and i get the same problem, the pdf in the email is always corrupted. 

So i thought that was something in my installation, then i started a fresh new VPS, installed docker, use the exactly guide here, to install the invoice ninja 4 with Caddy, create a test client and a test invoice and got the same problem.

I don't know what else can i test or check, any ideas?

**Comment by hillelcoren** [comment]
- Did anything change to make it stop working?

- Do you think the problem is related to running the app with Docker?

**Comment by Punkado** [comment]
I probably made a upgrade to the 4.5.19, but i just made a test, setup a fresh installation again, now with 4.5.18... same problem.

I dont know if is just with the Docker, the app without docker use local PHANTOMJS, that i cant install inside of the container to test... Well i could, but would be a little hard.

**Comment by hillelcoren** [comment]
Sorry, I'm not sure. Maybe the info here will help:

https://docs.invoiceninja.com/configure.html#troubleshooting

**Comment by Punkado** [comment]
I checked already the troubleshooting guide and didn't solve...

The problem is really easy to reproduce, anyone following the official installation guide will have the same problem that I am describing.

**Comment by hillelcoren** [comment]
We've found PhantomJS to be very flaky and are dropping it in v5

Sorry I'm not able to provide more help

**Comment by Punkado** [comment]
So the solution is to migrate to v5, even though that is in beta?

I had problems in the migration, but this is a problem for other issue report...

**Comment by hillelcoren** [comment]
I believe it can be made to work in v4, other users have reported trouble but have gotten it working 

We hope the feature is more reliable in v5...
