### ISSUE TITLE
Environment variables not read during setup

### ISSUE THREAD

**Issue by thomascenni** [invoiceninja/dockerfiles#206]
Hi,
I am installing invoiceninja:5.0.17 in a VPS.
I think I managed php-fm working because I am reaching the setup installation page.
The problem is that my environment variables:

DB_TYPE=mysql
MULTI_DB_ENABLED=false
DB_HOST=srv-captain--in-db
DB_USERNAME=invoiceninja
DB_PASSWORD=blablabla
DB_DATABASE=ninja

are not read, because I see the setup page with default values, like **db-ninja-01** for database or **localhost**:

![Screen Shot 2020-10-31 at 21 00 50](https://user-images.githubusercontent.com/33039107/97792388-3dd36d80-1bbc-11eb-98f0-96ab2fb9d046.png)

Any suggestion ?

# Setup information

RAM: 7.79 GB
OS: linux
CPU: 4 cores
Architecture: x86_64
Docker Version: 19.03.12

**Comment by turbo124** [comment]
The setup DB fields are only hints and are not read in from the _env variables.

For the host you need to enter ```db``` also, the variables are prefixed as below for an example.

```
    environment: 
      - APP_URL=http://in.localhost:8001/
      - APP_KEY=base64:[]
      - APP_DEBUG=true
      - MULTI_DB_ENABLED=false
      - DB_HOST1=db
      - DB_USERNAME1=ninja
      - DB_PASSWORD1=ninja
      - DB_DATABASE1=ninja
```

**Comment by turbo124** [comment]
@thomascenni  we've rewritten the dockerfiles for a cleaner setup and installation. Can you try again from a fresh setup using the quickstart in the readme.

**Comment by thomascenni** [comment]
> @thomascenni we've rewritten the dockerfiles for a cleaner setup and installation. Can you try again from a fresh setup using the quickstart in the readme.

@turbo124
If I understood well in the readme, the variables are defined in a env file and this file will be used during the setup.
Today I'm trying to setup InvoiceNinja as a one-click Caprover app (https://caprover.com/), and in this case the variables are common environment variables.
In the template for Caprover, the variable can be predefined, for example:

DB_DATABASE: ninja
or can be asked as a user input in a form:
DB_PASSWORD: $$cap_db_invoiceninja_password

but in any case will be treated as an environment variable, I don't have the possibility to read from a file.

See my template here (is very similar to a docker compose file): 
https://gist.github.com/thomascenni/d2e68eb54484f8d9bb797e9a0c2d296d

I modified the gist to use the last image invoiceninja:5 and also the variables using "1" as a suffix, but still no chance to read from env variables.

**Comment by turbo124** [comment]
@thomascenni in the gist you are defining them in the compose file, so this is fine.

which other .env vars are you unable to read in?

**Comment by thomascenni** [comment]
All are not read, because I always have the same predefined setup for variables as above
https://github.com/invoiceninja/dockerfiles/issues/206#issue-733831337
(for example db-ninja-01)
If I enter manually the DB connection variables, the setup then works fine.

**Comment by turbo124** [comment]
The /setup page will write additional variables to the .env and also create the first user account.
