### ISSUE TITLE
Out of date images on DockerHub

### ISSUE THREAD

**Issue by hmnd** [invoiceninja/dockerfiles#207]
Hey there. Thanks for putting this together! Could you please update the v5 image on DockerHub to the latest v5.0.23? Would love to get the latest fixes without having to push my own image.

**Comment by hillelcoren** [comment]
@lalop @codedge Can you help explain the process to update the Dockerfile, maybe we can automate it as part of the release process?

cc: @turbo124

**Comment by turbo124** [comment]
@hmnd @hillelcoren 

I've push a new image up. 

Let us know if there are any issues.
