### ISSUE TITLE
Web Server does not start

### ISSUE THREAD

**Issue by seybi87** [invoiceninja/dockerfiles#21]
Hi,

I tried the dockerfile on an Ubuntu 14.04 virtual machine with Docker 1.12 and Docker-Compose 1.8.1

The containers are started (docker ps) but it seems the webserver does not come up as no process listens on port 80 (netstat -tulpn) or any other port.

The startup log of docker-compose:

`Attaching to exemple_db_1, exemple_cron_1, exemple_app_1, exemple_web_1
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.527466Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.531551Z 0 [Note] mysqld (mysqld 5.7.16) starting as process 1 ...
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.537795Z 0 [Note] InnoDB: PUNCH HOLE support available
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.538787Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.538813Z 0 [Note] InnoDB: Uses event mutexes
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.538830Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.538840Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.538849Z 0 [Note] InnoDB: Using Linux native AIO
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.540094Z 0 [Note] InnoDB: Number of pools: 1
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.540224Z 0 [Note] InnoDB: Using CPU crc32 instructions
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.541678Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.555507Z 0 [Note] InnoDB: Completed initialization of buffer pool
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.559945Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.577244Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.578641Z 0 [Note] InnoDB: Log scan progressed past the checkpoint lsn 12137730
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.582097Z 0 [Note] InnoDB: Doing recovery: scanned up to log sequence number 12137739
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.582431Z 0 [Note] InnoDB: Doing recovery: scanned up to log sequence number 12137739
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.582873Z 0 [Note] InnoDB: Database was not shutdown normally!
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.582899Z 0 [Note] InnoDB: Starting crash recovery.
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.703678Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.705344Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.705496Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.841473Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.842364Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.842372Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.842604Z 0 [Note] InnoDB: Waiting for purge to start
^[[32mapp_1   |^[[0m MySQL Connection Error: SQLSTATE[HY000] [2002] Connection refused
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.892775Z 0 [Note] InnoDB: 5.7.16 started; log sequence number 12137739
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.893098Z 0 [Note] Plugin 'FEDERATED' is disabled.
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.896920Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.898799Z 0 [Note] InnoDB: Buffer pool(s) load completed at 161028 14:00:23
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.899598Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.900180Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.900452Z 0 [Note] IPv6 is available.
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.900513Z 0 [Note]   - '::' resolves to '::';
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.900751Z 0 [Note] Server socket created on IP: '::'.
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.905302Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.905377Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.907566Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.913565Z 0 [Note] Event Scheduler: Loaded 0 events
^[[36mdb_1    |^[[0m 2016-10-28T14:00:23.913899Z 0 [Note] mysqld: ready for connections.
^[[36mdb_1    |^[[0m Version: '5.7.16'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
^[[32mapp_1   |^[[0m MySQL ready
^[[32mapp_1   |^[[0m start
^[[32mapp_1   |^[[0m [28-Oct-2016 14:00:26] NOTICE: fpm is running, pid 1
^[[32mapp_1   |^[[0m [28-Oct-2016 14:00:26] NOTICE: ready to handle connections`

Any help is much appreciated.

Cheers

**Comment by lalop** [comment]
Hello @seybi87 ,
Did you have this issue with the last image ?

**Comment by pierreozoux** [comment]
@seybi87 can you `docker-compose ps`?

Also, related to https://github.com/invoiceninja/dockerfiles/pull/26 the current docker-compose starts the web server on a random port on the host.
You should apply the change in the mentionned pr, it should solve your issue.
