### ISSUE TITLE
Docker container doesn't link storage directory

### ISSUE THREAD

**Issue by brianwk** [invoiceninja/dockerfiles#211]
The Docker container does not link the storage link, which is done with the following artisan command:

`php artisan storage:link`

This results in the client invoices not being accessible under the public directory. Let me know if I should submit a patch / PR for this.

**Comment by szamengo** [comment]
Please do the patch asap! 
I think this is the fix for logo display in documents and pdf sending as attachment.
Thank you for your help!

**Comment by turbo124** [comment]
This shouldn't be required any more, the default storage location has been moved to /public/storage so no need for symlink

**Comment by szamengo** [comment]
So how the docker-compose should be modify to map volumes to var/www/app/public in order to have invoices accesibles?

**Comment by turbo124** [comment]
@szamengo So i believe using the defaults, the volume mounts to ```/var/lib/docker/volumes/dockerfiles_public/_data/``` and not to the defined mount point. I am not sure why. I think the original intention is to lower the barrier to get the container up and running at the expense of the correct mounting location.

If I uncomment the bind-mounted line instead - the container fails to mount with chown dir issues on the defined directory... I am get past this at the moment, but I feel this should resolve the issue you are seeing.

**Comment by szamengo** [comment]
Dear @turbo124 ... no unfortunately not works ...

the path of my  invoiceninja dockerfiles is <home>invoiceninja/dockerfiles

I created /var/www/app/public and the same for storage with chown root:root ... I've no web server on my ubuntu.
I uncomment bin-mounted line but not works for me .. perhaps I make a mistake on volume mounts ...
Could you please suggest the right mounts?

Thank you
Silvia

**Comment by szamengo** [comment]
PS: I choose nginx only http protocol ports 80:80

**Comment by turbo124** [comment]
@szamengo I'm stuck on this also. I can't seem to get the mounts anywhere other than /var/lib/docker/volumes.

**Comment by szamengo** [comment]
Ok! I'm waiting for your trick ! Perpaps the fix of @brianwk could be the right way!

**Comment by turbo124** [comment]
@szamengo  we've rewritten the dockerfiles for a cleaner setup and installation. Can you try again from a fresh setup using the quickstart in the readme.

**Comment by szamengo** [comment]
Dear David,
I saw yesterday and I think I have to set up my nginx configuration for ssl
connection... When I'll done I'll keep you posted

Thank you for the assistance
Silvia

Il mar 5 gen 2021, 02:14 David Bomba <notifications@github.com> ha scritto:
