### ISSUE TITLE
Unable to get it work on Unraid Server (V5)

### ISSUE THREAD

**Issue by Wystik-69** [invoiceninja/dockerfiles#212]
Hello everyone,

I've been trying for several hours to make the docker work under Unraid, but I can't reach the configuration page.

The database is created (MariaDB)

I get the error: ERR_CONNECTION_RESET

I put below the configuration of the docker :

![image](https://user-images.githubusercontent.com/63404022/99910343-b5914580-2ced-11eb-9eba-827c1f47cb4a.png)

Is there something badly configured?

Thanks

**Comment by n0ahk** [comment]
Are you getting some kind of error when trying to create it?

**Comment by Wystik-69** [comment]
No error ! Logs are perfect :
Configuration cache cleared!
Configuration cached successfully!
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Files cached successfully!
[22-Nov-2020 17:03:41] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[22-Nov-2020 17:03:41] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[22-Nov-2020 17:03:41] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[22-Nov-2020 17:03:41] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[22-Nov-2020 17:03:41] NOTICE: fpm is running, pid 1
[22-Nov-2020 17:03:41] NOTICE: ready to handle connections

**Comment by turbo124** [comment]
The default webserver is Caddy, I found I was unable to get it working with Caddy also, I had to comment out caddy and implement nginx and then i was able to boot the container.

**Comment by Wystik-69** [comment]
@turbo124 Humm ok, but on Unraid i can only pull the image that is on DockerHub how can I easily change Caddy to Nginx ?

I have already a Docker Caddy that's work only as a reverse proxy, i use it for a Wordpress docker and I want use it also for the InvoiceNinja docker.

**Comment by turbo124** [comment]
@Wystik-69 ok, so you are not using the docker-compose.yml file in this repo?

**Comment by Wystik-69** [comment]
Absolutley, Unraid doesnt support Compose natively as you can see on my screenshot, i can only specify the dockerhub repo and the wanted variable.

**Comment by turbo124** [comment]
@Wystik-69 I'm not sure what to suggest. I'm not an expert with Docker, and have zero experience with Caddy. Can you see any errors in the container logs?

**Comment by Wystik-69** [comment]
No I don't have any errors, all seems ok, just there is no webUI when i try to get the first setup page.

**Comment by Wystik-69** [comment]
Ok now it is working ;) 
![image](https://user-images.githubusercontent.com/63404022/100074146-b08fdb80-2e3e-11eb-826c-7f986b738e27.png)

Here's the guide :

1-Mount volume on CaddyV2 Docker : 

![image](https://user-images.githubusercontent.com/63404022/100074288-da490280-2e3e-11eb-9ce3-98eed02e0ac1.png)

Keep the /app do not change the name, i dont know why but it is working only with app as name.

2- Edit the port of your InvoiceNinja Docker :
![image](https://user-images.githubusercontent.com/63404022/100074930-9c98a980-2e3f-11eb-906a-17b5c309acf2.png)

Use the port 9000 on the dockerside, and what you want in host side. In my case 9191:9000

3- Edit de CaddyFile as followed

invoices.domain.com {
    root * /var/www/app/public/
    php_fastcgi 192.168.0.10:**9191** (I have used the 192.168.0.X IP because my UnraidServer is completly dumb and dont reconize 127.0.0.1 or localhost). 
    encode zstd gzip
    file_server browse
}

And voilà

Feel Free to make a big guide for all my friends who are using Unraid and want to get InvoiceNinja on it.

I've checked on the Unraid forum there are a lot of people they are trying to get it works.

**Comment by turbo124** [comment]
@Wystik-69 thank you for posting your fix!

**Comment by Wystik-69** [comment]
Edit : You must bind the storage to the CaddyDocker in order to get access to the PDF : 
![image](https://user-images.githubusercontent.com/63404022/100086790-2d768180-2e4e-11eb-98f5-5aa286ca825d.png)

Then execute the following command in the InvoiceNinja Docker Shell : **php artisan storage:link**

Now I get an **error 50**0 when i submit the setup page... :

![image](https://user-images.githubusercontent.com/63404022/100086969-5f87e380-2e4e-11eb-95be-f701b2dbda3b.png)

**Comment by turbo124** [comment]
@Wystik-69 you want to chang ```APP_DEBUG=true``` and inspect the error.

**Comment by Wystik-69** [comment]
Mission complete 

![image](https://user-images.githubusercontent.com/63404022/100202716-fc578900-2f01-11eb-8db4-6a8e64d426ec.png)

**Comment by hillelcoren** [comment]
Hooray!! Awesome, thanks!!

**Comment by Wystik-69** [comment]
**DOCUMENTATION FOR INVOICENINJA V5 on UNRAID by Wystik-69**

_*  Prerequisites *_

- CaddyV2 Docker (Available in CommunityAPP)
- MariaDB or MySQL Docker (Available in CommunityAPP)
- InvoiceNinja Docker (My Version is not Downloadable in CommunityApp)


**_MAKE SURE TO FOLLOW STEP BY STEP AND IN THIS ORDER :_** 

**1 - MariaDB Docker**
- Access with PhPMyAdmin Docker or directly in batch to your MariaDB and create a database.
- Is result you will get :
DBNAME : invoiceninja
Encode method : utf8_general_ci
Username : root or user created for it
Password : password used for accessing this db. 

Now we have done with the db creation keep this infos.

**2 - CaddyV2 Docker**

2.1 - Configure CaddyV2 for redirecting to InvoiceNinja Docker :
Make sure you can easily access and write in the CaddyFile file, in my case i've created and empty file using WinSCP in : /mnt/user/appdata/caddyv2/**Caddyfile**

And i've mapped in the docker this file, then i can edit it easily. 

That give us in a volume mapping creation : 
Docker path : /etc/caddy/Caddyfile
Host path : /mnt/user/appdata/caddyv2/Caddyfile

Exemple : 
![image](https://user-images.githubusercontent.com/63404022/100205361-5017a180-2f05-11eb-83ea-44e8e0ac81a6.png)

2.2 : Add to volume mapping in CaddyV2 : 
![image](https://user-images.githubusercontent.com/63404022/100205716-c0bebe00-2f05-11eb-9399-96881b054f8c.png)
![image](https://user-images.githubusercontent.com/63404022/100205741-c9af8f80-2f05-11eb-96c3-f9f0fdda6fa4.png)

Keep the /app/ do not rename it. I've tried and this is not working. 

Now CaddyV2 will have read/write access to future InvoiceNinja WebServer File. 

**3 - InvoiceNinja Docker**

3.1 Create a new template in the Docker tab here all the fields to fill **(use the advanced view)** :

name : invoiceninjaV5
ref : invoiceninja/invoiceninja
dockerhub URL : https://hub.docker.com/r/invoiceninja/invoiceninja
icon URL : https://raw.githubusercontent.com/hillelcoren/invoice-ninja/master/public/images/round_logo.png
network type : bridge
--- You have to create the variable for each in Unraid UI --- 
Exemple :
![image](https://user-images.githubusercontent.com/63404022/100204660-6a9d4b00-2f04-11eb-9545-ea3e9c2d16bd.png)


APP_URL: sub or domain that you will use.
APP_KEY : left it empty for now.
MULTI_DB_ENABLED : false
DB_HOST1 : IP of the mariaDB docker. (can be localhost or the same IP as Unraid)
DB_PORT1 : PORT of you MariaDB Docker (do not write you port in DB_HOST1 variable that's will not work.
DB_USERNAME1 : root or whatever you choose from the previous DB steps.
DB_PASSWORD1 : The DB password.
DB_DATABASE1: : the name use for the database. (invoiceninja in my case)

--- You have to create the volumes mapping for each in Unraid UI --- 
![image](https://user-images.githubusercontent.com/63404022/100204604-59543e80-2f04-11eb-9b8c-5db0909fe26b.png)
 Storage folder
Docker path : /var/www/app/storage
Host path : /mnt/user/appdata/invoiceninja/storage

![image](https://user-images.githubusercontent.com/63404022/100205024-e4353900-2f04-11eb-8282-0e6870601f99.png)

Public folder (used by caddy for publish you website)
Docker path : /var/www/app/public
Host path : /mnt/user/appdata/invoiceninja/public

**3.2 Generating the App Key** 

First before validate your docker config, you will add in "post argue" or "post variable" : php artisan key:generate --show (you will remove this after)

![image](https://user-images.githubusercontent.com/63404022/100206862-2bbcc480-2f07-11eb-8b68-34d6ca2147ed.png)

Now submit everything and start the docker.

It will stop immediatly, you just have to go the logs of the docker from the UnRaid WebUI and copy your key ;) 

Now edit your Docker config, remove the post variable and fill the key field including "base64:"

You can now start your InvoiceNinja Docker everything is configured for it. 

**4 : Edit CaddyFile.**
Now go to your CaddyFile mapped with FTP or elses. 

And add this line : 

```
domain.com  {
    root * /var/www/app/public/ (path that CaddyV2 will read, that the volume mapped in the previous step)
    php_fastcgi DOCKERIP:PORT (the port used for the InvoiceNinja Docker)
    encode zstd gzip
    file_server browse
}

Exemple :
invoices.google.com {
    root * /var/www/app/public/
    php_fastcgi 192.168.0.10:9000
    encode zstd gzip
    file_server browse
}

```
Reboot CaddyV2. 

Access the IP used and you are on the InvoiceNinja setup !

**Comment by turbo124** [comment]
Thanks for this contribution!

**Comment by shrippen** [comment]
This all worked rather well but I can't get past the setup because when I click on Test PDF it says "Oops, looks like something isn't correct!"

The log files are not really helpful either.

`2021-03-28 17:47:19,435 INFO reaped unknown pid 380 (exit status 0)
2021-03-28 17:47:19,436 INFO reaped unknown pid 381 (exit status 0)
2021-03-28 17:47:19,436 INFO reaped unknown pid 401 (exit status 0)`

I have set PHANTOMJS_PDF_GENERATION to false.

What can i try?

**Comment by beganovich** [comment]
Hey there, thanks, I'll check this and get back to you soon 👍

**Comment by kweefc** [comment]
> **DOCUMENTATION FOR INVOICENINJA V5 on UNRAID by Wystik-69**
> 
> _* Prerequisites *_
> 
> * CaddyV2 Docker (Available in CommunityAPP)
> * MariaDB or MySQL Docker (Available in CommunityAPP)
> * InvoiceNinja Docker (My Version is not Downloadable in CommunityApp)
> 
> **_MAKE SURE TO FOLLOW STEP BY STEP AND IN THIS ORDER :_**
> 
> **1 - MariaDB Docker**
> 
> * Access with PhPMyAdmin Docker or directly in batch to your MariaDB and create a database.
> * Is result you will get :
>   DBNAME : invoiceninja
>   Encode method : utf8_general_ci
>   Username : root or user created for it
>   Password : password used for accessing this db.
> 
> Now we have done with the db creation keep this infos.
> 
> **2 - CaddyV2 Docker**
> 
> 2.1 - Configure CaddyV2 for redirecting to InvoiceNinja Docker : Make sure you can easily access and write in the CaddyFile file, in my case i've created and empty file using WinSCP in : /mnt/user/appdata/caddyv2/**Caddyfile**
> 
> And i've mapped in the docker this file, then i can edit it easily.
> 
> That give us in a volume mapping creation : Docker path : /etc/caddy/Caddyfile Host path : /mnt/user/appdata/caddyv2/Caddyfile
> 
> Exemple : ![image](https://user-images.githubusercontent.com/63404022/100205361-5017a180-2f05-11eb-83ea-44e8e0ac81a6.png)
> 
> 2.2 : Add to volume mapping in CaddyV2 : ![image](https://user-images.githubusercontent.com/63404022/100205716-c0bebe00-2f05-11eb-9399-96881b054f8c.png) ![image](https://user-images.githubusercontent.com/63404022/100205741-c9af8f80-2f05-11eb-96c3-f9f0fdda6fa4.png)
> 
> Keep the /app/ do not rename it. I've tried and this is not working.
> 
> Now CaddyV2 will have read/write access to future InvoiceNinja WebServer File.
> 
> **3 - InvoiceNinja Docker**
> 
> 3.1 Create a new template in the Docker tab here all the fields to fill **(use the advanced view)** :
> 
> name : invoiceninjaV5 ref : invoiceninja/invoiceninja dockerhub URL : https://hub.docker.com/r/invoiceninja/invoiceninja icon URL : https://raw.githubusercontent.com/hillelcoren/invoice-ninja/master/public/images/round_logo.png network type : bridge --- You have to create the variable for each in Unraid UI --- Exemple : ![image](https://user-images.githubusercontent.com/63404022/100204660-6a9d4b00-2f04-11eb-9545-ea3e9c2d16bd.png)
> 
> APP_URL: sub or domain that you will use. APP_KEY : left it empty for now. MULTI_DB_ENABLED : false DB_HOST1 : IP of the mariaDB docker. (can be localhost or the same IP as Unraid) DB_PORT1 : PORT of you MariaDB Docker (do not write you port in DB_HOST1 variable that's will not work. DB_USERNAME1 : root or whatever you choose from the previous DB steps. DB_PASSWORD1 : The DB password. DB_DATABASE1: : the name use for the database. (invoiceninja in my case)
> 
> --- You have to create the volumes mapping for each in Unraid UI --- ![image](https://user-images.githubusercontent.com/63404022/100204604-59543e80-2f04-11eb-9b8c-5db0909fe26b.png) Storage folder Docker path : /var/www/app/storage Host path : /mnt/user/appdata/invoiceninja/storage
> 
> ![image](https://user-images.githubusercontent.com/63404022/100205024-e4353900-2f04-11eb-8282-0e6870601f99.png)
> 
> Public folder (used by caddy for publish you website) Docker path : /var/www/app/public Host path : /mnt/user/appdata/invoiceninja/public
> 
> --- You have to create the port mapping in Unraid UI ---
> 
> Container Port : 9000 Host Port : 9000 or else, i've used 9191.
> 
> **3.2 Generating the App Key**
> 
> First before validate your docker config, you will add in "post argue" or "post variable" : php artisan key:generate --show (you will remove this after)
> 
> ![image](https://user-images.githubusercontent.com/63404022/100208910-89eaa700-2f09-11eb-888f-40a2de39a73f.png)
> 
> Now submit everything and start the docker.
> 
> It will stop immediatly, you just have to go the logs of the docker from the UnRaid WebUI and copy your key ;)
> 
> Now edit your Docker config, remove the post variable and fill the key field including "base64:"
> 
> You can now start your InvoiceNinja Docker everything is configured for it.
> 
> **4 : Edit CaddyFile.** Now go to your CaddyFile mapped with FTP or elses.
> 
> And add this line :
> 
> ```
> domain.com  {
>     root * /var/www/app/public/ (path that CaddyV2 will read, that the volume mapped in the previous step)
>     php_fastcgi DOCKERIP:PORT (the port used for the InvoiceNinja Docker)
>     encode zstd gzip
>     file_server browse
> }
> 
> Exemple :
> invoices.google.com {
>     root * /var/www/app/public/
>     php_fastcgi 192.168.0.10:9000
>     encode zstd gzip
>     file_server browse
> }
> ```
> 
> Reboot CaddyV2.
> 
> Access the IP used and you are on the InvoiceNinja setup !
> 
> UnRaid global screenshot ![image](https://user-images.githubusercontent.com/63404022/100207678-28760880-2f08-11eb-9b59-eb5672644a95.png)
> 
> **IN ORDER TO GET PDF WORKING :**
> 
> **php artisan storage:link** in InvoiceNinja shell.
> 
> **** DURING THE SETUP PAGE *****
> 
> **Ignore the DB configuration** just fill the others fields, the DB is already in .env so when you will validate it will configure it directly.


may i know how to run without caddy?
