### ISSUE TITLE
Timeout on setup

### ISSUE THREAD

**Issue by heavygale** [invoiceninja/dockerfiles#234]
I'm using the docker-compose setup for ninja5 with nginx as described [here](https://github.com/invoiceninja/dockerfiles/wiki/docker-compose-with-nginx#guide-for-invoice-ninja-5), using a freshly installed Debian 10 VM with Docker version 19.03.14 and docker-compose 1.21.0

When submitting the setup it's loading for a while and then just reloading the setup, according to the logs it's a timeout. I tried multiple times.

Docker Log for ninja-repo_db_1
`2020-12-05T13:14:47.917062Z 6 [Note] Aborted connection 6 to db: 'ninja' user: 'ninja' host: '172.19.0.3' (Got an error reading communication packets)`

laravel.log 
`[2020-12-05 13:14:47] production.INFO: The process "mysql  --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --database="${:LARAVEL_LOAD_DATABASE}" < "${:LARAVEL_LOAD_PATH}"" exceeded the timeout of 60 seconds.  
`

If I submit the setup again, the error `Table 'accounts' already exists` is logged in laravel.log  - so i need to remove all data to start over.

I already increased the timeout for PHP
```
fastcgi_send_timeout 600;
fastcgi_read_timeout 600;
```
What other timeouts can I increase for the setup can finish it's job?

**Comment by turbo124** [comment]
have you changed anything in the docker-compose file?

**Comment by heavygale** [comment]
For testing I've just stashed my changes and applied only the changes as described in the wiki to the docker-compose file:

-  `image: caddy:alpine` replaced by `image: nginx`
`- APP_URL=https://localhost` replaced by `- APP_URL=http://10.10.10.87`

- `- ./config/caddy/Caddyfile:/etc/caddy/Caddyfile`
replaced by:      
`- ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro`

- `- "443:443"` removed

- `- APP_KEY=<INSERT THE GENERATED APPLICATION KEY HERE>`
replaced by
`- APP_KEY=base64:NzBP66oSdW5EjctE+I4YMXcdz0T0Iir3gyRh1P9HYyw=`

I now also updates docker-compose to version 1.27.4

It's still the same result.

Output of docker log one minute after submitting the setup form:
```
server_1  | 10.10.10.56 - - [06/Dec/2020:11:01:26 +0000] "POST /setup HTTP/1.1" 302 354 "http://10.10.10.87/setup"
app_1     | 172.19.0.4 -  06/Dec/2020:11:00:15 +0000 "POST /index.php" 302
server_1  | 10.10.10.56 - - [06/Dec/2020:11:01:30 +0000] "GET /setup HTTP/1.1" 200 19564 "http://10.10.10.87/setup"
app_1     | 172.19.0.4 -  06/Dec/2020:11:01:26 +0000 "GET /index.php" 200
server_1  | 10.10.10.56 - - [06/Dec/2020:11:01:30 +0000] "GET /js/app.js?id=a33a5a58bfc6e2174841 HTTP/1.1" 200 25063 "http://10.10.10.87/setup"
server_1  | 10.10.10.56 - - [06/Dec/2020:11:01:30 +0000] "GET /js/vendor/alpinejs/alpine.js HTTP/1.1" 200 68711 "http://10.10.10.87/setup"
server_1  | 10.10.10.56 - - [06/Dec/2020:11:01:30 +0000] "GET /css/app.css?id=2fee89354bd20f89bf73 HTTP/1.1" 200 34402 "http://10.10.10.87/setup"
server_1  | 10.10.10.56 - - [06/Dec/2020:11:01:30 +0000] "GET /js/setup/setup.js HTTP/1.1" 200 19552 "http://10.10.10.87/setup"
db_1      | 2020-12-06T11:01:31.281647Z 5 [Note] Aborted connection 5 to db: 'ninja' user: 'ninja' host: '172.19.0.3' (Got an error reading communication packets)
```

Content of /var/lib/docker/volumes/ninja-repo_storage/_data/logs/laravel.log
`[2020-12-06 11:01:26] production.INFO: The process "mysql  --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --database="${:LARAVEL_LOAD_DATABASE}" < "${:LARAVEL_LOAD_PATH}"" exceeded the timeout of 60 seconds. `

**Comment by turbo124** [comment]
@heavygale  we've rewritten the dockerfiles for a cleaner setup and installation. Can you try again from a fresh setup using the quickstart in the readme.

**Comment by heavygale** [comment]
I deleted everything and started over using the quickstart guide.

I did the `sudo chown -R 1500:1500 docker/app` but when starting the stack it fails with:
`app_1     | cp: can't create directory '/var/www/app/storage/app': Permission denied`

Additionally I tested with `sudo chmod -R 777 docker` , it was then able to write files to the folders, but still failed:
`app_1     | chown: /var/www/app/public: Operation not permitted`

**Comment by turbo124** [comment]
did you do `docker-composer pull`` ?

**Comment by heavygale** [comment]
No, I missed that, good hint!
Sadly I'm now still getting a timeout when submitting the setup:
```
server_1  | 2021/01/06 21:39:43 [error] 29#29: *6 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.10.10.56, server: _, request: "POST /setup HTTP/1.1", upstream: "fastcgi://172.21.0.4:9000", host: "10.10.10.87", referrer: "http://10.10.10.87/setup"
server_1  | 10.10.10.56 - - [06/Jan/2021:21:39:43 +0000] "POST /setup HTTP/1.1" 504 167 "http://10.10.10.87/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:85.0) Gecko/20100101 Firefox/85.0" "-"
app_1     | 172.21.0.5 -  06/Jan/2021:21:38:43 +0000 "POST /index.php" 302
db_1      | 2021-01-06T21:39:51.706190Z 10 [Note] Aborted connection 10 to db: 'ninja' user: 'ninja' host: '172.21.0.4' (Got an error reading communication packets)
```
Or with the increased PHP timeout in nginx conf:
```
server_1  | 10.10.10.56 - - [06/Jan/2021:21:53:47 +0000] "POST /setup HTTP/1.1" 302 354 "http://10.10.10.87/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:85.0) Gecko/20100101 Firefox/85.0" "-"
app_1     | 172.21.0.5 -  06/Jan/2021:21:52:43 +0000 "POST /index.php" 302
db_1      | 2021-01-06T21:53:48.239600Z 8 [Note] Aborted connection 8 to db: 'ninja' user: 'ninja' host: '172.21.0.4' (Got an error reading communication packets)
```
While the setup is beeing processed I can hear the HDDs working in my NAS, but it seems to be to slow to finish in time.
I'll test the setup on a faster server tomorrow, maybe I can copy the finished setup to the slower NAS afterwards.

**Comment by turbo124** [comment]
Quite possibly your CPU isn't able to complete the migration within the timeout length.

**Comment by heavygale** [comment]
Alright, setting it up in a VM and copying it the files over afterwards worked.
The NAS has a Atom C2538 (4x2.4GHz) and a RAID 5,... tought that should be enough. ^^
