### ISSUE TITLE
PDOException  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ninja.accounts' doesn't exist

### ISSUE THREAD

**Issue by cccaballero** [invoiceninja/dockerfiles#235]
I am following the "Docker Compose with nginx" quick start from the wiki, and I am getting a 500 error with no extra error info in the docker logs. If I activate the laravel debugging I get the following error:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ninja.accounts' doesn't exist (SQL: select * from `accounts` limit 1)
```

**Comment by cccaballero** [comment]
Solved, I had to run migrations with `docker-compose exec app php artisan migrate`. Maybe include this in docs for newbies like me?

**Comment by hillelcoren** [comment]
Glad to hear it's working, thanks for sharing the fix!
