### ISSUE TITLE
Updated Docker installation of Invoice Ninja from 5.0.34 to 5.0.36 error "chown: [Files]: Operation not permitted"

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/dockerfiles#236]
I just updated from 5.0.34 to 5.0.36. On startup i now get a bunch of "chown: [Files]: Operation not permitted" errors. See below for full list. 

I just pulled the latest Image and restartet the Docker Containers with the new Image. Should i execute any other steps bevor restarting with the new Image? 

```
chown: /var/www/app/storage/framework/cache/data/10: Operation not permitted 
chown: /var/www/app/storage/framework/views/e645e7ceb08119ca36514c8a4af7bfa55625137c.php: Operation not permitted 
chown: /var/www/app/storage/framework/views/6e1c8e914e2052a62c641a7d9535b73c089c362d.php: Operation not permitted 
chown: /var/www/app/public/.@__thumb/s800favicon.png: Operation not permitted 
chown: /var/www/app/public/.@__thumb/defaultfavicon.png: Operation not permitted 
chown: /var/www/app/public/.@__thumb/s100favicon.png: Operation not permitted 
chown: /var/www/app/public/.@__thumb: Operation not permitted 
chown: /var/www/app/public/.@__thumb: Operation not permitted 
chown: /var/www/app/storage/framework/cache/data/10/3a/103ac2ab087b4da49d891e2d1823f45a275bd23d: Operation not permitted 
chown: /var/www/app/storage/framework/cache/data/10/3a: Operation not permitted 
chown: /var/www/app/storage/framework/cache/data/10/3a: Operation not permitted 
chown: /var/www/app/storage/framework/cache/data/10: Operation not permitted 
chown: /var/www/app/storage/framework/cache/data/10: Operation not permitted 
chown: /var/www/app/storage/framework/views/e645e7ceb08119ca36514c8a4af7bfa55625137c.php: Operation not permitted 
chown: /var/www/app/storage/framework/views/6e1c8e914e2052a62c641a7d9535b73c089c362d.php: Operation not permitted 
chown: /var/www/app/public/.@__thumb/s800favicon.png: Operation not permitted 
chown: /var/www/app/public/.@__thumb/defaultfavicon.png: Operation not permitted 
chown: /var/www/app/public/.@__thumb/s100favicon.png: Operation not permitted 
chown: /var/www/app/public/.@__thumb: Operation not permitted 
chown: /var/www/app/public/.@__thumb: Operation not permitted 
chown: /var/www/app/storage/framework/cache/data/10/3a/103ac2ab087b4da49d891e2d1823f45a275bd23d: Operation not permitted 
chown: /var/www/app/storage/framework/cache/data/10/3a: Operation not permitted 
chown: /var/www/app/storage/framework/cache/data/10/3a: Operation not permitted 
chown: /var/www/app/storage/framework/cache/data/10: Operation not permitted 
chown: /var/www/app/storage/framework/cache/data/10: Operation not permitted 
chown: /var/www/app/storage/framework/views/e645e7ceb08119ca36514c8a4af7bfa55625137c.php: Operation not permitted 
chown: /var/www/app/storage/framework/views/6e1c8e914e2052a62c641a7d9535b73c089c362d.php: Operation not permitted 
chown: /var/www/app/public/.@__thumb/s800favicon.png: Operation not permitted 
chown: /var/www/app/public/.@__thumb/defaultfavicon.png: Operation not permitted 
chown: /var/www/app/public/.@__thumb/s100favicon.png: Operation not permitted 
chown: /var/www/app/public/.@__thumb: Operation not permitted 
chown: /var/www/app/public/.@__thumb: Operation not permitted
```

**Comment by Akjo4712** [comment]
Managed to get it working again. I just deleted the storage and public docker Volume. It was recreated on restart. Everythings is up and working again. 

Does deleting the Storage and Public Folder have any unwanted side effects? Like losing any Data?
```
      - public:/var/www/app/public
      - storage:/var/www/app/storage
```

**Comment by hillelcoren** [comment]
Thanks for sharing the solution!

Most data is stored in the database, deleting those folders would delete the company logos and any uploaded documents.

**Comment by turbo124** [comment]
@Akjo4712 can you confirm the ownership of -public and -storage - these would need to be writable by the runtime docker user

**Comment by Akjo4712** [comment]
I just updated from 5.0.36 to 5.0.39 with the same procedure and i didn't expirence the problems stated above. I can't tell you the Ownerships before i made the update.
As the Problem didn't occure while updating from 5.0.36 to 5.0.39 it doesn't seem that relevant any more to me. Tell me if you need more details from me.

**Comment by turbo124** [comment]
@Akjo4712  we've rewritten the dockerfiles for a cleaner setup and installation. Can you try again from a fresh setup using the quickstart in the readme.

**Comment by Akjo4712** [comment]
Just made a fresh setup. No issue with Permissions for now. Will comment if the Problem appears during a update in the future.

**Comment by Akjo4712** [comment]
@turbo124 I just had this kind of Issue again and i was able to debug the problem. Problem is not related to Invoice Ninja, but changing the Docker Startup Script might fix this Problem and make it more fault tolerant.

I am running Docker on a QNAP NAS. QNAP auto generates Thumbnails for Pictures in a hidden Folder `.@__thumb`. This Folder causes Errors when Invoice Ninja executes the CHOWN on all Files in it's Folders.

Might change the Script to proceed Startup, even if the CHOWN command fails? For me it is okay to leave it like that. Deleting the Thumbnails bevor Startup is easy.

**Comment by turbo124** [comment]
@Akjo4712 thanks for letting us know!
