### ISSUE TITLE
Proper tagging on Docker Hub

### ISSUE THREAD

**Issue by cinemast** [invoiceninja/dockerfiles#24]
Hi!

Thanks for providing this docker image. However I would wish for a proper version tagging on docker hub. Currently all releases end-up in latest. Could you please create a tag for each release? It was the case for versions before 2.5.1.2

https://hub.docker.com/r/invoiceninja/invoiceninja/tags/

**Comment by lalop** [comment]
Since the invoiceninja's maintainers work only on the next release and don't maintain olders one I don't see a good reason to tag the docker image.
How this can help you ?

**Comment by cinemast** [comment]
It allows each individual to decide when it wants to update the invoice ninja app in a reproducible way. Currently it depends on the date/time of pulling which version will be received.

Please tag them on each release. Latest will always be there anyway for rolling release. I don't expect any updates on old releases of course, just that I am able to decide which version of invoice ninja I will receive.

**Comment by lalop** [comment]
The point is that, the image is automatically builed, I have to rework all this repos to tag all version.
I will try to take some time to do this next month

**Comment by lalop** [comment]
they are coming https://hub.docker.com/r/invoiceninja/invoiceninja/tags/

**Comment by cinemast** [comment]
Thank you!
