### ISSUE TITLE
Email not working after install

### ISSUE THREAD

**Issue by cccaballero** [invoiceninja/dockerfiles#240]
Hi, I have just installed invoiceninja5 using the dockerfiles, and in the invoiceninja setup, when testing email everything works fine, but after install, sending emails starts to throw errors. I think that for some reason my email settings were not applied and I can't find how can I check and update the email settings.

**Comment by turbo124** [comment]
@cccaballero are you able to add your mail config variables into your docker-compose.yml file and then down / up the container.

**Comment by cccaballero** [comment]
@turbo124 Yes, is working fine after setting the environment variables. Thanks!!
