### ISSUE TITLE
v5 install of invoice ninja with provided docker-compose cannot generate pdfs

### ISSUE THREAD

**Issue by adamrees89** [invoiceninja/dockerfiles#245]
I've installed invoice ninja using the docker-compose instructions provided in this git repo. I'm using the nginx option instead of caddy as I want my install to be accessible from my private network only (vpn for remote access).

I have everything working great except for the pdf creating, I've got test invoices and quotes and I get a 404 error when clicking view invoice.

I've been through a few of the instructions in the closed issues but nothing has fixed my issue.

Any ideas?

**Comment by Condolas** [comment]
Just had this issue, setting my $APP_URL to **https://mydomain.com/** (the last backslash is important) and restarting the container and re-running the php artisan optimize command fixed it.

**Comment by adamrees89** [comment]
> Just had this issue, setting my $APP_URL to **https://mydomain.com/** (the last backslash is important) and restarting the container and re-running the php artisan optimize command fixed it.

Hi Condolas,

I did this, and just for anyone else reading this, I used my internal IP but with http:// and the trailing slash.

I still cannot view PDFs but I no longer have the 404 error, but now I have a 500 error.

Any ideas?

**Comment by Condolas** [comment]
I just started having the 500 errors as well. Did a fresh install to test as well and I can't seem to get past the 500 error when viewing invoices.

**Comment by turbo124** [comment]
@Condolas we've rewritten the dockerfiles for a cleaner setup and installation. Can you try again from a fresh setup using the quickstart in the readme.

**Comment by Condolas** [comment]
@turbo124 it works! Had to do some manual tweaking, but pdfs are generating far more smoothly now. Thanks!

**Comment by turbo124** [comment]
@Condolas great!!

Can you please let me know what tweaks you needed to add? I want to make this bullet proof :)

**Comment by Condolas** [comment]
@turbo124 Yes, I had to perform the following:

- run **sudo chown -R 1000:82 storage/app** (This fixed a permissions issue)
- run **php artisan migrate:fresh** (The web page initially will load and not redirect to /setup. Instead it would show a SQL error about a table not being found, I think it was the ninja.accounts table.)
- Added **TRUSTED_PROXIES='10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'** (I run IN behind a traefik proxy, needed this to passthrough correctly)
- had to use HTTPS in the APP_URL variable. HTTP would cause issues with chrome, something about serving HTTPS content over an insecure HTTP call.
- Not sure if this is an issue, however I commented out the db port numbers in the docker-compose file. I think it may be a typo as it is set to 3305:3306. Regardless the app works great without the port numbers defined.

**Comment by adamrees89** [comment]
I've uploaded my redacted docker-compose file to gist which I used successfully in the end. I'm using the nginx proxy instead of the default.

https://gist.github.com/adamrees89/90cc83f97b836311ce03c3653315e01f

I fixed my 500 error as I hadn't set up docker to run as a non-root user, changed the docker config and groups settings and it just worked.
