### ISSUE TITLE
Company logos not shown in invoices or invoice designer

### ISSUE THREAD

**Issue by gtothill** [invoiceninja/dockerfiles#254]
I am aware that a very similar issue has been raised previously but I hope that you will forgive me for opening it again. I'm not entirely sure from reading the post [here ](https://forum.invoiceninja.com/t/company-logo-not-display-within-invoice/5218)what the underlying cause was.  Although the OP's name is the same as mine in that post that is coincidental!

Here are the steps that I took:

1) I followed the standard quick start and installed invoice ninja v5.0.44-C37 on my docker instance. Used the directory structure provided by the git clone as the mounted directories without changing anything.  For testing used the provided mysql variables. Used the suggested port allocations - which also deconflicted port 80 on the docker host. Did not use a reverse proxy.

2) Set ownership of mounted directories as chown -R 1500:1500 docker/app

3) Ran docker-compose exec php artisan storage:link against the container. Told me the link already existed (and then that it had been created!).

4) Did /setup on first run. All checks including pdf generation worked properly.

5) On first login system seems to work as expected except in regards to the company logo appearing on the invoices - tested in the design section of settings.

6) Uploaded a logo to the default company. It appears saved.

7) Went to the invoice design for the company and viewed the pdf preview. Uploaded logo was not shown.

8) Error below shown in logs:

app_1     | 172.18.0.16 -  06/Jan/2021:15:54:07 +0000 "GET /index.php" 200
server_1  | 192.168.124.19 - - [06/Jan/2021:15:54:08 +0000] "POST /api/v1/refresh?updated_at=1609946440&first_load=true HTTP/1.1" 200 77237 "http://invoice.mydomain.local:8003/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66" "-"
app_1     | 172.18.0.16 -  06/Jan/2021:15:54:08 +0000 "POST /index.php" 200
server_1  | 192.168.124.19 - - [06/Jan/2021:15:54:08 +0000] "GET /storage/pjTfoYG1LyoQdBCf7Yaf91YJMidNaUiIXy2Hyss5Muw2owlFxdDAKmngj1gBsfVl/2Q59XUOCBxgvDkc0zGkF36trQeBfefEEfc9sqLMF.png HTTP/1.1" 304 0 "http://invoice.digitalrivet.local:8003/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66" "-"
app_1     | [06-Jan-2021 15:54:15] ALERT: oops, unknown child (383) exited with code 0. Please open a bug report (https://bugs.php.net).
app_1     | [06-Jan-2021 15:54:15] ALERT: oops, unknown child (404) exited with code 0. Please open a bug report (https://bugs.php.net).
app_1     | [06-Jan-2021 15:54:15] ALERT: oops, unknown child (382) exited with code 0. Please open a bug report (https://bugs.php.net).
server_1  | 192.168.124.19 - - [06/Jan/2021:15:54:15 +0000] "POST /api/v1/preview? HTTP/1.1" 200 20961 "http://invoice.mydomain.local:8003/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66" "-"
 

9) If I try and access that file directly then it downloads fine.  I can also see that it is present in the /public/storage directory and has the right ownership.

This is what I get in the logs if I specify the url directly - which displays the file.

server_1  | 192.168.124.19 - - [06/Jan/2021:15:58:35 +0000] "GET /storage/pjTfoYG1LyoQdBCf7Yaf91YJMidNaUiIXy2Hyss5Muw2owlFxdDAKmngj1gBsfVl/2Q59XUOCBxgvDkc0zGkF36trQeBfefEEfc9sqLMF.png HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66" "-"
 

Can anyone give me a suggestion as to how I might further debug this? 

Kind regards,

Geoff.

**Comment by turbo124** [comment]
this looks like a DNS resolution issue. chrome will not resolve any local domains unless they have a domain ending in ```.test```

**Comment by gtothill** [comment]
Thanks turbo124.
I'm probably being a bit dense here but I'm assuming that you mean that the Chrome browser wont resolve local domains unless they are .test?
If so it may be that this limitation has been lifted - all our internal services are hosted on a .local domain and all resolve fine against a local bind server on our internal network.
Doing a ipconfig /flushdns and a chrome browser cache clearance on win 10 followed by manually entering a url causes the domain to be resolved - or is this only a problem at a script level?
All other functions of invoice ninja work fine on the .local domain.
Sorry if Im way off with this and thank for your help,
All the best
Geoff.

**Comment by turbo124** [comment]
We use Chrome to generate the PDFs, and it is the chromium binary itself which refuses to do the internal lookup unless the domain is .test

**Comment by gtothill** [comment]
Super - thanks - explanation much appreciated. Will bump our internal server to a .test domain. Thanks to the team for all the support and dev work on this.
