### ISSUE TITLE
Enhancement: rename "env" to ".env"

### ISSUE THREAD

**Issue by Condolas** [invoiceninja/dockerfiles#259]
Just a suggestion that may make the docker-compose.yml a bit cleaner, rename the "env" file to ".env" and remove all instances of the "env_file:" from the docker-compose.yml file. 

According to https://docs.docker.com/compose/env-file/ :
_Compose supports declaring default environment variables in an environment file named .env placed in the folder where the docker-compose command is executed (current working directory)._

This would also alleviate the need to specify env_file: path in containers added in the future.

**Comment by turbo124** [comment]
Thanks for the suggestion, the downside with using ```.env``` is some people don't know this is a hidden file and not directly visible.

We'll keep it in mind nevertheless.

**Comment by turbo124** [comment]
I'm going to close this for now, we can revisit this later if needed.

**Comment by ovizii** [comment]
I would think it would be nice to have some sort of explanations of the difference between the env file and the .env file which is being used inside the container - i.e. which variables to declare in which file. 
i.e. I declared all the DB conenction and email settings variables in the env file but when I ran the setup I was aked about all of them again so what was the point of declaring them inside the env file? And after the setup I see that /var/www/app/.env is still filled with default values.

**Comment by turbo124** [comment]
@ovizii 

The app isn't aware it is in a container, so you are correct, the setup screen for the DB section is redundant for a docker container. 

the docker env is the overriding environment file, all of your env variables should be in this file and it will be preferences over the containers .env file.
