### ISSUE TITLE
Question: why add cap SYS_ADMIN?

### ISSUE THREAD

**Issue by snaptowen** [invoiceninja/dockerfiles#261]
I can't think of any particular reason to require effective root access here - for the sake of sanity I'm assuming there's good reason, but so far I've had no issues running without. Anyone aware of why this is recommended/required?

**Comment by lwj5** [comment]
Good catch. It’s probably for chromium.

The commit history shows it was added with puppeteer so it checks out.

@turbo124 has moved IN it to snappdf which runs no sandbox https://github.com/beganovich/snappdf/blob/master/src/Snappdf.php so all good to remove

**Comment by turbo124** [comment]
Thanks @lwj5 @snaptowen 

I've updated the docker-compose.yml file

#263
