### ISSUE TITLE
Migrations are run on both Cron and App Container

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/dockerfiles#264]
When i update to a new Version, i can see, that both the cron and the app container are running migrations. This sometimes conflicts and i think this could lead to unexpected results, when both containers do the same migration.

# Logs
![image](https://user-images.githubusercontent.com/65533611/105039598-09f04180-5a61-11eb-8faa-7fa8a347f7dc.png)

# Setup information
docker-compose

**Comment by turbo124** [comment]
@Akjo4712 yes, i don't like the look of that. I think the correct approach here is to run the scheduler in the app container and remove the cron container... i'll add this to my backlog.

**Comment by turbo124** [comment]
#270 fixes this.

**Comment by Akjo4712** [comment]
Already upgraded to the new Version. Feels much better now. Thanks alot!
