### ISSUE TITLE
Upgrading from Docker tag 5.0.40 to latest wipes all data

### ISSUE THREAD

**Issue by adamrees89** [invoiceninja/dockerfiles#269]
I am using docker-compose and Nginx.

I was running on docker tag 5.0.40, and upgraded to latest. This wiped all my information within the system, including customisations for invoicing.

**Comment by turbo124** [comment]
Do you have a persistent volume for your DB?

Did you have to redo the setup?

**Comment by turbo124** [comment]
@adamrees89 I wasn't able to recreate this, i did serial upgrades and my data persisted fine. I'm not sure what to put this down.

**Comment by adamrees89** [comment]
@turbo124, ok,

So I've got backups of my volumes and a mysqldump file. Restoring the backups seems to have no affect on the updated version as discussed above.

I'm using the procedures for backup and restoring of volumes as in the link below:

https://github.com/loomchild/volume-backup

My docker-compose and env file are at the zip file attached if required.
[docker-compose.zip](https://github.com/invoiceninja/dockerfiles/files/5922170/docker-compose.zip)

**Comment by adamrees89** [comment]
@turbo124, also I'm more than happy to document a working backup and restore procedure for the wiki on here if that helps lower the amount of questioning both here and on the forum.

One I get a manual backup procedure working I'm planning on writing a backup script (python or bash) to automate, I'm more than happy to open source it to reduce maintenance headaches.

**Comment by turbo124** [comment]
@adamrees89 i'm not sure what has happened to your environment, especially if your backups also aren't restoring you back to a known working copy.

**Comment by adamrees89** [comment]
@turbo124 would you mind casting your eye over the docker-compose and env files in case there's something I've missed?

**Comment by turbo124** [comment]
@adamrees89 it looks pretty much identical to the one in the repo here. The only thing I would suggest, is to follow the guide in the readme, and ensure your directory permissions are exactly the same as that could cause issues with the volumes.

**Comment by adamrees89** [comment]
@turbo124 will do.

**Comment by adamrees89** [comment]
@turbo124 so I'm an idiot.

When I first set it up, I was using volumes, I didn't notice that the standard docker-compose file uses bind-mounts.

Backup all working, update successful.

**Comment by turbo124** [comment]
@adamrees89 thanks for the update, good to hear it is sorted :)
