### ISSUE TITLE
Confused about LAN IP on local install

### ISSUE THREAD

**Issue by Natetronn** [invoiceninja/dockerfiles#285]
I'm a little bit confused about how local setup works in regards to the LAN IP described in the readme note here:

https://github.com/invoiceninja/dockerfiles#note-for-people-running-the-container-locally-on-their-pc

A few question, if I may:

1. Can I change `CNAME=in.localhost` in .env? e.g. to `CNAME=invoiceninja.test`
2. In `config/hosts` do I then put `invoiceninja.test` instead of `in5.test`?
3. Also in `config/hosts` do I then put my own local IP before the cname (now invoiceninja.test)? e.g. the IP address I get from running `ifconfig` or similar command?
4. Finally, in `docker-compose.yml` do I then need to change the three instances of  `- "${CNAME}:192.168.0.124 " #host and ip` to said IP from number 3 above? e.g. `- "${CNAME}:192.168.1.xxx " #host and ip` (where xxx is my local lan ip)

I've tried this without success and why I'm confused. 

Note: if I change nothing at all it works, minus in5.test and why I'm confused by the note. If I make the above changes nothing works, which is odd to me.

**Comment by turbo124** [comment]
@Natetronn This is due to the latest commit breaking some thing. I have reverted the last PR, if you can update the repo, it will be much simpler to follow

**Comment by Natetronn** [comment]
Ah, okay! Thanks @turbo124.
