### ISSUE TITLE
Css & JS won't load after updating to 4.5.32

### ISSUE THREAD

**Issue by danielgroen** [invoiceninja/dockerfiles#287]
Hi,

When i updated to 4.5.32 my css didn't load anymore.

I am running on Traefik as edge router. This means that Traefik does the routing to https.
Invoiceninja only serves on port 80.

I think there is where it goes wrong. That Invoiceninja thinks that it's on port 80 but meanwhile traefik changes it to https.
Is it possible to use relative paths for the following files:
![image](https://user-images.githubusercontent.com/6578052/107846637-8cacb800-6de5-11eb-9e5c-b2c2466a8e2a.png)

**Comment by turbo124** [comment]
you may need to change your APP_URL to https://

**Comment by danielgroen** [comment]
Unfortunately app_url has been set to https

**Comment by turbo124** [comment]
You may want to look at this section of configuring a laravel application with a trusted proxy

https://laravel.com/docs/8.x/requests#configuring-trusted-proxies

**Comment by danielgroen** [comment]
This seems indeed the problem.
However according to this [article](https://julien-aupart.medium.com/laravel-and-cors-behind-a-reverse-proxy-b737566bdd96)
The trick should be by adding a file 'trustedproxy.php to the config folder.

Can this be added into invoiceninja?

**Comment by turbo124** [comment]
@danielgroen I'll add this into the next release :)

**Comment by danielgroen** [comment]
Thanks a lot @turbo124! if you also would implement it for v5, since i also ran into the same problem there. Thanks man!

**Comment by turbo124** [comment]
@danielgroen i've only implement this for V5, we have a change freeze on V4.

**Comment by danielgroen** [comment]
allright,
is there any news on a stable release for v5?
My v4 looks now like this, undoable to do administration ofc :p
![image](https://user-images.githubusercontent.com/6578052/107936313-c8c94f80-6f82-11eb-868f-6fd1ae3ca77e.png)

**Comment by zurajm** [comment]
Hi @danielgroen, I've struggled with the same issue, fix is really simple and can be found here:
https://github.com/invoiceninja/dockerfiles/issues/14#issuecomment-241860289

All you need to do is to add a line to nginx config file.

Regards, Miha

**Comment by ovizii** [comment]
Thanks everyone. I also had the issue of failing CSS because of mixed content when updating from 4.5.30 to 4.5.35 - luckily I was able to complete the migration to v5 even with the mixed content problem :-)
