### ISSUE TITLE
Access rights on public directory 404ing everything in nginx docker container

### ISSUE THREAD

**Issue by orion78fr** [invoiceninja/dockerfiles#290]
First, I'm going to say I **did** run `sudo chown -R 1500:1500 docker/app` to let the invoiceninja (app) container create the appropriate files in the public directory, this is not the issue.

However, the nginx (server) container had trouble loading many files.
The strange thing is that if I manually added `/index.php` to the URL, the setup page did load, but without any CSS or JS.

I had a hard time narrowing the issue, but I found that the nginx container did not have read access to the docker/app/public folder (both the group and user id are different than the invoiceninja container) but the rights for the files inside were correct.
To fix it, I had to `sudo chmod o+rx docker/app/public`.
This may be linked to the fact that my `umask` is `0077` and it did not set the `o+rx` rights while cloning the git repository.

Maybe you should add the chmod to the readme too ?

# Setup information

What version do you run? 7f41580
Do you run docker-compose or a single Dockerfile ? `docker-compose -d up`

**Comment by turbo124** [comment]
This sounds like several issues rather than one, are you running a modified or unmodified version of our dockerfile?

**Comment by orion78fr** [comment]
Everything was solved by a `chmod o+rx` to the docker/app/public folder. Again, this is probably due to my (rather restrictive) umask.

Only thing I changed in the docker-compose.yml are the passwords and port of the nginx server (I already had a non dockerized nginx without php and I used it to proxy-pass).

**Comment by turbo124** [comment]
Ok, i think we can close this and put it down to the umask.
