### ISSUE TITLE
Publish Invoice Ninja 4.5.34 to Docker Hub

### ISSUE THREAD

**Issue by andrewhaji** [invoiceninja/dockerfiles#294]
Hi all,

Thanks for your continued development of this software. Please forgive me if this isn't the right place to be posting this.

I am currently running Invoice Ninja 4.5.32 using your official Docker image. I would like to upgrade to 4.5.34 so that I can eventually migrate to 5.x, but 4.5.34 hasn't been published to Docker Hub. Is this something that can be done?

Thanks,
Andrew

**Comment by turbo124** [comment]
Sorry, this was my mistake, i've started a build for this, it should be available shortly.

**Comment by andrewhaji** [comment]
Thank you! Much appreciated.

Do you expect that 4.5.34 will be the last release of IN4? Is the migration process as good as it's going to get?

Thanks,
Andrew
