### ISSUE TITLE
[Question] Still need cron container in v5?

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/dockerfiles#296]
I'm trying to upgrade from v4 to v5.

In v4 there was a dedicated ["cron" container](https://github.com/invoiceninja/dockerfiles/blob/4.5.17/docker-compose/docker-compose.yml#L54).

In the v5 examples that no longer exists. However [the docs](https://invoice-ninja.readthedocs.io/en/latest/configure.html#recurring-invoices-and-reminder-emails) still mention the need for this.

Should I still be using a cron container in v5, or are the docs outdated?

**Comment by turbo124** [comment]
@lonix1 

For V5, initially we had a separate container for the cron, then we integrated the crons into one of the existing containers, so for V5 it is no longer requred. 

V5 docs are new and are located here https://invoiceninja.github.io

Are you rebuilding your own dockerfile? or using the provided one in this repo? The repo one is plug and play with V5 :)

**Comment by lonix1** [comment]
No I'm using the compose file in this repo, but I got confused by the (old) docs which told me to use a cron container.

Thanks for the link to the v5 docs, it makes much more sense now! :+1:
