### ISSUE TITLE
Problem with generating invoices

### ISSUE THREAD

**Issue by lbadell** [invoiceninja/dockerfiles#297]
Hello, i am self-hosting IN using docker and i when i generate a invoice it generates corrupted pdfs.

This are the steps that i took
Cloned the repo,
Generate a APP_KEY and edit the env file with APP_URL= http://in5.test/ and added the APP_KEY
Changed the config/hosts to <my-ip> in5.test
This isn´t on the readme, but in the docker-compose.yml there are some lines with
"in5.localhost:192.168.0.124 " #host and ip
I changed them to in5.test:<my-local-ip>
Another thing is that i added 127.0.0.1 in5.test to my /etc/hosts file
Run the chown command and docker-compose up -d

I go to in5.test and i get some errors about ninja.accounts but i can acess /setup and follow the setup without any problems 
I can enter the web-interface, generate a dummy company and a dummy invoice but when i want to view the pdf, firefox cannot open it, its seems that generate corrupted pdfs files or something. I am attaching the pdf 
[1.pdf](https://github.com/invoiceninja/dockerfiles/files/6165775/1.pdf)

I not know what are the relevant logs to view to see what is happening.
Thanks you in advance.

**Comment by turbo124** [comment]
@lbadell 

could you please set the following in your env file

PHANTOMJS_PDF_GENERATION=false

and then restart the containers... this should resolve the issue.

**Comment by lbadell** [comment]
Yes, it did resolve the issue.
Thank you.
