### ISSUE TITLE
chown not permitted

### ISSUE THREAD

**Issue by Aron2560** [invoiceninja/dockerfiles#303]
Running docker on Windows (wsl) ubuntu. 
Getting the following error.

chown: /var/www/app/storage: Operation not permitted
chown: /var/www/app/storage: Operation not permitted

I added sudo before the chown command but no luck.
I also tried sudo umount /mnt/c && sudo mount -t drvfs C: /mnt/c -o metadata to no luck.

What else can I try?

**Comment by turbo124** [comment]
https://docs.docker.com/docker-for-windows/troubleshoot/#permissions-errors-on-data-directories-for-shared-volumes

According to this, you should not have to worry about permissions when running on docker

**Comment by Aron2560** [comment]
I see. But I still have this issue. What can I try?
See attached screenshot of the error log. It keeps restarting app_1 

![image](https://user-images.githubusercontent.com/11949102/112252494-9242bc80-8c33-11eb-9e45-5d0de08735f1.png)

**Comment by turbo124** [comment]
What happens if you comment out the following in the entrypoint.sh file

```bash
if [[ ${str::1} -le 4 ]]; then 
    chown -R "$INVOICENINJA_USER":www-data /var/www/app/storage /var/www/app/public /var/www/app/bootstrap
fi
```

**Comment by lwj5** [comment]
@turbo124 the build .31 is before I added the if statement, maybe that’s why. I see an error with the if statement, don’t but a new image yet

**Comment by lwj5** [comment]
@turbo124 the build .31 is created before I added the _if_ statement, so it shouldn't be that problem.

There's no issue when running build .31 on docker on mac.

I don't have a Windows PC to test, @Aron2560 could you rebuild the dockerfile from the master branch to see if the _if_ statement help?

**Comment by lwj5** [comment]
I cannot reproduce this on Debian WSL2 

![image](https://user-images.githubusercontent.com/16207788/112355451-9db3e780-8d08-11eb-941b-53fa51ef71c1.png)

app started and working correctly
