### ISSUE TITLE
[Bug] v5.1.32 does not start

### ISSUE THREAD

**Issue by lonix1** [invoiceninja/dockerfiles#308]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
app 5.1.32
docker 20.10.5
docker-compose 1.28.5

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/) Please provide redacted output**
see below

**Have you searched existing issues?**
yes

**Have you reported this to Slack/forum before posting?**
no

**Describe the bug**
see below

**Steps To Reproduce**
start stack (docker compose up)

**Additional context**
Starting a **fresh** stack from scratch gives this in the invoiceninja container:

> Configuration cache cleared!
> Configuration cached successfully!
> Configuration cache cleared!
> Configuration cached successfully!
> Route cache cleared!
> Routes cached successfully!
> les cached successfully!
> Unknown suffix '-' used for variable 'port' (value '--silent')
> mysqladmin: Error while setting value '--silent' to 'port'
> Waiting for DB (mariadb:)
> Unknown suffix '-' used for variable 'port' (value '--silent')
> mysqladmin: Error while setting value '--silent' to 'port'
> Waiting for DB (mariadb:)
> Unknown suffix '-' used for variable 'port' (value '--silent')
> mysqladmin: Error while setting value '--silent' to 'port'
> Waiting for DB (mariadb:)
> Unknown suffix '-' used for variable 'port' (value '--silent')
> mysqladmin: Error while setting value '--silent' to 'port'
> Waiting for DB (mariadb:)
> Unknown suffix '-' used for variable 'port' (value '--silent')
> mysqladmin: Error while setting value '--silent' to 'port'
> Waiting for DB (mariadb:)
> Unknown suffix '-' used for variable 'port' (value '--silent')
> mysqladmin: Error while setting value '--silent' to 'port'
> Waiting for DB (mariadb:)
> Unknown suffix '-' used for variable 'port' (value '--silent')
> mysqladmin: Error while setting value '--silent' to 'port'
> Waiting for DB (mariadb:)
> Unknown suffix '-' used for variable 'port' (value '--silent')
> mysqladmin: Error while setting value '--silent' to 'port'
> Waiting for DB (mariadb:)

Notes
- all I did was change the version from 5.1.31 to 5.1.32
- **previous version works with the exact same config** - and when I rollback it works
- database is working fine, that's not the problem
- I don't think this is a docker related problem

**Comment by turbo124** [comment]
The issue is here:

```
while ! mysqladmin ping -h "$DB_HOST1" -P $DB_PORT1 --silent; do
    echo "Waiting for DB ($DB_HOST1:$DB_PORT1)"
    sleep 1
done
```

As an interim, you'll need to set the DB_PORT1 variable in your env file. Can you confirm this is configured?

@lwj5 seems introduced here c0350de41866ac9e4cae4b3da4790848492c708e

**Comment by kevinjaygonz** [comment]
Yeah I'm having the same issue. Seems like turbo has already figured it out but is there a work around for the time being while they are working on the issue.

**Comment by turbo124** [comment]
@kevinjaygonz 

In the entrypoint.sh file comment out the lines

```
while ! mysqladmin ping -h "$DB_HOST1" -P $DB_PORT1 --silent; do
    echo "Waiting for DB ($DB_HOST1:$DB_PORT1)"
    sleep 1
done
```

**Comment by tecnomur** [comment]
> @kevinjaygonz
> 
> In the entrypoint.sh file comment out the lines
> 
> ```
> while ! mysqladmin ping -h "$DB_HOST1" -P $DB_PORT1 --silent; do
>     echo "Waiting for DB ($DB_HOST1:$DB_PORT1)"
>     sleep 1
> done
> ```

Still not working😔

**Comment by turbo124** [comment]
same error?

**Comment by tecnomur** [comment]
Yes David, same error.

**Comment by turbo124** [comment]
is your DB_PORT1 defined in the docker-compose.yml or your env file?

**Comment by lwj5** [comment]
I’ll update the entry point to only fix this issue.

**Comment by kevinjaygonz** [comment]
I'm not sure if this bit of information will helps but this error happens when I'm trying to generate the APP_KEY using the following command. I didn't see anyone else saying that they just said it's not running.
`docker run --rm -it invoiceninja/invoiceninja php artisan key:generate --show`

**Comment by lwj5** [comment]
I've updated the 5.1.32 image. You will need to delete the old images with TAG `5`, `5.1.32`, and `latest` from your computer before you can resolve the issue.

To do this you can delete the images from the Docker Dashboard or through the command line.

To delete these images on the command line run:
```bash
docker image rm invoiceninja/invoiceninja:latest --force
docker image rm invoiceninja/invoiceninja:5 --force
docker image rm invoiceninja/invoiceninja:5.1.32 --force
```

If you receive `Error: No such image:`, you can ignore it.

Now you can try doing the things you were trying to do before.

**Please also read https://github.com/invoiceninja/dockerfiles#updating-the-image-when-using-docker-compose when updating image versions when using docker-compose**

**Comment by lonix1** [comment]
IN container doesn't start, logs show:
> Error: could not find config file /supervisord.conf
> For help, use /usr/bin/supervisord -h

**Comment by lwj5** [comment]
@lonix1 please create a new issue.

**Comment by lonix1** [comment]
It's related to the same problem - 5.1.32 now shows that, it still doesn't start.

**Comment by lwj5** [comment]
No such issue.

try
```bash
docker-compose up --force-recreate
```

```
Creating network "dockerfiles_invoiceninja" with the default driver
Creating dockerfiles_db_1 ... done
Creating dockerfiles_app_1 ... done
Creating dockerfiles_server_1 ... done
Attaching to dockerfiles_db_1, dockerfiles_app_1, dockerfiles_server_1
app_1     | Initialising Laravel...
app_1     | Configuration cache cleared!
app_1     | Configuration cached successfully!
app_1     | Configuration cache cleared!
app_1     | Configuration cached successfully!
app_1     | Route cache cleared!
app_1     | Routes cached successfully!
app_1     | Files cached successfully!
app_1     | 
app_1     | In Connection.php line 678:
app_1     |                                                                                
app_1     |   SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_s  
app_1     |   chema.tables where table_schema = ninja and table_name = accounts and table  
app_1     |   _type = 'BASE TABLE')                                                        
app_1     |                                                                                
app_1     | 
app_1     | In Exception.php line 18:
app_1     |                                              
app_1     |   SQLSTATE[HY000] [2002] Connection refused  
app_1     |                                              
app_1     | 
app_1     | In PDOConnection.php line 38:
app_1     |                                              
app_1     |   SQLSTATE[HY000] [2002] Connection refused  
app_1     |                                              
app_1     | 
app_1     | 2021-03-29 04:50:00,885 WARN For [program:php-fpm], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
app_1     | 2021-03-29 04:50:00,886 WARN For [program:scheduler], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
app_1     | 2021-03-29 04:50:00,888 WARN For [program:queue-worker], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
app_1     | 2021-03-29 04:50:00,888 WARN For [program:queue-worker], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
app_1     | 2021-03-29 04:50:00,918 INFO supervisord started with pid 1
app_1     | 2021-03-29 04:50:01,920 INFO spawned: 'shutdown' with pid 85
app_1     | 2021-03-29 04:50:01,922 INFO spawned: 'php-fpm' with pid 86
app_1     | 2021-03-29 04:50:01,924 INFO spawned: 'queue-worker_00' with pid 87
app_1     | 2021-03-29 04:50:01,960 INFO spawned: 'queue-worker_01' with pid 88
app_1     | 2021-03-29 04:50:01,965 INFO spawned: 'scheduler' with pid 89
app_1     | READY
app_1     | [29-Mar-2021 04:50:02] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
app_1     | [29-Mar-2021 04:50:02] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
app_1     | [29-Mar-2021 04:50:02] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
app_1     | [29-Mar-2021 04:50:02] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
app_1     | [29-Mar-2021 04:50:02] NOTICE: fpm is running, pid 86
app_1     | [29-Mar-2021 04:50:02] NOTICE: ready to handle connections
app_1     | 2021-03-29 04:50:03,759 INFO success: shutdown entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
app_1     | 2021-03-29 04:50:03,759 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
app_1     | 2021-03-29 04:50:03,759 INFO success: queue-worker_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
app_1     | 2021-03-29 04:50:03,759 INFO success: queue-worker_01 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
app_1     | 2021-03-29 04:50:03,759 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by lonix1** [comment]
Same as yours:
<pre>
invoiceninja/invoiceninja   5.1.32                    6335a7693f9c   15 hours ago    1.12GB
</pre>

**Comment by tecnomur** [comment]
I think the trick is 

Please also read https://github.com/invoiceninja/dockerfiles#updating-the-image-when-using-docker-compose when updating image versions when using docker-compose

there are changes on tree directories and files.

**Comment by lonix1** [comment]
@tecnomur Yes I've suspected what you found - files/dirs and permissions have changed since the last version, so 5.1.32 is a breaking change. Thanks for letting me know, I'll investigate.

**Comment by lonix1** [comment]
@tecnomur Yes I've suspected what you found - files/dirs and permissions have changed since the last version, so 5.1.32 is a breaking change. Thanks for letting me know, I'll investigate.

---

UPDATE: okay did some digging, yes the files have changed but unless you're building from source it shouldn't be a problem (I assume in your case you're building from source?) In my case I'm using the published container, and so that should handle the internal changes automatically. I wonder where the problem is - I think it must be a permission problem. 99% of the time when a container fails to start its permissions :smile:

**Comment by lwj5** [comment]
@lonix1 have you tried the command.

docker-compose up --force-recreate

It solves the problems sometimes. As compose keeps a cache of the file system

**Comment by lonix1** [comment]
@lwj5 Thanks, yes I started from a clean environment - no prior config. I removed all containers, images, networks, volumes, etc.

**Comment by lonix1** [comment]
There are a number of changes from 31 to 32, I'll list my findings below:
- the new compose file does not mount the `shutdown.sh` file ([31](https://github.com/invoiceninja/dockerfiles/blob/5.1.31/docker-compose.yml#L32), [32](https://github.com/invoiceninja/dockerfiles/blob/5.1.32/docker-compose.yml#L29)), but the supervisord [config](https://github.com/invoiceninja/dockerfiles/blob/5.1.32/alpine/5/rootfs/etc/supervisord.conf#L37) needs it, so this is a problem that someome will encounter soon (*BTW: why not just bake this into the image?*)
- in [31](https://github.com/invoiceninja/dockerfiles/blob/5.1.31/alpine/Dockerfile_v5#L105) supervisord started explicitly, but in [32](https://github.com/invoiceninja/dockerfiles/blob/5.1.32/alpine/5/Dockerfile#L99) it is started implicitly and maybe fails to find its config - I suspect the problem is here, but then again why does it work for @lwj5 and not me? Maybe a permissions issue after all?

I'll play around with this some more later, and try find the issue. Let's see if it also affects other people.

**Comment by lwj5** [comment]
you can strike out the first point as well. I baked it into the image in 5.1.32 and removed it from compose.yml, it was weird it wasn't before. Ref https://github.com/invoiceninja/dockerfiles/tree/master/alpine/5/rootfs/usr/local/bin

Yes, as per the last point. If it works for me it should work for you, since it's docker images. Anw let me try testing it on Linux and Windows.

**Comment by lonix1** [comment]
Yes thanks for that, that shutdown script was just annoying :laughing:

BTW I'm on linux, but I don't see why that should matter, you're right that the container should "just work". That said, this is a *common problem on alpine*, that's why the explicit form of starting supervisord is preferred: `CMD ["/usr/bin/supervisord", "-c", "/path/to/supervisord.conf"]`. Most alpine images (that I've seen) start supervisord this way, that's why it was that way before. I don't have time right now to build from source / create my own image, but I'm quite positive this is the issue. I'll test it later and let you know what I discover.

Thanks for looking into it as well!

**Comment by lonix1** [comment]
@lwj5 I've made a custom dockerfile and the problem went away!! There must be some lingering config problem just as you said. I don't get it, docker should "just work"! :sob: Thanks for looking into it, and your gut feel was right after all!
