### ISSUE TITLE
Invoice Ninja Setup - Couple improvements

### ISSUE THREAD

**Issue by kevinjaygonz** [invoiceninja/dockerfiles#311]
**Setup information**

docker-compose

**Describe the bug**
When you are attempting to connect the Database in the setup web wizard you receive errors.

**To reproduce**
1. Go to 'example.com/setup'
2. Once you are in the 'Database Connection' area you click 'Test Connection'
3. See error

**Expected behavior**
I expected that the information that was inputted was correct and would connect successfully connect to the database.

**Screenshots/logs**
![image](https://user-images.githubusercontent.com/13715369/112762200-70975b80-8fcc-11eb-833b-aa60e60bea8e.png)

```
SQLSTATE[HY000] [2002] No such file or directory
```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
(paste your output here)
```

- Output of `helm version`:
```
(paste your output here)
```
- Output of `kubectl version`:
```
(paste your output here)
```

**Additional context**
I've found changing host from 'localhost' to 'dockerfiles_db_1' and also changing the database from 'db-ninja-01' to 'ninja' allow me to connect to the database successfully. Recommend either changing the defaults or adding a disclaimer on the dockerfiles README

**Comment by turbo124** [comment]
in the quick start we do have the following

```
**Note: When performing the setup, the Database host is db

```
