### ISSUE TITLE
PDF Generation failing in Docker

### ISSUE THREAD

**Issue by schmittg25** [invoiceninja/dockerfiles#316]
Docker Compose setup, IN5 is running, but it won't generate any PDFs. I signed up for PhantomJS, and put my key and password in env but it doesn't seem to be working.

![image](https://user-images.githubusercontent.com/81315906/113456744-16d3ce80-93dc-11eb-9f93-b35ffe70a82e.png)

**Comment by turbo124** [comment]
@schmittg25 any reason why you don't want to use the built in PDF generator? it is much faster than Phantom?
