### ISSUE TITLE
"Error: please check that Invoice Ninja v5 is installed on the server" on adding document to expense

### ISSUE THREAD

**Issue by ndroftheline** [invoiceninja/dockerfiles#319]
Hey crew,

I've got docker v5 running on my server and ran through some initial tests with my business partner this evening, but encountered this problem: I can't upload documents to expenses, through the browser or the testflight v5 ios app. I get the error in the subject, "Error: please check that Invoice Ninja v5 is installed on the server" as a popup. 

Current running build v5.1.34-C45 . 

Keen to fix, thanks.

**Comment by turbo124** [comment]
@ndroftheline are you able to upload the files directly from the admin portal via web?

**Comment by ndroftheline** [comment]
i feel like quite a rube asking, but what is the "admin portal"? if that's what we call the regular web app, how do i upload files directly? whether using the regular web app on a browser or the ios app, i get the same error doing the same operation (attempting to upload a document to an expense). 

![image](https://user-images.githubusercontent.com/4163695/113912807-ad1a5100-982f-11eb-8a38-a3f9a38a9ddf.png)

**Comment by hillelcoren** [comment]
Thanks for the screenshot!

Are you able to use the network tab in the browser console to check the URL being used in the request?

**Comment by ndroftheline** [comment]
i think this might be what you were after? this kicks up when the error presents. 
![image](https://user-images.githubusercontent.com/4163695/113913782-d38cbc00-9830-11eb-9648-1799f09877ab.png)

and i was able to confirm that i am, although with an error still, able to upload smaller files:
![image](https://user-images.githubusercontent.com/4163695/113913829-e8694f80-9830-11eb-97a2-63473d8a2b85.png)

**Comment by ndroftheline** [comment]
the file i attempted to attach there is a typical picture i've downloaded from my google photos account, 2.1mb in size

**Comment by ndroftheline** [comment]
found a fairly involved (but old) discussion of what might be a similar problem. https://github.com/nginx-proxy/nginx-proxy/issues/690 

ok, so after adding the client_max_body_size 2048M; entry to the in-vhost.conf file i'm able to perform this upload without an error. 

`server {
#    listen 80 default_server;
    listen 49142 default_server;
    server_name _;
#    server_name in.mounga.eco 192.168.11.60:49142;

    root /var/www/app/public/;
    index index.php;
    client_max_body_size 2048M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass mounga-invoiceninja-app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
    }
}
`

i notice the env reference https://github.com/invoiceninja/invoiceninja/blob/master/.env.example has an item called "#MAX_DOCUMENT_SIZE # KB" i'll try that instead, would prefer to keep modifications in my env file....trying that now.

**Comment by turbo124** [comment]
thanks for letting us know

**Comment by ndroftheline** [comment]
nope, setting

MAX_DOCUMENT_SIZE=2000000 #KB

and disabling the client_max_body_size returns to the previous error.

**Comment by ndroftheline** [comment]
just to clarify - are you guys able to replicate the error on a fresh docker-compose or is it something i've done wrong?

**Comment by turbo124** [comment]
This is a nginx specifc config... We'll update the config to have a larger value
