### ISSUE TITLE
Including phantomjs locally

### ISSUE THREAD

**Issue by LaurensRietveld** [invoiceninja/dockerfiles#32]
This would resolve quite some issues as PDFs can be generated locally. Afaik, this docker image does not include phantomjs yet, so no local pdf generation is supported yet.

Perhaps relevant, this comment on including phantomjs: https://github.com/invoiceninja/invoiceninja/issues/886#issuecomment-270483293

**Comment by lalop** [comment]
hello @LaurensRietveld 

thank you to point this issue.
I will make this asap in the week

**Comment by lalop** [comment]
@LaurensRietveld can you give me a simple way to repproduce the issue caused by the lack of phantomjs ?

**Comment by hillelcoren** [comment]
If PhantomJS isn't installed the app still works but we use a third party service (https://phantomjscloud.com/) to generate the PDF

**Comment by lalop** [comment]
ok, but how can I test if local phantomjs is used ?

**Comment by LaurensRietveld** [comment]
That should be visible on this page: `/settings/email_settings`. Next to the 'attach invoice' setting you should see the text `Using local PhantomJS`. 
If the text didn't show yet, you might need to add env variable `PHANTOMJS_BIN_PATH: /usr/local/bin/phantomjs` to the compose file as well

**Comment by lalop** [comment]
thank you @LaurensRietveld for this information I'm looking to fix this

**Comment by lalop** [comment]
Something like that ?
![capture d ecran 2017-02-02 a 15 26 58](https://cloud.githubusercontent.com/assets/313117/22553182/19277968-e95c-11e6-9488-5e719150bc7f.png)

**Comment by LaurensRietveld** [comment]
jep, exactly!

**Comment by lalop** [comment]
I just push Dockerfile with phantomjs, docker hub should compile a new image with the latest tag in few minutes

**Comment by LaurensRietveld** [comment]
great, seems to be working for me, thanks!

**Comment by lalop** [comment]
good news,
thank you
