### ISSUE TITLE
DEBUG MODE IS ENABLED will not go away.

### ISSUE THREAD

**Issue by darrylgibbs** [invoiceninja/dockerfiles#322]
**Setup information**
Complete and working install of Invoice Ninja v5.1.42 on Raspberry Pi 4 using official git repo.

**Describe the bug**
Despite completing setup and setting ENV variable APP_DEBUG=false and then restarting the entire stack, and even rebooting the Pi multiple times, the red block warning will not go away.

What am I doing wrong?

Multiple uses of the "docker-compose exec app php artisan migrate" hasn't helped either.

ENV file:
```
APP_URL=my.domain.here
APP_KEY=my-app-key-here
**APP_DEBUG=false**
MULTI_DB_ENABLED=false
DB_HOST1=db
DB_PORT1=3306
DB_USERNAME1=ninja
DB_PASSWORD1=mypasswordhere
DB_DATABASE1=ninja
MYSQL_ROOT_PASSWORD=myOTHERpasswordhere
MYSQL_USER=ninja
MYSQL_PASSWORD=mypasswordhere
MYSQL_DATABASE=ninja

#this is a system variable please do not remove
IS_DOCKER=true

PHANTOMJS_PDF_GENERATION=true

#V4 env vars
DB_STRICT=false
DB_HOST=db
DB_DATABASE=ninja
DB_USERNAME=ninja
DB_PASSWORD=ninja
APP_CIPHER=AES-256-CBC
```

**Comment by lwj5** [comment]
Have you tried `docker-compose up --force-recreate`

Might be the PHP Opcache

**Comment by darrylgibbs** [comment]
That seems to have done it! Thanks!

Although, I did do a create multiple times, but via PORTAINER.  However, I'm not sure there was a **force** option included.

**Comment by dwishaventures** [comment]
> docker-compose up --force-recreate

It didnt work for me. Any other trick ?
