### ISSUE TITLE
[Bug] Cannot generate key on R Pi 4

### ISSUE THREAD

**Issue by manakill** [invoiceninja/dockerfiles#324]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
5

**What environment are you running?**
Docker on Pi 4

Command:
docker run --rm -it invoiceninja/invoiceninja php artisan key:generate --show

Output:
Unable to find image 'invoiceninja/invoiceninja:latest' locally
latest: Pulling from invoiceninja/invoiceninja
docker: no matching manifest for linux/arm/v7 in the manifest list entries.

**Comment by lwj5** [comment]
Hi @manakill 

ARMv7 is not supported. Only ARM64 on Pi 4

@turbo124 do you think #108 should be re-opened

**Comment by lwj5** [comment]
If not other comments, this will be tracked in #183
