### ISSUE TITLE
SSL Certs?

### ISSUE THREAD

**Issue by manakill** [invoiceninja/dockerfiles#329]
I have seen a container or two that have SSL certs tied into Invoice Ninja container. Can we tie it in with settings in the yml? Or a way to get it to work on a subdomain and easily installed with Lets Encrypt? 

I know we have options but I don't know what would be the easiest or most proper. I also feel that some solution or directions, would a good addition to the current setup.

**Comment by turbo124** [comment]
I think the easiest way would be to use the Caddy template - caddy will provide auto ssl :)

**Comment by manakill** [comment]
Oh my, what is this hocus pocus!? Thanks, this looks like it'll solve my multiple SSL needs and more!
(this is one of those times I'm glad I asked for any opinions rather than just trying something myself lol)

**Comment by scchearn** [comment]
> I think the easiest way would be to use the Caddy template - caddy will provide auto ssl :)

Please explain how to use the Caddy template with docker compose. I don't know if I'm just being blind, but I can not see any info on HTTPS/SSL with the docker image. Maybe I missed some prerequisites along the way.

**Comment by manakill** [comment]
Run Caddy in it's own container and configure it there, for what ports to listen on, and where to send the traffic. It will do the job of getting SSL certs on it's own. It's been working beautifully on some other software I run, for months on end, with no issues at all. I haven't used on Invoice Ninja since one of the main functions I need is still not implemented (working with BTCPayServer)
