### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory 

### ISSUE THREAD

**Issue by cornelissensolutions** [invoiceninja/dockerfiles#333]
**Setup information**
I have a VPS server where I run several production docker instances. I have a traefik docker container running on p80 and p443 which covers the ssl certification. 
I have invoiceninja running via an edited docker-compose file (added the traefik labels and network to it)

**Describe the bug**
When I run the docker, I first get a crappy setup page (not the same as which I have on a local test server) 
![Screenshot from 2021-04-28 21-56-59_crop](https://user-images.githubusercontent.com/46491144/116710418-08280980-a9d2-11eb-9292-c462b9352aaa.png) but nevertheless, when I fill in all the data and press submit, I get the following error: 
SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = ninja and table_name = accounts and table_type = 'BASE TABLE')
![Screenshot from 2021-04-28 21-56-31_crop](https://user-images.githubusercontent.com/46491144/116710505-1f66f700-a9d2-11eb-9974-5da21019d794.png)

**To reproduce**
1. Go to <url>/setup'
2. Fill in all the data needed
3. Click on submit

**Expected behavior**
When I run this locally, I end up with a working invoiceninja instance. 

**Screenshots/logs**
2021-04-30T14:06:51.400898Z 0 [Note] mysqld: ready for connections.
app_1     | In Connection.php line 678:
db_1      | Version: '5.7.34'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
app_1     |                                                                                
app_1     |   SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from inform  
app_1     |   ation_schema.tables where table_schema = ninja and table_name = accounts an  
app_1     |   d table_type = 'BASE TABLE')                                                 
app_1     |                                                                                
app_1     | 
app_1     | In Exception.php line 18:
app_1     |                                                     
app_1     |   SQLSTATE[HY000] [2002] No such file or directory  
app_1     |                                                     
app_1     | 
app_1     | In PDOConnection.php line 39:
app_1     |                                                     
app_1     |   SQLSTATE[HY000] [2002] No such file or directory
app_1     | 
app_1     | [2021-04-30T14:16:00+00:00] Execution #10 output:
app_1     | No scheduled commands are ready to run.
app_1     | 
app_1     | [2021-04-30T14:17:00+00:00] Execution #11 output:
app_1     | No scheduled commands are ready to run.

```
Any Error that sucks
```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:01 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Additional context**
I found a similar  thread which is already closed : https://github.com/invoiceninja/dockerfiles/issues/260 but there the solution was in the nginx container with the certificate. Which will not help in my case (imo)

**Comment by turbo124** [comment]
as mentioned in the other thread, you'll want to edit the `env` file and use the correct DB credentials there. The setup page on docker doesn't pass through the DB credentials
