### ISSUE TITLE
question: installed with docker compose, however just getting Welcome to nginx screen

### ISSUE THREAD

**Issue by brinx338** [invoiceninja/dockerfiles#334]
Hello, this might be something very simple that I'm overlooking. 
Wondering if there's anyone that could assist.

**Describe the bug**

Installed using docker compose (changed the service port to 8080) in both the env and yaml files.

**To reproduce**
=========== my env file ========== 

APP_URL=http://192.168.15.167:8080
APP_KEY=base64:Gf15AabcdefghijkellomennopPc0/yOS5LbotPc=
APP_DEBUG=true
MULTI_DB_ENABLED=false
DB_HOST1=db
DB_PORT1=3306
DB_USERNAME1=ninja
DB_PASSWORD1=ninja
DB_DATABASE1=ninja
PHANTOMJS_PDF_GENERATION=false

==============================

========= my yaml file  ============
only thing changed is:
**ports:**
      - "8080:80"
      #- "443:443"
and I have commented out the lines for _extra hosts_
==============================

please ignore the **bold**, not sure how to remove

**Expected behavior**
Expecting to get the invoiceninja setup/login screen

**Screenshots/logs**
![Capture](https://user-images.githubusercontent.com/83820851/117450920-77888680-af07-11eb-9c38-90a8f697a0f7.JPG)
... so I think I'm almost there..

```
no error/seems to complete successfully when running compose command below

admin@teslaNAS:/volume1/docker/invoiceninja$
admin@teslaNAS:/volume1/docker/invoiceninja$ sudo docker-compose up --detach
Recreating invoiceninja_db_1 ... _done_
Recreating invoiceninja_app_1 ... _done_
Recreating invoiceninja_server_1 ... _done_
admin@teslaNAS:/volume1/docker/invoiceninja$

```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
18.09.8
```

**Additional context**
This is on a Synology NAS (portainer status).
![Capture2](https://user-images.githubusercontent.com/83820851/117451246-df3ed180-af07-11eb-8e99-d063b7d6ddc2.JPG)

Trying to figure out what "further configuration is required" as mentioned by the nginx welcome screen.
Appreciate any assistance.

**Comment by brinx338** [comment]
> 
> 
> Judging from here #195 i don't think there was much luck getting this to work on portainer.

Thanks for responding...

I'm technically not using portainer... (tried creating this using a stack at first, but it doesn't even get halfway through the install)

once I tried the installation using standard config.yml file it seems to install okay and brings up all the images.

I included the screenshot for the portainer just to show that the containers are up and running

Thanks again

**Comment by lwj5** [comment]
Hey @brinx338

just change the line
https://github.com/invoiceninja/dockerfiles/blob/4ee20766ef17f0bac99977e604e01d3d57b0adbe/docker-compose.yml#L11

in-vhost to default to replace all default route
