### ISSUE TITLE
persistent data and update

### ISSUE THREAD

**Issue by lalop** [invoiceninja/dockerfiles#34]
From the invoiceninja repos, dixit @freskimo

> If you setup invoice ninja the first time in a docker container the declared volume /var/www/app/public is persistent. This means that if the container is restarted the changes made on this directory different from the original image are persisted. Once you want to update a new version you pull the new image and stop the current container then you start the same container with the new image. Because the volumes are persistent the changes reflected in the new image are not copied over the existing files. This means all files in /var/www/app/public are not updated with the new version.

**Comment by lalop** [comment]
As said in the readme https://github.com/invoiceninja/dockerfiles/blob/master/README.md, you should not presist the public folder only  `public/logo` all other files comes with the new image.
This image can't be aware of what is persisted or not

**Comment by freskimo** [comment]
I know...

But you declared volume in the Dockerfile (which means it is persistent!!). I know you did this to use the volumes_from on the web service. But this has the side-effect of the problem we are discussing.

**Comment by lalop** [comment]
Oh ? I didn't know that, re you sure ?

**Comment by freskimo** [comment]
https://github.com/invoiceninja/dockerfiles/blob/master/Dockerfile#L55

**Comment by lalop** [comment]
:) sorry I mean are you sure that the data will be persisted  even if no external folder is mounted on public ?

**Comment by freskimo** [comment]
Yes, declared volume in the Dockerfile, externally or named are actually all the same. Internally a directory under the docker mount directory will be created which holds all changes with respect to the original image.

> The VOLUME instruction creates a mount point with the specified name and marks it as holding externally mounted volumes from native host or other containers.

> Note: If any build steps change the data within the volume after it has been declared, those changes will be discarded.
This last line should be read as "if the volume is created". The order of the volume directive in the Dockerfile does not matter whatsoever

**Comment by freskimo** [comment]
This is actually logic when you think about it. If you say some directory needs to be persistent you don't want that starting up a new instance of this container will save over all the data you wish to keep.

**Comment by lalop** [comment]
how do you update your image ?
I have to reproduce this issue since I'm running this image since I created it, updating each time a new version is out and I never get this kind of issue.

**Comment by freskimo** [comment]
`docker-compose pull`
`docker-compose up -d`

I can omit the problem by:
`docker-compose pull`
`docker-compose stop`
`docker-compose rm -f`
`docker-compose up -d`

But this is not the preferred method because you remove the persistent volumes...

**Comment by freskimo** [comment]
@lalop what do you think?

How do you update then?

**Comment by lalop** [comment]
I update like this : 
```
docker-compose pull
docker-compose stop 
docker-compose rm app
docker-compose up -d
```
I was aware of docker is persisting all the defined volume, you point a real issue but I don't know what is the good way to solve this.
Rsync is a good one but it adds some complexity to the image, in an other and all the other Dokerfile I see ( wordpress, nextcloud ... ) don't seam to manage this. 
So I'm looking for a commun way to solve this... maybe adding some doc about how to update will solve this.

**Comment by lalop** [comment]
@pierreozoux maybe you can light us here

**Comment by freskimo** [comment]
I'll make a new PR without the rsync. 

Which directories contain persistent data?
- logo `app/public/logo`
- log files `app/storage/logs`
- where are the uploaded documents?
- other things i might be missing?

**Comment by lalop** [comment]
I think the only persistent data are in `app/public/logo` and `app/storage` , @hillelcoren can you confirm this ?
How do you want to do whithout rsync ?

**Comment by hillelcoren** [comment]
@lalop I believe that's correct. 

@freskimo The documents are stored in storage/documents/

**Comment by hillelcoren** [comment]
Note: it's `storage` rather than `app/storage`

**Comment by lalop** [comment]
@hillelcoren, this can be confusing but the application is in `/var/www/app` in the docker image here is why I wrote `app/storage` :)

**Comment by hillelcoren** [comment]
Ah, ok. Gotcha.

**Comment by freskimo** [comment]
I would replace rsync with cp

**Comment by lalop** [comment]
humm... I'm doing this for the logo and storage directory not for the public, my bad 
https://github.com/invoiceninja/dockerfiles/blob/master/app-entrypoint.sh#L37

**Comment by freskimo** [comment]
maybe cleaner if it uses symlinks instead of copying all this data.
I'll try something out when I have some time left.

**Comment by lalop** [comment]
I fixed it https://github.com/invoiceninja/dockerfiles/commit/c07242eb1c7231b4c39adb98eef6406bddcf239f
