### ISSUE TITLE
SQLSTATE[HY000] [1045] Access denied for user ''@'xxx' (using password: NO)

### ISSUE THREAD

**Issue by chrisskeddy** [invoiceninja/dockerfiles#341]
**Setup information**
I'm using Ubuntu 20.04.2 server edition. In installed this in a VM and I installed
Docker version 20.10.6, build 370c289
docker-compose version 1.29.2, build 5becea4c
Edit: I git pulled from this repo less then 2 hours ago. Monday May 10th 17:00 PST

**Describe the bug**
It appears as if something is wrong with invoice ninja accessing the database for some queries.

**To reproduce**
I'm using Ubuntu 20.04.2 server edition. In installed this in a VM and I installed
Docker version 20.10.6, build 370c289
docker-compose version 1.29.2, build 5becea4c

I followed the directions in the readme file

URL "http://192.168.2.1"
require https "False"
Passes Test PDF
Host: 192.168.2.1
Port: 3305(since docker-compose file remaps it)
Database:ninja(docker-compose file named it this)

I select log for smtp(since I don't have something setup)

Attempt to create user. sends me back to setup page.
I don't get any errors in the browser

**Expected behavior**
Create user and continue 

**Screenshots/logs**
server_1  | 192.168.2.10 - - [11/May/2021:02:48:07 +0000] "POST /setup/check_db                                                                                                                                                              HTTP/1.1" 200 12 "http://192.168.2.1/setup" "Mozilla/5.0 (Windows NT 10.0; Win6                                                                                                                                                             4; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36                                                                                                                                                             " "-"
app_1     | 172.18.0.4 -  11/May/2021:02:48:07 +0000 "POST /index.php" 200
db_1      | 2021-05-11T02:48:27.401674Z 6 [Note] Access denied for user ''@'172.                                                                                                                                                             18.0.1' (using password: NO)
db_1      | 2021-05-11T02:48:27.416603Z 7 [Note] Access denied for user ''@'172.                                                                                                                                                             18.0.1' (using password: NO)
db_1      | 2021-05-11T02:48:27.483916Z 9 [Note] Access denied for user ''@'172.                                                                                                                                                             18.0.1' (using password: NO)
server_1  | 192.168.2.10 - - [11/May/2021:02:48:27 +0000] "POST /setup HTTP/1.1"                                                                                                                                                              302 358 "http://192.168.2.1/setup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)                                                                                                                                                              AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "-"
app_1     | 172.18.0.4 -  11/May/2021:02:48:27 +0000 "POST /index.php" 302
db_1      | 2021-05-11T02:48:27.525914Z 10 [Note] Access denied for user ''@'172                                                                                                                                                             .18.0.1' (using password: NO)
db_1      | 2021-05-11T02:48:27.541168Z 11 [Note] Access denied for user ''@'172                                                                                                                                                             .18.0.1' (using password: NO)
server_1  | 192.168.2.10 - - [11/May/2021:02:48:27 +0000] "GET /setup HTTP/1.1"                                                                                                                                                              200 20914 "http://192.168.2.1/setup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)                                                                                                                                                              AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "-"
app_1     | 172.18.0.4 -  11/May/2021:02:48:27 +0000 "GET /index.php" 200
app_1     |
app_1     | [2021-05-11T02:49:00+00:00] Execution #8 output:
app_1     | No scheduled commands are ready to run.
server_1  | 192.168.2.10 - - [11/May/2021:02:49:10 +0000] "POST /setup/check_pdf HTTP/1.1" 200 40 "http://192.168.2.1/setup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "-"
app_1     | 172.18.0.4 -  11/May/2021:02:49:10 +0000 "POST /index.php" 200
app_1     | 2021-05-11 02:49:10,464 INFO reaped unknown pid 266 (exit status 0)
app_1     | 2021-05-11 02:49:10,464 INFO reaped unknown pid 282 (terminated by SIGTERM)
app_1     | 2021-05-11 02:49:10,465 INFO reaped unknown pid 288 (exit status 0)
app_1     | 2021-05-11 02:49:11,467 INFO reaped unknown pid 265 (exit status 0)
server_1  | 192.168.2.10 - - [11/May/2021:02:49:18 +0000] "POST /setup/check_db HTTP/1.1" 400 109 "http://192.168.2.1/setup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "-"
app_1     | 172.18.0.4 -  11/May/2021:02:49:18 +0000 "POST /index.php" 400
server_1  | 192.168.2.10 - - [11/May/2021:02:49:29 +0000] "POST /setup/check_db HTTP/1.1" 200 12 "http://192.168.2.1/setup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "-"
app_1     | 172.18.0.4 -  11/May/2021:02:49:29 +0000 "POST /index.php" 200
app_1     |
app_1     | [2021-05-11T02:50:00+00:00] Execution #9 output:
app_1     | Running scheduled command: App\Jobs\Util\SchedulerCheck
db_1      | 2021-05-11T02:50:00.255031Z 13 [Note] Access denied for user ''@'172.18.0.1' (using password: NO)
db_1      | 2021-05-11T02:50:00.258809Z 14 [Note] Access denied for user ''@'172.18.0.1' (using password: NO)
db_1      | 2021-05-11T02:50:00.260238Z 15 [Note] Access denied for user ''@'172.18.0.1' (using password: NO)
db_1      | 2021-05-11T02:50:00.261510Z 16 [Note] Access denied for user ''@'172.18.0.1' (using password: NO)
app_1     | In Connection.php line 678:
app_1     |
app_1     |   SQLSTATE[HY000] [1045] Access denied for user ''@'172.18.0.1' (using passwo
app_1     |   rd: NO) (SQL: select * from information_schema.tables where table_schema =
app_1     |   ninja and table_name = accounts and table_type = 'BASE TABLE')
app_1     |
app_1     |
app_1     | In Exception.php line 18:
app_1     |
app_1     |   SQLSTATE[HY000] [1045] Access denied for user ''@'172.18.0.1' (using passwo
app_1     |   rd: NO)
app_1     |
app_1     |
app_1     | In PDOConnection.php line 39:
app_1     |
app_1     |   SQLSTATE[HY000] [1045] Access denied for user ''@'172.18.0.1' (using passwo
app_1     |   rd: NO)

**Comment by lwj5** [comment]
Hi @chrisskeddy 

The next build of docker image will resolve this.

could you prefix the number 1 to the following in the env in the meantime.
DB_USERNAME
DB_PASSWORD

so meaning use
DB_USERNAME1
DB_PASSWORD1

**Comment by lwj5** [comment]
I updated my last post, the container should run once you fall back to the previous `env` file here:

https://github.com/invoiceninja/dockerfiles/blob/62b1d8cb9426f7c530f938a9249b251c8b769620/env

This is until 5.1.62 is released

**Comment by chrisskeddy** [comment]
Today I started invoice ninja again
It redownloaded MySQL and Invoice ninja
I'm now getting an error of:

Starting invoice_ninja_2021_db_1 ...
Starting invoice_ninja_2021_db_1 ... error

ERROR: for invoice_ninja_2021_db_1  Cannot start service db: driver failed programming external connectivity on endpoint invoice_ninja_2021_db_1 (593e1b3b7f58b262dc6f05d33928eb8ef3e33e5d971255724d80047fd0e92495): Error starting userland proxy: listen tcp 0.0.0.0:3305: bind: address already in use

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint invoice_ninja_2021_db_1 (593e1b3b7f58b262dc6f05d33928eb8ef3e33e5d971255724d80047fd0e92495): Error starting userland proxy: listen tcp 0.0.0.0:3305: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by chrisskeddy** [comment]
After changing the env file over I was able to create an account and start using the service.
