### ISSUE TITLE
Something went wrong: file(/var/www/app/.env): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by deeztek** [invoiceninja/dockerfiles#344]
Hi,

trying to get Invoice Ninja with docker compose, however I'm getting the following error in the Invoice Ninja Setup page after I go through the Application Settings, Database Connection and Email Settings successfully, I check I agree to the terms of service and privacy policy and I hit submit I'm immediately greeted with the error below:

![image](https://user-images.githubusercontent.com/17934095/117987780-d0419000-b308-11eb-9815-c334e6eb08ea.png)

I've ensured that the permissions and the owner are setup per the instructions:

chmod 755 docker/app/public
sudo chown -R 1500:1500 docker/app

I would appreciate some help.

Thanks a lot

**Comment by lwj5** [comment]
Hi @deeztek 

Thanks for reporting this bug, I’ll try to come up with a fix ASAP.

In the mean time, while the compose is running. Issues this commands

`docker ps`

and

`docker exec -it <container id from above> touch .env`

My apologies for the inconvenience.

**Comment by deeztek** [comment]
The workaround seems to to work however, doing a Health Check in the app says the .env is not writable.

**Comment by hillelcoren** [comment]
I think you can ignore that, I believe it's from using Docker. We'll disable this warning.

**Comment by bhuris** [comment]
> Hi @deeztek
> 
> Thanks for reporting this bug, I’ll try to come up with a fix ASAP.
> 
> In the mean time, while the compose is running. Could you run these commands
> 
> `docker ps`
> 
> and
> 
> `docker exec -it <container id from above> touch .env`
> 
> Let me know if it works after. My apologies for the inconvenience.

@lwj5 
It works now !! Thank so much !!

**Comment by turbo124** [comment]
@kameleon25 we've changed the flow of the setup - now you just need to add your desired username/password to the docker .env and the initial account will be configured without having to touch the setup screen.
