### ISSUE TITLE
[Helm] Too many redirects after setting up as HTTPS

### ISSUE THREAD

**Issue by ffaen** [invoiceninja/dockerfiles#349]
**Setup information**

Helm

**Describe the bug**
After an initial setup of invoiceninja using helm, trying to access to login screen through https will fail with `ERR_TOO_MANY_REDIRECTS`

**To reproduce**
1. Install Invoiceninja with `helm install -n invoiceninja invoiceninja invoiceninja/invoiceninja --create-namespace -f values.yaml`
2. Complete setup over http
3. Add HTTPS certificate and `helm upgrade -n invoiceninja invoiceninja invoiceninja/invoiceninja`
4. Navigate to URL

**Expected behavior**
Page should not error, show login screen

**Screenshots/logs**
No screenshots or logs that seem useful, just lots of hits to the login page redirecting to itself

**Docker/Kubernetes/Helm**:
- Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```
- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
values.yaml:

```yaml
nginx:
  ingress:
    enabled: true
    hostname: ninja.{snip}
    # add in step 3
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # end
appKey: {snip}
redis:
  password: {snip}
mariadb:
  auth:
    password: {snip}
    rootPassword: {snip}
global:
  storageClass: csi-cinder-classic
volumePermissions:
  enabled: true
```

**Comment by lwj5** [comment]
Could you set add an extra env

REQUIRE_HTTPS=false

and restart the pod

**Comment by ffaen** [comment]
Yes, that seems like it's done it. Is this a mistake I made with my configuration or is this something that should be adjusted in the config map? I can take a look and see if I can put in a PR if this is the case

**Comment by lwj5** [comment]
The Force HTTPS option in the initial setup page of IN can be a little confusing and should be unchecked when using TLS terminating at the ingress. 

Here’s the flow:
Client > Ingress > Nginx (IN app)

Although the connection between the Client and Ingress is over HTTPS, the connection between Ingress and Nginx is over HTTP as TLS is terminated at the Ingress.

So technically Invoice Ninja always sees a HTTP connection even if it tries to upgrade it, leading to a loop.

The latest commits to the docker image will remove the setup page which will make setup easier. I’m awaiting image 5.1.63 to be release before releasing next chart version where there will also be an additional option to set REQUIRE_HTTPS to true (defaults to false) and a few other options.

If you manage to use the extraEnvVars or extraEnvVarsCM and don’t mind helping to document in a section before Upgrading it would be great. This would help others who might want to set other env.

**Comment by ffaen** [comment]
> If you manage to use the extraEnvVars or extraEnvVarsCM and don’t mind helping to document it in a section before “Upgrading” it would be great. This would help others who might want to set other env.

I've opened #351 to discuss on this further. 

I've also noticed since deploying with this change that some routes still try to use HTTP, most notably the Customer Portal's CSS and JS files. Is this a result of the proxy process as well, the Laravel app providing HTTP resources and then the nginx proxy forcing HTTPS?

**Comment by lwj5** [comment]
I've fixed the configmap such that the APP_URL uses `https://` if TLS ingress is enabled. Once you upgrade the chart and restart the IN pod, it should work as intended. 

You can choose to force HTTPS on the ingress using Nginx annotations if you like.

**Comment by ffaen** [comment]
Hey

Thanks for the quick release, I'm running it and it seems to have fixed the customer portal (mostly!) 

There still seems to be some other assets that are trying to be loaded over HTTP:

![image](https://user-images.githubusercontent.com/3136033/118565848-d2717780-b76a-11eb-90ec-0db5cc225ed0.png)

This isn't directly attached to this issue so happy to spin this out to another issue if required.

Also if you can give me a starting direction I can look into fixing this myself, but I assume it may be in the invoiceninja repo instead of here?

**Comment by lwj5** [comment]
Just tested it on my server. Have you disabled your cache?

![Screenshot 2021-05-18 at 10 32 53 AM](https://user-images.githubusercontent.com/16207788/118581597-78050500-b7c4-11eb-8017-1233041e507c.png)

**Comment by ffaen** [comment]
> This shows that it is loading HTTPS. If you don't get `https://` and your APP_URL is correct, then it might be cache.

`sh`ing onto the main pod and running `echo $APP_URL` returns a https url

> 
> Few things to try:
> 
> * Clear your cache, or disable it on the network pane of the dev tools

Cache was cleared, still no help :(

> * Clear CDN cache (if any)

No CDN, everything is directly from the server

> * Clear Laravel cache. You can try a `php artisan cache:clear` in IN pod.

I get this after running that, so maybe my install is broken in some way?

```
2021-05-18 08:56:57] production.ERROR: ERR unknown command `FLUSHDB`, with args beginning with:  {"exception":"[object] (Predis\\Response\\ServerException(code: 0): ERR unknown command `FLUSHDB`, with args beginning with:  at /var/www/app/vendor/predis/predis/src/Client.php:370)
```


> 
> If it still doesn't help, I would advise waiting for the 5.1.63 image release as there are some important fixes that might help.

I'll keep an eye out. Just to double check, since the release of the 0.4.1 do I still require the extra REQUIRE_HTTPS='false' in my extraEnvVars?

**Comment by lwj5** [comment]
Hey, 

Don’t worry, your Invoice Ninja install is fine. It’s likely the Redis caching old content causing the HTTP issue. Bitnami probably renamed the `FLUSHDB` command is for safety reasons and hence why you got that error.

> I'll keep an eye out. Just to double check, since the release of the 0.4.1 do I still require the extra REQUIRE_HTTPS='false' in my extraEnvVars?

Yes it is still required until an update of the Helm Chart after 5.1.63 is released.

**Comment by lwj5** [comment]
IN 5.1.63 and chart 0.5.0 is released, you can remove the extra env once you upgrade

**Comment by ffaen** [comment]
> You will need to flush Redis manually. I do not have the instructions on top of my head, you might need to do a google search on how to do this.

I resolved this by adding the following to my `values.yaml` (from this [StackOverflow answer](https://stackoverflow.com/a/59189742/4739911)):

```yaml
redis:
  // ...
  master:
    disableCommands: []
  slave:
    disableCommands: []
```

The cache clear works as intended then.

Customer Portal seems to be working okay over HTTPS now, but viewing an invoice internally is still bringing up a mixed content error, even after the flushdb 

![image](https://user-images.githubusercontent.com/3136033/119192237-b5dd8400-ba77-11eb-9c40-9241b8d44259.png)

**Comment by lwj5** [comment]
@ffaen I've tried it and faced the same issue as well for View PDF. I've created an issue here: https://github.com/invoiceninja/invoiceninja/issues/5793

Let's track this issue over there instead.

**Comment by ffaen** [comment]
Hi

Bringing this back here as I now believe that it's an issue with the trusted proxies not being set in the chart.

Adding this to the `values.yaml` allows laravel to pick up that we're using HTTPS:

```yaml
extraEnvVars:
  - name: TRUSTED_PROXIES
    value: '*'
```

I'm not well versed with Helm chart configs, but if there is a way we can get the IP address of the nginx server that would be more specific? If not, then this will do. I can put this into the configmap and make a pull request if you'd like?

**Comment by lwj5** [comment]
> I can put this into the configmap and make a pull request if you'd like?

Yes, that would be great! 

> I'm not well versed with Helm chart configs, but if there is a way we can get the IP address of the nginx server that would be more specific? If not, then this will do.

We can't get the IP unless it's resolved via hostname. I think it would be okay to leave it as `*` and expose a `trustedProxies` variable in values.yaml for a user to set it if they want.

If you need help working with values let me know, I'll help add on to your PR.

**Comment by lwj5** [comment]
Replied in #355
