### ISSUE TITLE
Stup stuck

### ISSUE THREAD

**Issue by aorvay** [invoiceninja/dockerfiles#354]
**Setup information**

**Describe the bug**
I'm stuck on the setup, every time I complete the form it start again. I'm very new on this.

I think is a database connection problem but can't fix it!!!

![setup_invoiceninja_stuck](https://user-images.githubusercontent.com/17532118/118709030-c645f280-b81c-11eb-8e42-29512d91a2ab.jpg)

I'll attach a "docker-compose logs -f" if it helps!

Thnak you a lot

**Comment by turbo124** [comment]
Are you using the standard docker-compose file or have you created this docker file yourself?

If you have no experience with Docker this would be the easiest way to get started.
