### ISSUE TITLE
"View PDF" in Invoice section redirects to HTTP URL

### ISSUE THREAD

**Issue by lwj5** [invoiceninja/dockerfiles#355]
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.65

**What environment are you running?**
Docker/Helm

**Have you checked log files (storage/logs/) Please provide redacted output**
None, see screenshot below and info reported by @ffaen https://github.com/invoiceninja/dockerfiles/issues/349#issuecomment-846222887

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
Clicking "View PDF" in an invoice section redirects to HTTP URL. Leading to a `blocked:mixed content` by Chrome.
Although APP_URL is using HTTPS.

Unfortunately, I haven't had time to look into the code, so I can't say what is wrong yet.

**Steps To Reproduce**
- Launch a fresh instance of IN (helm in this case)
- Use https://xxx as APP_URL
- Create an invoice
- Click "View PDF"

**Expected behavior**
The download is redirected to an HTTPS URL

**Screenshots**
![Screenshot 2021-05-24 at 12 23 16 AM](https://user-images.githubusercontent.com/16207788/119268594-45c13080-bc26-11eb-84df-d32c2d4d2413.png)

After allowing mixed content in Chrome:
![Screenshot 2021-05-24 at 12 05 41 AM](https://user-images.githubusercontent.com/16207788/119268205-815afb00-bc24-11eb-9c69-45bcc7e8d9f7.png)

Note: 2nd redirect is due to my server rule settings redirecting all HTTP traffic to HTTPS

**Additional context**
TLS terminates at the load balancer
See network topology here: https://github.com/invoiceninja/dockerfiles/issues/349#issuecomment-841840164

Note: Before posting don't forget to check our "Troubleshooting" category in the [docs](https://invoiceninja.github.io/docs/self-host-troubleshooting/) (https://invoiceninja.github.io/docs/self-host-troubleshooting/).

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
No

**Comment by lwj5** [comment]
Reply for #349

> I can put this into the configmap and make a pull request if you'd like?

Yes, that would be great! 

> I'm not well versed with Helm chart configs, but if there is a way we can get the IP address of the nginx server that would be more specific? If not, then this will do.

We can't get the IP unless it's resolved via hostname. I think it would be okay to leave it as `*` and expose a `trustedProxies` variable in values.yaml for a user to set it if they want.

If you need help working with values let me know, I'll help add on to your PR.

**Comment by ffaen** [comment]
PR has been created, please review at your convenience :)

**Comment by cdmoss** [comment]
I'm getting this exact issue - I'm running a brand new install, TRUSTED_PROXIES is set to '*'.
