### ISSUE TITLE
FPM is failing

### ISSUE THREAD

**Issue by staegi** [invoiceninja/dockerfiles#361]
If I launch it a newer version than 4.5.18 then FPM is failing. See console output:

`[01-Jun-2021 18:28:42] NOTICE: fpm is running, pid 1`
`[01-Jun-2021 18:28:42] NOTICE: ready to handle connections`
`[01-Jun-2021 18:30:23] NOTICE: Finishing ...`
`[01-Jun-2021 18:30:23] ERROR: unable to read what child say: Bad file descriptor (9)`
`[01-Jun-2021 18:30:23] ERROR: unable to read what child say: Bad file descriptor (9)`
`[01-Jun-2021 18:30:23] NOTICE: exiting, bye-bye!`

As I figured out on stackoverflow it's failing because the `pm.max_children` setting in the php ini

**Comment by turbo124** [comment]
unable to replicate this on any of my environments. are you using the provided docker file?

**Comment by staegi** [comment]
Yes, I tried `invoiceninja/invoiceninja:4.5.38`. With `invoiceninja/invoiceninja:4.5.18` it works.
