### ISSUE TITLE
Build Pipeline for 5.1.72 failed - Not uploaded to Docker Hub

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/dockerfiles#363]
**Describe the bug**
Build Pipeline didn't pass, 5.1.72 didn't get uploaded to Docker Hub. For Error detail see the Logs https://github.com/invoiceninja/dockerfiles/actions/runs/918278104

**Screenshots/logs**
https://github.com/invoiceninja/dockerfiles/actions/runs/918278104
![image](https://user-images.githubusercontent.com/65533611/121295054-b20e8600-c8ee-11eb-9c9d-df15ae7122f2.png)

**Comment by turbo124** [comment]
I've just tagged 5.1.74. this should build correctly.
