### ISSUE TITLE
.env pdf phantom is set by default

### ISSUE THREAD

**Issue by tecnomur** [invoiceninja/dockerfiles#384]
Snappdf is not set by default.

![Captura 2021-07-02 a las 19 35 41](https://user-images.githubusercontent.com/47739534/125170844-3f285180-e1b1-11eb-85e2-de2172c8519b.png)

I need to change it to snappdf to make works pdf generation.

**Comment by turbo124** [comment]
This is by design, most users are running system that cannot support the underlying libraries that Snappdf requires: You can set Snappdf by setting the following .env VARS

PDF_GENERATOR=snappdf 
PHANTOMJS_PDF_GENERATION=false

**Comment by turbo124** [comment]
The dockerfiles env file overrides the container .env file

If you inspect that you'll see

```
PHANTOMJS_PDF_GENERATION=false
```

**Comment by tecnomur** [comment]
I know, but doesn’t works for me.

![DB49C233-039B-4EB1-AD39-D0270C95680F](https://user-images.githubusercontent.com/47739534/125200922-490f8a80-e26d-11eb-87d7-caf17c21684c.jpeg)

**Comment by turbo124** [comment]
I can recreate this!

The fix is to add into the env file the following:

```
PDF_GENERATOR=snappdf
```
