### ISSUE TITLE
Docker :latest tag not installed latest version

### ISSUE THREAD

**Issue by glassbase** [invoiceninja/dockerfiles#388]
**Setup information**

docker-compose

**Describe the bug**
Docker :latest tag does not pull latest version. I just pulled :latest tag now and it is installed 5.2.17 and should have pulled .19. I know sometimes there is a delay with image building, but even .18 has been out for a few days. 

**To reproduce**
1. Install IN using :latest tag
2. Observe installed version is not the latest

**Expected behavior**
See above

**Screenshots/logs**
n/a 

n/a

**Docker/Kubernetes/Helm**:
n/a

n/a

**Additional context**
n/a

**Comment by turbo124** [comment]
are you using the standard docker-compose file from this repo?

I believe 

```
docker-compose down
docker-compose pull
docker-compose up
```

is all that should required
