### ISSUE TITLE
pending Jobs only stacks up on version 5.2.11

### ISSUE THREAD

**Issue by danielgroen** [invoiceninja/dockerfiles#390]
Hi,

I can't send any invoices. When i click on "health check" i see the following:
![afbeelding](https://user-images.githubusercontent.com/6578052/130092527-8d58e10b-97c3-4b79-9299-7c5d11d62e11.png)

When i `tail -F laravel.log` while clicking on "send invoice" i see the whole email in the laravel.log. However i got no error. Any idea what this could be?

**Comment by turbo124** [comment]
@danielgroen could this be linked to your other issue with the app failing to update?

**Comment by danielgroen** [comment]
it might can be the cause of something because when i couldnt get 5.2.19 to work i downgraded to 5.2.11. (this issue).

i also cleared the pending jobs though with php artisan, but when i tried to send a new invoice it 'll still add up at the pending jobs.

**Comment by danielgroen** [comment]
i moved to vanilla invoiceinja so this issue doesn't mind no more
