### ISSUE TITLE
pod/invoiceninja mysqladmin ping timeout at 12 hours

### ISSUE THREAD

**Issue by schroedt** [invoiceninja/dockerfiles#391]
Hi there,

I noticed a hanging init container of `pod/invoiceninja`. That's due to the default of `connection-timeout=43200` (= 12 hours). As the connection-error would be returned after 12 hours of waiting, I do recommend adding a parameter, e.g. `mysqladmin status -h $DB_HOST -P $DB_PORT **--connect-timeout=10**`:

```
kubectl -n invoice-ninja exec -ti pod/invoiceninja-76d84ff655-6jd42 -c wait-db -- sh
~ $ mysqladmin status -h $DB_HOST -P $DB_PORT **--connect-timeout=5**

mysqladmin: connect to server at 'mariadb.db-maria.svc.cluster.local' failed
error: 'Lost connection to MySQL server at 'handshake: reading initial communication packet', system error: 110'
~ $
```

I am using latest Helm chart for Kubernetes:

```
helm repo add invoiceninja https://invoiceninja.github.io/dockerfiles
helm repo update
helm install invoiceninja invoiceninja/invoiceninja --namespace invoice-ninja \
                --set appKey=***\
                --set redis.auth.password=*** \
                --set userEmail=mail@my-example.de \
                --set userPassword=*** \
                --set mariadb.enabled=false \
                --set externalDatabase.host=*** \
                --set externalDatabase.user=*** \
                --set externalDatabase.password=*** \
                --set externalDatabase.database=*** \
                --set externalDatabase.port=***
```

**Comment by schroedt** [comment]
One more finding: I think current implementation cannot run with `istio`, having mTLS `strict`(otherwise: disable TLS in total » bad choise):

- An init countainer is used » before pod-start, before envoy is deployed
- `wait-db` tries connecting to `mariadb` on a istio-enabled pod
- `mariadb` runs within mTLS (strict) because of `server first`protocol
- wait-db has no up and running istio container and will fail 100% because of missing mTLS via envoy.

**Comment by schroedt** [comment]
Login-Page not compatible with `KeePass` and other extensions:

- `User` + `Password` on first page (or first + second)
- Normally `TOTP` is requested on a dedicated second page (if TOTP is configured, otherwise skipped for not irritating users)
- `TOTP` field has a strange name
- `Secret`

**Comment by lwj5** [comment]
Thanks for the suggestion. I agree with the addition of timeout.

For istio I would suggest to add a flag to disable the init container. 

For the last issue please file a new issue in the invoiceninja repo.
