### ISSUE TITLE
Missing 4.5.45 images: Migrating to v5 issue - undefined variable (solved)

### ISSUE THREAD

**Issue by vogelfreiheit** [invoiceninja/dockerfiles#401]
The following issue is present in <4.5.45 and no images are built or available for 4.5.45, only 4.5.44:

https://forum.invoiceninja.com/t/migrating-to-v5-issue-undefined-variable-solved/8277

This is preventing docker users from migrating v4 setups to v5 as of today.

**Comment by turbo124** [comment]
I've just started a build for 4.5.45

**Comment by vogelfreiheit** [comment]
Thank you! :-)
