### ISSUE TITLE
The cron needs to be enabled

### ISSUE THREAD

**Issue by souldessin** [invoiceninja/dockerfiles#403]
**Setup information**
docker-compose

**Describe the bug**
Even though this is a fresh docker compose instance for Invoice Ninja, the cron refuses to start. Other than uncommenting the DB backup cron scripts, the error persists.

I do get the below in the the logs, but nothing will auto-generate.
```bash
app_1     | [2021-10-13T01:23:00+00:00] Execution #7 output:
app_1     | No scheduled commands are ready to run.
```

**To reproduce**
I followed the instructions with only changing the needed info in the docker-compose.yml, env, and later the config/hosts files. Twice this will still show the error saying that cron needs to be enabled.

I have tried checking the cron as root in the container, but I can't even get `rc-status` to run.

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.40
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:02 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:25 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by jurgenhaas** [comment]
Even if the cron backups get enabled in the docker-compose file, the cron doesn't execute because the file `./config/mysql/backup-script` is not marked as executable.
