### ISSUE TITLE
No PDF preview or generated

### ISSUE THREAD

**Issue by souldessin** [invoiceninja/dockerfiles#404]
**Setup information**
docker-compose

**Describe the bug**
Every time that I try to generate a new invoice, while using Firefox on a computer that is on the same network as the server that is hosting the instance, I get a grey preview box that says `PlatformException(error, NoSuchMethodError: self.pdfjsLib is undefined, null, null)`. All that I can find is a bunch of code corrections for fixing JS errors in flutter. I have spun-up the instance with no adjustments to the hosts file and the second time with the IP of the host server and the app_url as the entry. While it is going through a reverse proxy, I also tried accessing it directly via the IP:port and got the same behavior.

I'm just at a loss. It is a container and I followed the current documentation.

**Comment by souldessin** [comment]
I did not and I just reloaded everything to check it and that is working.

Thank you, it wasn't evident at first while reading through everything.

**Comment by yankee14** [comment]
I am having a similar error trying to use snappdf. I am serving invoiceninja from behind a reverse proxy. Everything seems to be working fine except for the pdf generation.

![image](https://user-images.githubusercontent.com/12487802/156964780-8d83983b-6f90-4dfc-8ce6-2f798222a3d4.png)

I have set `TRUSTED_PROXIES=*` in the `env` file as suggested. I also have some other entries:

```
PHANTOMJS_PDF_GENERATION=false
PDF_GENERATOR=snappdf
```
