### ISSUE TITLE
[Helm] Bump tagged version to latest docker version (5.3.29)

### ISSUE THREAD

**Issue by ffaen** [invoiceninja/dockerfiles#405]
Hi,

The chart version of IN (5.2.12) is now behind the current docker build (5.3.29) by quite a distance - is there a reason for this?

I've manually bumped the version on my local IN instance, and so far there are no issues - I'm happy to continue testing it this week to ensure there isn't anything that's gone wrong and then send a PR in to bump the chart tag & application version.

If there's some work that's needed for the chart to fully support the new version, I'm happy to take a crack at it and include it in the PR.

Thanks

**Comment by lwj5** [comment]
Hey there,

There's no additional work needed to support the new version. If the latest IN version feels alright, feel free to make a PR :)
