### ISSUE TITLE
bad practice .env

### ISSUE THREAD

**Issue by freskimo** [invoiceninja/dockerfiles#41]
It is considered bad practice placing the .env file in the repo.
It is better to make an example.env and tell the users to copy this file to .env. This reduces the risk of people pushing their passwords on some repo and to make sure no .env variables are pushed, a gitignore file should exclude any .env file.

https://github.com/invoiceninja/dockerfiles/blob/master/example/.env

**Comment by miend** [comment]
I opened PR #48 to address this, pending approval from @lalop.
