### ISSUE TITLE
can't open /setup, Redirect back to index.html

### ISSUE THREAD

**Issue by HariboApfel** [invoiceninja/dockerfiles#412]
**Setup information**
docker run 

**Describe the bug**
i am unable to open the invoiceninja setup page under web.xxxx.at/setup. It always redirects me back to web.xxxx.at/#/.

**To reproduce**
Setup mariadb.
Setup Invoiceninja:
`name: Create and start invoiceninja container
  docker_container:
    name: invoiceninja
    image: "invoiceninja/invoiceninja"
    pull: yes
    ports:
      - "9000:9000"
    env:
      APP_ENV: "production"
      APP_DEBUG: "false"
      APP_URL: "https://web.{{ user.domain }}"
      APP_KEY: "base64:0x+ch+/CT5e0cEP7UCOLDEAz4CLrBitGVN73yig/zNY"
      APP_CIPHER: "AES-256-CBC"
      DB_TYPE: "mariadb"
      MULTI_DB_ENABLED: "false"
      DB_HOST: "mariadb:3306"
      DB_USERNAME: root
      DB_PASSWORD: password321
      DB_DATABASE: invoiceninja
    volumes:
      - "/opt/invoiceninja/public:/var/www/app/public"
      - "/opt/invoiceninja/storage:/var/www/app/storage"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - invoiceninja`

setup nginx
`name: Create and start container
  docker_container:
    name: nginx
    image: nginx
    pull: yes
    env:
      VIRTUAL_HOST: "{{ (nginx.direct_domain|default(false,true)) | ternary(user.domain + ',' + 'www.' + user.domain, nginx.subdomain|default('web',true) + '.' + user.domain) }}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "{{ (nginx.direct_domain|default(false,true)) | ternary(user.domain + ',' + 'www.' + user.domain, nginx.subdomain|default('web',true) + '.' + user.domain) }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/home/alex/cloudbox/roles/nginx/files/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro"
      - "/opt/invoiceninja/public:/var/www/app/public:ro"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - nginx`

**Expected behavior**
open /setup to setup invoiceninja

**Screenshots/logs**

```
No Errors
```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:57 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:06 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Additional context**

**Comment by lwj5** [comment]
Hi @HariboApfel 

There’s no setup page for the docker version of Invoice Ninja. All the configuration is done through environment variables, which I think you have done. 

You can set the initial username and password in there as well.

**Comment by lwj5** [comment]
Shall close this for now, feel free to reply if you are still facing this issue
