### ISSUE TITLE
Inconsistent port info on docker hub

### ISSUE THREAD

**Issue by Timmmy** [invoiceninja/dockerfiles#413]
**Describe the bug**
Docker hub documentation https://hub.docker.com/r/invoiceninja/invoiceninja/ mentions a default port of 80, but in the example docker command port 9000 is the only mapped port.

Are these used for different purposes or is there an inconsistency here?

**Comment by turbo124** [comment]
The example docs there are quite old, i would suggest following the ReadMe on this repo.

**Comment by Timmmy** [comment]
Thanks @turbo124 .
Scope seems a bit different however, unless I missed it, the repo seems to contain only info about running on docker-compose which uses an env file as opposed to the command line args in docker.

Anyhow, you can figure it out, but it's not so easy for people new to docker.

That being said, port 80 is the answer then.
