### ISSUE TITLE
Container web interface not starting

### ISSUE THREAD

**Issue by Timmmy** [invoiceninja/dockerfiles#414]
Hi all,

I'm unable to get the v5 docker image to do a correct clean install.
Database tables are being created, but I'm only getting empty responses on the web interface. Storage and public folder remain empty but are writeable from the container.

Logs: https://pastebin.com/raw/TbFLbs6A

    docker run -d \
    -v /xxx/invoiceninja-test/public:/var/app/public:rw \
    -v /xxx/invoiceninja-test/storage:/var/app/storage:rw \
    -e APP_ENV='production' \
    -e APP_DEBUG=1 \
    -e APP_URL='http://xxx:9008' \
    -e APP_KEY=base64:xxx \
    -e APP_CIPHER='AES-256-CBC' \
    -e DB_TYPE='mysql' \
    -e DB_STRICT='false' \
    -e DB_HOST='xxx:3307' \
    -e DB_DATABASE='invoiceninja-test' \
    -e DB_USERNAME='ninja-test' \
    -e DB_PASSWORD='xxx' \
    -p '9008:80' \
    --name 'Ninja-Test' \
    invoiceninja/invoiceninja:5.3.33

Any ideas?

Thanks in advance,

Timmmy

(Transfered from forums https://forum.invoiceninja.com/t/container-web-interface-not-starting/9161)

**Comment by lwj5** [comment]
Similar to https://github.com/invoiceninja/dockerfiles/issues/418

**Comment by lwj5** [comment]
Shall close this for now, feel free to reply if you are still facing this issue
