### ISSUE TITLE
Testing db connection in app-entrypoint.sh

### ISSUE THREAD

**Issue by freskimo** [invoiceninja/dockerfiles#42]
I want to open the discussion: 

**why is the db testing mechanism necessary?**

AFAIK It is not the responsibility of the container to check the db connection. Instead the application itself should verify if there is a working db connection. This simplifies the `app-entrypoint.sh` and loses the inaccurate try wait mechanism.

**Comment by lalop** [comment]
The main reason is because I would like to intialize the database on first launch because the first migration can cause timeout via web request... but I didn't did it yet.

**Comment by freskimo** [comment]
This should happen in the application and not on the level of container...
I understand the problem but this is not the right approach. The fix is needed in the `invoiceninja/invoiceninja` git repo and not here.

A solution to the problem would be to split up the queries in chunks and run it in a queue.

**Comment by lalop** [comment]
What is wrong in doing this at the level container ?

**Comment by freskimo** [comment]
You trying to fix a problem by solving it on a different location. This has a bad smell.
Other people hosting invoice ninja w/o docker have the same problem and this should be addressed in the application itself not on another level.

It is not wrong but docker files & entrypoints should stay as simple/clean as possible w/o too much extras. Offcourse you can add db imports, db backups, healthchecks... but this adds up to the startup time of the container e.g. when running multiple instances of the invoiceninja container with loadbalancing and you move all instances to a new location, then they first need to make a db call to see if there actually is a db. This process should happen as fast as possible.

**In my understanding the docker way is to spin up a container as fast as possible**

**Comment by freskimo** [comment]
The docker way would be the following:
initially
`docker run --rm invoiceninja/invoiceninja php artisan db:seed --force`
this results in a db seed and when this is finished the container will be removed, then:
`docker run invoiceninja/invoiceninja`
to run the app.

I am working on a better readme and will post it soon.

**Comment by freskimo** [comment]
Is running db:seed sufficient? Or should migrate also be run?

**Comment by freskimo** [comment]
Are these the commands that need to be run?
```
php artisan optimize --force
php artisan migrate --force
php artisan db:seed --force
```

**Comment by lalop** [comment]
I think this is all, and for the update 
```
php artisan optimize --force
php artisan migrate
php artisan db:seed --class=UpdateSeeder
```
according to http://docs.invoiceninja.com/en/latest/update.html

**Comment by hillelcoren** [comment]
Yes, those are the commands needed to initially setup the app. 

You can combine the last two: `php artisan migrate --seed`

**Comment by lalop** [comment]
AFAIK the global seed command should run only once

**Comment by lalop** [comment]
@hillelcoren, do you think adding an install and update command that groups all the needed one for installing and updating could be a good thing ?

**Comment by hillelcoren** [comment]
It seems like a good idea to me...

**Comment by lalop** [comment]
this is closed by https://github.com/invoiceninja/dockerfiles/commit/c27b04b63ac2b50e9ffe4bb8444af343626fef2e
@hillelcoren I will try to make a pr to invoiceninja project... asap
