### ISSUE TITLE
mysql5 is using too much ram

### ISSUE THREAD

**Issue by Azertooth** [invoiceninja/dockerfiles#424]
**Setup information**

docker-compose

**Describe the bug**
Recently the mysql5 container started using too much ram (~16gb), from the usual ~227mb
Already tried all the older images down to 5.7.31, on a fresh container (without invoiceninja data) to no avail. I noted that with mysql8 images this is not happening so I want to switch to mysql8 or mariadb, would that be a problem for invoiceninja?

**Comment by turbo124** [comment]
@Azertooth 

shouldn't be a problem to use mysql8 or mariadb.. we use MariaDB in production .
