### ISSUE TITLE
Username and password escaping breaks deploys

### ISSUE THREAD

**Issue by VeselaHouba** [invoiceninja/dockerfiles#427]
**Setup information**
docker-compose (caprover actually)
`INVOICENINJA_VERSION=5.3.45`

**Describe the bug**
Username and password escaping introduced in https://github.com/invoiceninja/dockerfiles/pull/419 breaks new installations. Username and password is actually wrapped in `" "` symbols during creation, so the env values don't work.

**To reproduce**
1. Start environment using docker-compose using some `IN_USER_EMAIL` and `IN_PASSWORD`
2. User doesn't work via web UI. (401 code)
3. You can login by wrapping the username and password in `"`

**Expected behavior**
User is able to login

**Screenshots/logs**
You can try to create some user by hand using scripts after and before #419 and see results in db

```
/var/www/app # export IN_USER_EMAIL=abc@cde.ef
/var/www/app # export IN_PASSWORD=somesecretpassword
/var/www/app # curl -s https://raw.githubusercontent.com/invoiceninja/dockerfiles/5.3.45/alpine/5/rootfs/docker-entrypoint-init.d/10-init-in.sh > /docker-entrypoint
-init.d/10-init-in.sh
/var/www/app # /docker-entrypoint-init.d/10-init-in.sh
Running DatabaseSeeder
Skipping: already run
Database seeding completed successfully.
Thu, 13 Jan 2022 11:56:10 +0000 Create Single Account...
```
```
MariaDB [ninja]> select email from users;
+--------------+
| email        |
+--------------+
| "abc@cde.ef" |
+--------------+
1 row in set (0.002 sec)

```
older working version - 5.3.34
```
/var/www/app # curl -s https://raw.githubusercontent.com/invoiceninja/dockerfiles/5.3.34/alpine/5/rootfs/docker-entrypoint-init.d/10-init-in.sh > /docker-entrypoint
-init.d/10-init-in.sh
/var/www/app # /docker-entrypoint-init.d/10-init-in.sh
Running DatabaseSeeder
Skipping: already run
Database seeding completed successfully.
Thu, 13 Jan 2022 11:58:30 +0000 Create Single Account...
```
```
MariaDB [ninja]> select email from users;
+--------------+
| email        |
+--------------+
| "abc@cde.ef" |
| abc@cde.ef   |
+--------------+
2 rows in set (0.002 sec)

```

**Comment by turbo124** [comment]
@VeselaHouba 

Thanks for this, are you able to PR a fix?

**Comment by VeselaHouba** [comment]
Best I can do for quick fix is PR with reverted changes, but the original issue https://github.com/invoiceninja/dockerfiles/issues/415 needs to be reopened then.

**Comment by turbo124** [comment]
@VeselaHouba that works for me, i think we can consider special characters in a password an edge case for the initial setup. This can always be changed later on when the app in running.
