### ISSUE TITLE
snappdf , chromium-browser can't create pdf's

### ISSUE THREAD

**Issue by dagofan** [invoiceninja/dockerfiles#434]
[0305/204545.629098:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
[0305/204545.629558:WARNING:dns_config_service_posix.cc(342)] Failed to read DnsConfig.
Received signal 11 SEGV_ACCERR 0029e6e01000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Comment by turbo124** [comment]
@dagofan not sure on this one, i cannot recreate on any of our test platforms.

**Comment by dagofan** [comment]
@turb124 The setup is Oracle Cloud , ARM , Oracle Linux, private VPN.  
The same setup on my PC or a VM in Proxmox works immediately.
The probability is very high that it has something to do with the cloud server.

**Comment by turbo124** [comment]
@dagofan if you are able to isolate the issue in the VM, please let us know.
