### ISSUE TITLE
db container fails creating: bind mount failed

### ISSUE THREAD

**Issue by wannesrams** [invoiceninja/dockerfiles#435]
**Setup information**

docker-compose 

**Describe the bug**
When running docker-compose -f docker-compose.yml up -d the creation of the db container fails with the following message

Creating network "invoiceninja5_invoiceninja" with the default driver
Creating invoiceninja5_db_1 ... error

ERROR: for invoiceninja5_db_1  Cannot start service db: Bind mount failed: '/volume1/docker/invoiceninja5/docker/mysql/data' does not exists

ERROR: for db  Cannot start service db: Bind mount failed: '/volume1/docker/invoiceninja5/docker/mysql/data' does not exists
ERROR: Encountered errors while bringing up the project.

**To reproduce**

**Expected behavior**

**Screenshots/logs**

```
Any Error that sucks
```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
(paste your output here)
```

- Output of `helm version`:
```
(paste your output here)
```
- Output of `kubectl version`:
```
(paste your output here)
```

**Additional context**

**Comment by turbo124** [comment]
Are you setting the correct user/group permissions prior to starting the containers?

**Comment by wannesrams** [comment]
Hey , thanks for answering, I got past it, the mysql and mysql/data folders do not exist after cloning the repo. I created them ( and also /mysql/bak in case you enable auto backups) and all works fine thanks. I think it would be great to add these folders to the repo by default

**Comment by turbo124** [comment]
I think this would have been a permissions issue preventing the creation of the subdirectories when the container was building for the first time. We do stub the public and storage directories, but unless the permissions are set the container will fall over.
