### ISSUE TITLE
Will there be another v4 Docker release?

### ISSUE THREAD

**Issue by MegaphoneJon** [invoiceninja/dockerfiles#438]
I see that there are migration improvements in v4.50, but the latest release on Docker Hub is 4.46.  Are there plans for another v4 release?

**Comment by turbo124** [comment]
I've tagged this. I'm unsure if it will build due to 7.4 dependencies :crossed_fingers:

**Comment by turbo124** [comment]
@MegaphoneJon this won't work.

The image will not build against PHP 7.4.

**Comment by oliverpool** [comment]
@turbo124 so I guess the answer is no? :disappointed:

**Comment by oliverpool** [comment]
Latest docker image v4: 4.5.46
Latest release v4: [v4.5.50](https://github.com/invoiceninja/invoiceninja/releases/tag/v4.5.50)

**Comment by 2color** [comment]
I tried the following images in an attempt to run Invoice ninja v4:
- `invoiceninja/invoiceninja:4.5.46-p2`(php 7.3)
-  `invoiceninja/invoiceninja:4.5.46` (php 7.2.34)

Unfortunately, it's not possible to run either successfully 
With `invoiceninja/invoiceninja:4.5.46` (php 7.2.34),  I get the `dockerfiles-app-1  | Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0". You are running 7.2.34. in /var/www/app/vendor/composer/platform_check.php on line 24` errors 

With `invoiceninja/invoiceninja:4.5.46` (php 7.2.34), I get the undefined constants error: 
```
dockerfiles-app-1  |   Use of undefined constant TOKEN_BILLING_ALWAYS - assumed 'TOKEN_BILLING_ALW
dockerfiles-app-1  |   AYS' (this will throw an Error in a future version of PHP)
```

As it stands, I am not aware of a way to run v4. I think it would be a good idea to document this at the very least to save users time. 

Thoughts @turbo124?

**Comment by oliverpool** [comment]
I am running v4.5.35 via docker without issues (on a local network to reduce exposure).

**Comment by 2color** [comment]
> I am running v4.5.35 via docker without issues (on a local network to reduce exposure).

Thanks @oliverpool. 

I was able to get it running with the [`alpine-4.5.35` tag](https://hub.docker.com/layers/invoiceninja/invoiceninja/alpine-4.5.35/images/sha256-3ca474af82960c08505fc97e5a0b9b87fbc43b07f74160a2849e60b377f7f1d8?context=explore)

**Comment by Cronus89** [comment]
What are the suggested steps to migrate to v5, with an outdated 4.5.35?
