### ISSUE TITLE
Can`t log in

### ISSUE THREAD

**Issue by VentumPhoenix** [invoiceninja/dockerfiles#440]
Hello, 

I hosted invoiceninja myself via Docker Compose. The problem I have is that I can't log in and the only email in the database is [admin@example.com](mailto:admin@example.com). I couldn't find a default password. I've also reinstalled it several times, but can never create a user at the beginning. 
Can I create a user via the console or in the database?
If information is still missing, please let me know.

Thanks in advanced.

**Comment by turbo124** [comment]
If you inspect the env file you'll see the default username / password combination
