### ISSUE TITLE
Email not work

### ISSUE THREAD

**Issue by TheDomcrafter** [invoiceninja/dockerfiles#444]
Hello community,

I did my installation via Docker. Unfortunately, I now have the problem that no emails can be sent. There is nothing under /storage/logs/laravel.log .
My env for the email settings looks like this:

MAIL_MAILER=smtp
MAIL_HOST=mail.mydomain.de
MAIL_PORT=465
MAIL_USERNAME=admin@mydomain.de
MAIL_PASSWORD="Password"
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS=admin@mydomain.de
MAIL_FROM_NAME="Admin Mydomain"

Are my settings correct and also the quotes?
Do I also have to assign the ports to the container or not?

If information is still missing, please let me know.
Thanks in advanced.

**Comment by mattchis** [comment]
Same issue here... Not sure why this was closed as completed....
So I have done a little digging and noticed that the SMTP relay is rejecting because of this issue:
```
SMTP connection from [xxx.xxx.xxx.xxx]:49974 (TCP/IP connection count = 1)
no host name found for IP address xxx.xxx.xxx.xxx
no host name found for IP address xxx.xxx.xxx.xxx
SMTP connection from [xxx.xxx.xxx.xxx]:49974 lost D=0s
```
I am not sure if the laravel is sending the hostname when it is connecting via smtp.

**Comment by turbo124** [comment]
If you are using google relay, you may find this useful:

https://forum.invoiceninja.com/t/emails-not-sending-yet-another-thread-v5-5-55/12401/8
