### ISSUE TITLE
Internal DB not created in Docker Container

### ISSUE THREAD

**Issue by moorsey** [invoiceninja/dockerfiles#446]
Am I right in assuming the main docker container should create an internal DB? https://hub.docker.com/r/invoiceninja/invoiceninja/

`DB_HOST` is shown as "localhost", so guessing that's right.

On creation however I just get a repeat of:

```
2022-06-14T15:43:17Z [INFO] [Entrypoint]: Initialising Invoice Ninja...,
Configuration cache cleared!,
Configuration cached successfully!,
Configuration cache cleared!,
Configuration cached successfully!,
Route cache cleared!,
Routes cached successfully!,
les cached successfully!,
,
In Connection.php line 712:,
                                                                               ,
  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from inform  ,
  ation_schema.tables where table_schema = ninja and table_name = accounts an  ,
  d table_type = 'BASE TABLE')                                                 ,
                                                                               ,
,
In Connector.php line 70:,
                                                    ,
  SQLSTATE[HY000] [2002] No such file or directory  ,
                                                    ,
,
2022-06-14T15:43:18Z [ERROR] [Entrypoint]: Error connecting to DB,
```

Created using:

```
docker run -d \
--name=invoiceninja \
--restart unless-stopped \
--net=proxy \
-v /dockerdata/invoiceninja/public:/var/app/public \
-v /dockerdata/invoiceninja/storage:/var/app/storage \
-e APP_ENV='production' \
-e APP_DEBUG=0 \
-e APP_URL='https://invoiceninja.blah.com' \
-e APP_KEY='blah' \
-e APP_CIPHER='AES-256-CBC' \
-e DB_TYPE='mysql' \
-e DB_STRICT='false' \
-e DB_HOST='localhost' \
-e DB_DATABASE='ninja' \
-e DB_USERNAME='ninja' \
-e DB_PASSWORD='ninja' \
invoiceninja/invoiceninja
```

Many thanks!

**Comment by MarkJaroski** [comment]
Are you using the snap version of docker by any chance?

**Comment by MarkJaroski** [comment]
I ask because I had the same issue, and after debugging I realized that the Ubuntu Snap has ICC (Inter-Container Communications) disabled by default.

For my purposes it's probably better to run the apt-based docker anyway, so I switched, and all was well.

**Comment by moorsey** [comment]
Hi @MarkJaroski 

I am running on Open Media Vault, pretty sure this is not snap

Got this running through docker-compose in the end

Thanks for the reply

**Comment by notflip** [comment]
@moorsey I'm having the same type of issue, did you use the default docker-compose file provided?

**Comment by moorsey** [comment]
@notflip yes, basically, use the default files provided, I had obviously come across some incorrect info.  If you follow the info on the main page of this repo, including setting the file permissions etc, you should be good to go

**Comment by dwishaventures** [comment]
> @moorsey I'm having the same type of issue, did you use the default docker-compose file provided?

What issue you are having ? I had to modify a few things and remove a lot of things to run inside a docker with Traefik as reverse proxy.

**Comment by NanoSector** [comment]
This happens when you use `localhost` as database host. Switch to `127.0.0.1` instead. Apparently localhost assumes a UNIX socket instead of a TCP connection.
