### ISSUE TITLE
Errors and problems when deploying in non-root path (with traefik2)

### ISSUE THREAD

**Issue by TimmThaler** [invoiceninja/dockerfiles#449]
Hello there,

I'm having a nasty little problem deploying Invoice Ninja via docker in a non-root path of the URL (`domain.com/invoiceninja`) using the in this repository provided docker-compose file in combination with traefik2 as my reverse proxy.

The "bug" is that the new instance of IN is not accessible via the APP_URL in the env file (`domain.com/invoiceninja`).
First, there are several js files thats path seems to be hardcoded, i. e. the browser looks for `/vendor/livewire/...` or `/js/...` which does not exist.
Second, I tried "optimizing" the standard nginx config file from this repo using the information given [here](https://forum.invoiceninja.com/t/using-nginx-to-serve-from-non-root-path/3919/9). Of course I edited the paths to fit my needs, but it did not work either. To me it seems that the APP_URL is not used as a base url which would be really good.

The logs show that (of course) the sub path `/invoiceninja` does not exists on my file system but even when I managed to get nginx looking in the right directory for the needed files, some libraries as shown above do not load.

**To reproduce**
1. Deploy the stack with docker compose.
2. Add label for traefik2: `"traefik.http.routers.invoiceninja.rule=Host(`domain.com`) && PathPrefix(`/invoiceninja`)"`
3. Open browser to `domain.com/invoiceninja`
4. See nothing or half loaded login page with no possibility to log in because of wrong urls of assets

**Expected behavior**
Edit the env file and add the APP_URL. Load up the stack and go without path or url problems.

I'd be happy, if someone could help me with this. Accessing my deployment locally without traefik via the local IP and in root path works right out of the box.

Cheers :)

**Comment by turbo124** [comment]
@TimmThaler 

Installing the app in a non root path is an issue not just with docker but also regular installations.

The issue as you've mentioned is to do with paths. In this case, you would need to add a configuration in config/livewire.php

```
    /*
    |--------------------------------------------------------------------------
    | Livewire Assets URL
    |--------------------------------------------------------------------------
    |
    | This value sets the path to Livewire JavaScript assets, for cases where
    | your app's domain root is not the correct path. By default, Livewire
    | will load its JavaScript assets from the app's "relative root".
    |
    | Examples: "/assets", "myurl.com/app".
    |
    */

    'asset_url' => null,

```

The asset_url will be the full path (ie /invoiceninja)

The suggested workaround is to simply install the app on a subdomain ie billing.domain.com this ends up being easier to deal with.

**Comment by TimmThaler** [comment]
Hi turbo124,

thank you!
Yes, that was the impression I got searching the web… But I don’t want to give up 😄 

Sure, a separate sub domain would be the simplest solution, but unfortunately I don’t have one in my setup.

I will try and edit the asset url and post my results as I have some :)

**Comment by TimmThaler** [comment]
Hello there!

Please wait to let me take my time and test before you close the issue. Because my problem is not fixed at all!

The most important question is: Where do I find the mentioned `config/livewire.php`? There is no such file `livewire.php` in any of the directories created by the docker container. And in the GitHub repos there doesn't exist it either...

Any ideas? Somebody? ;)
And no, it's _not_ the `index.php`.
