### ISSUE TITLE
app-entrypoint.sh vs entrypoint.sh

### ISSUE THREAD

**Issue by miend** [invoiceninja/dockerfiles#45]
Is there any reason why the `entrypoint.sh` [referenced in the Dockerfile](https://github.com/invoiceninja/dockerfiles/blob/master/Dockerfile#L73) is named differently from the `app-entrypoint.sh` in the repo? Copying in a file of the same name would look cleaner.

**Comment by lalop** [comment]
No real good reason.
You may be right. Di you want to make a pr ?

**Comment by miend** [comment]
Done.

**Comment by lalop** [comment]
thank you
