### ISSUE TITLE
Docker-Selfhosted grey screen

### ISSUE THREAD

**Issue by Photograaf15** [invoiceninja/dockerfiles#451]
Best,
Since 2 days i have a serious issue with invoiceninja.
When i go to my invoicing URL the only thing i get is the 3 dots that you see its loading, after +/- 10 seconds the background of the page goes to grey and after that nothing happens!

What did i try?
Compleet fresh re-install, updating/downgrading images
Requesting new SSL certificates from cloudflare.
removing browser caching, tried also multiple different browsers.

I dont get any errors in the container logs and or in /docker/app/storage/logs.
The browser console gives 3 errors but on google i dont get a helpfull result!

![image](https://user-images.githubusercontent.com/5887440/180008017-1570be2e-fbde-4640-8d6c-b640534b5b71.png)

I run this on a 64-bit Ubuntu server with 16GB ram and fully on a SSD.

The permissions of the whole folder are set like the manual tells me to do
user 1500:1500
perm: 755

Any sugestions i can try to fix this issue?

**Comment by barrelltitor** [comment]
Hey, did you manage to fix this? If so how?
