### ISSUE TITLE
`TRUSTED_PROXIES` is not in `env`

### ISSUE THREAD

**Issue by almereyda** [invoiceninja/dockerfiles#454]
**Setup information**
docker-compose aab280dcc1b3bfc4907705ddab0dbd25dc0ba461

**Describe the bug**
This repository does not target the common use case of running the application behind a reverse proxy. The `TRUSTED_PROXY` setting remains undocumented here, and is also not part of the example `env`, not even commented.

**To reproduce**

1. Deploy the application, try to send an email and see the PDF preview broken there. Technically this is known as https://github.com/invoiceninja/invoiceninja/issues/6200  
    Nowadays in Firefox this reads  
    ```  
    Blocked loading mixed active content “http://business.example.com/client/invoice/something/download_pdf”  
    ```
    - PDF preview will not be broken for invoice editing pages

**Expected behavior**
The application previews the PDF in the email sending dialogue.

That is to say, this repository contains information within the README and the example `env` that suggests to use the `TRUSTED_PROXY` to configure the frontend. `*` can be a useful setting here, in case of Docker setups.

- https://github.com/invoiceninja/invoiceninja/issues/7551#issuecomment-1154989785
- https://github.com/invoiceninja/dockerfiles/issues/67#issuecomment-366936696

**Screenshots/logs**
There's a spinner, instead of the document.

**Comment by Psycho0verload** [comment]
I had the same problem. Had also found out about the proxy. I have integrated it into my current merge. Now the option is with in the env file.

**Comment by turbo124** [comment]
#453

**Comment by almereyda** [comment]
Cool, nice. Thanks!
