### ISSUE TITLE
The entire thing doesn't work lol

### ISSUE THREAD

**Issue by jordanhinks** [invoiceninja/dockerfiles#456]
Simply said, the entire guide provided when copied and pasted exactly as stated and advised to change some values - and it doesn't work, terrible.

**Comment by turbo124** [comment]
I took this at face value and decided to make a video showing me following the steps in the documentation. You may want to advise where you strayed from the exact steps.

If the docs need improving I'm certainly happy to make any adjustments...

https://www.youtube.com/watch?v=kWBFGVituPI

**Comment by jordanhinks** [comment]
Thank you for going the extra mile with this. I've tested it again and made a change to the docker network and can confirm it now works.
