### ISSUE TITLE
[Suggestion] Add mail port to docker-compose.yml

### ISSUE THREAD

**Issue by jordanhinks** [invoiceninja/dockerfiles#457]
Very small addition, include the below under docker-compose.yml, this should be placed under ports for nginx server:

```
# Specify port based on smtp server used, example: 587 for Gmail.
# - "587:587"
```

The reason for this is because otherwise emails are not able to be sent.

**Comment by dleidert** [comment]
Why would you have to add port 587 for sending mail? That port is used by the mail server, not by your Invoice Ninja instance. Even if any of the containers would need to talk to each other on port 587, they share the same network and reach each other within this network.
