### ISSUE TITLE
in.localhost vs in5.test, why are they both used?

### ISSUE THREAD

**Issue by notflip** [invoiceninja/dockerfiles#458]
Can anyone tell me the difference between references to in5.test in the hosts, and in.localhost in the docker-compose file?

**Comment by turbo124** [comment]
These are just placeholders

**Comment by notflip** [comment]
But shouldn't they be the same url? I understand they are placeholders, but why 2 different one's? In a real application, wouldn't these url's be the same for it to work?

**Comment by moda20** [comment]
same question here, this setup is extremely confusing. laravel and nginx have the esiest integration and this is not that.
