### ISSUE TITLE
Docker run doesn't work. MySQL Connection Refused

### ISSUE THREAD

**Issue by silver0a1** [invoiceninja/dockerfiles#46]
Apertures-iMac:example apsec$ docker run -e APP_ENV='production' -e APP_DEBUG=0 -e APP_URL='http://ninja.dev' -e APP_KEY='SomeRandomStringSomeRandomString' -e APP_CIPHER='AES-256-CBC' -e DB_TYPE='mysql' -e DB_STRICT='false' -e DB_HOST='localhost' -e DB_DATABASE='ninja' -e DB_USERNAME='ninja' -e DB_PASSWORD=‘ninja’ -p '80:80' invoiceninja/invoiceninja
MySQL Connection Error: SQLSTATE[HY000] [2002] No such file or directory
MySQL Connection Error: SQLSTATE[HY000] [2002] No such file or directory
MySQL Connection Error: SQLSTATE[HY000] [2002] No such file or directory
MySQL Connection Error: SQLSTATE[HY000] [2002] No such file or directory
MySQL Connection Error: SQLSTATE[HY000] [2002] No such file or directory

**Comment by lalop** [comment]
you pass localhost as host but for the container localhost is itself so it can't connect to your database

**Comment by miend** [comment]
@silver0a1 The easiest way to start running the Docker image provided here would be to copy the `docker-compose.yml`, `nginx.conf`, and `.env` files from the `/example` directory to the repository root directory, and then using Docker Compose (`docker-compose up`) to run them. This will provide containers for the app, mysql, nginx webserver, and cron tasks that are already linked to each other for networking purposes.

If you don't want to go this route, there are ways to have the Docker container connect to the host machine (at `localhost`) if you want to. You can find network settings for docker containers in the [Docker run reference here](https://docs.docker.com/engine/reference/run/#/network-settings). Pay particulate attention to the following options:

- `docker run --network="bridge"` will provide a network bridge on which the container and host machine will both have IP addresses, allowing them to communicate.
- `docker run --network="host"` will use the host's network stack inside the container. This means that `localhost` inside the container will not refer to the container itself as it usually does, but to the host machine.
