### ISSUE TITLE
Despite Setting Debug Mode to false, InvoiceNinja Remains in Developer Mode...

### ISSUE THREAD

**Issue by Freddie-GER** [invoiceninja/dockerfiles#461]
How do I turn this off???

**Comment by turbo124** [comment]
in the env file in the dockerfiles repo

set 

APP_DEBUG=false

**Comment by Freddie-GER** [comment]
Hi David, as described in the request - that was my first thought as welI, so i changed it to false, but Invoiceninja stayed in Dev mode :-(. Also stayed in dev mode after container restart and after a complete machine restart. 

Thank you for your help, Frederike

**Comment by turbo124** [comment]
@Freddie-GER 

I am able to toggle debug mode by change the APP_DEBUG var in the env file. and the down/uping the container.

Just to confirm, the env file i am referencing is the on in the dockerfiles repo here:

https://github.com/invoiceninja/dockerfiles/blob/master/env

**Comment by Freddie-GER** [comment]
Yes, that‘s the one.
Curious.
Well I had kill the whole install anyways cos the embedded mariadb in the build for some reason superceded my existing one that serves my nextcloud, so I‘ll try a clean new install with that Debug Variable set to false from the getgo.

… And try to figure out how to only have one mariadb instance serving both nextcloud and invoiceninja ;)

Thanks again!

Von meinem iPad gesendet
