### ISSUE TITLE
appKey in Kubernetes/Helm

### ISSUE THREAD

**Issue by xeruf** [invoiceninja/dockerfiles#465]
Do I have to pass an appkey?
I generated a b64encoded key with 64 bytes and now get:
> Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm.

Will it generate one itself if I don't pass it?

**Comment by xeruf** [comment]
yep, seems to auto-generate

**Comment by lwj5** [comment]
Please see the readme, it's clearly stated here https://github.com/invoiceninja/dockerfiles/tree/master/charts/invoiceninja#invoice-ninja-container-parameters

Nonetheless, you should provide a value.
