### ISSUE TITLE
  Invoice Ninja apps SQLSTATE[HY000] [2002] Connection refused  errors

### ISSUE THREAD

**Issue by aloychan** [invoiceninja/dockerfiles#473]
The invoice ninja apps  is throwing these error when trying to connect to the db.  
I have tried numerous time following the steps but I cannot seem to get it running.
Any help here would be appreciated. 

In Connector.php line 70:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             
2022-11-18T[00:34:10](https://www.youtube.com/watch?v=xo6a3KtLC2g&t=2050s)Z [ERROR] [Entrypoint]: Error connecting to DB
2022-11-18T[00:34:28](https://www.youtube.com/watch?v=xo6a3KtLC2g&t=2068s)Z [INFO] [Entrypoint]: Initialising Invoice Ninja...
   INFO  Configuration cached successfully.  
   INFO  Caching the framework bootstrap files.  
  config .......................................................... 143ms DONE
  routes .......................................................... 335ms DONE
In Connection.php line 760:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user 'ninja'@'%' to database 'ninj  
  a' (SQL: select * from information_schema.tables where table_schema = ninja  
   and table_name = accounts and table_type = 'BASE TABLE')                    
                                                                               
In Connector.php line 70:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user 'ninja'@'%' to database 'ninj  
  a'                                                                           
                                                                               
2022-11-18T[00:34:40](https://www.youtube.com/watch?v=xo6a3KtLC2g&t=2080s)Z [ERROR] [Entrypoint]: Error connecting to DB
2022-11-18T[00:34:56](https://www.youtube.com/watch?v=xo6a3KtLC2g&t=2096s)Z [INFO] [Entrypoint]: Initialising Invoice Ninja...
   INFO  Configuration cached successfully.

**Comment by turbo124** [comment]
```
SQLSTATE[HY000] [1044] Access denied for user 'ninja'@'%' to database 'ninj
a'
```

this is the issue here.

**Comment by aloychan** [comment]
@turbo124 any way to address the issue. I have been trying all night and I cant seem to get it working. Tyvm

**Comment by navanjr** [comment]
Can you explain how this occurred when following the steps described in the README? 
I am seeing similar errors when deploying to a production environment.
`app` and `db` services are restarting...
```db_1      | 2023-03-10 18:34:59+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.32-1.el8 started.
db_1      | 2023-03-10 18:34:59+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1      | 2023-03-10 18:34:59+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.32-1.el8 started.
app_1     | 
app_1     | In Connection.php line 760:
app_1     |                                                                                
app_1     |   SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_s  
app_1     |   chema.tables where table_schema = ninja and table_name = accounts and table  
app_1     |   _type = 'BASE TABLE')                                                        
app_1     |                                                                                
app_1     | 
app_1     | In Connector.php line 70:
app_1     |                                              
app_1     |   SQLSTATE[HY000] [2002] Connection refused  
app_1     |                                              
app_1     | 
app_1     | 2023-03-10T18:34:59Z [ERROR] [Entrypoint]: Error connecting to DB
db_1      | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
invoiceninja_app_1 exited with code 1
db_1      | 2023-03-10T18:35:00.699846Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
db_1      | 2023-03-10T18:35:00.724717Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.32) starting as process 1
db_1      | 2023-03-10T18:35:00.871282Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
```

**Comment by turbo124** [comment]
It looks like the mysql container has not started yet. The app continues to ping the mysql service until it comes up.
