### ISSUE TITLE
Database not connecting to app container

### ISSUE THREAD

**Issue by magicman32** [invoiceninja/dockerfiles#487]
**Setup information**

docker compose up -d

**Describe the bug**
Database is not connecting

**To reproduce**
1. Go to '...portainer to check logs
2. Click on '....database container
5. 
![database-container-ninja](https://user-images.githubusercontent.com/15340872/212069467-86706cdc-24f9-4e43-8e4a-f0dff92b396a.png)

6. Click on.....app container
7. Click on logs
8. see error
9. 
![app-container-ninja](https://user-images.githubusercontent.com/15340872/212069515-408c81bb-0ca9-4976-b315-1929a8417927.png)

**Expected behavior**
Database to connect.......

docker-compose.yml (db section)
db:
    image: mysql:8

    ports:
      - "3305:3306"
    restart: always
    env_file: env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated

env (file

# DB connection
DB_HOST=db
DB_PORT=3306
DB_DATABASE=ninja
DB_USERNAME=ninja
DB_PASSWORD=ninja

is db_port in env file meant to match 3305 in docker compose

Sorry, this is my first time doing one of these

**Comment by Xenion1987** [comment]
Please post your complete `docker-compose.yml` file.
I know this behavior while I was testing different networks within the `docker-compose.yml` file.

You could also try to resolve the database DNS name by yourself by executing

```sh
docker compose exec app ping -c1 db
```

As long as there is no error while trying to resolve the hostname, the network config should be OK.

**Comment by magicman32** [comment]
its fixed now it was a file permissions I overlooked on project page

**Comment by Xenion1987** [comment]
@turbo124 
Issue can be closed
