### ISSUE TITLE
Add two php extensions for PostgreSQL support

### ISSUE THREAD

**Issue by solairen** [invoiceninja/dockerfiles#491]
Hi,

those two extensions allow running Invoice-Ninja with PostgreSQL:

- pdo_pgsql
- pgsql

in here `alpine\5\Dockerfile`:

```Dockerfile
RUN install-php-extensions \
    bcmath \
    exif \
    gd \
    gmp \
    mysqli \
    opcache \
    pdo_mysql \
    zip \
    pdo_pgsql \
    pgsql \
    @composer \
    && rm /usr/local/bin/install-php-extensions
```

This ticket is related with [PostgreSQL support](https://forum.invoiceninja.com/t/postgresql-support/12431/2)

**Comment by turbo124** [comment]
@solairen are you able to PR this please?

**Comment by solairen** [comment]
@turbo124 yes. Today evening or tomorrow I will make PR.

**Comment by solairen** [comment]
@turbo124 I created a PR

**Comment by turbo124** [comment]
Thanks!
