### ISSUE TITLE
Emails worked in Docker setup with google's smtp-relay. After 2 upgrades, it's not working anymore (error code 421)

### ISSUE THREAD

**Issue by jon91** [invoiceninja/dockerfiles#492]
**Setup information**
docker-compose

**Describe the bug**
Initially installed and configured around July of 2022 with version 5.5.2.
smtp-relay was used as mailer, with _no_ auth, but limited to the IP of the server.
Working great for months and no issues.
Upgraded to 5.5.45 in December, and emails stopped coming through. Figured it was a bug, so I emailed them manually.
With latest release, 5.5.63, still same issue.

#### System failed to email invoice xxxx
`Expected response code "250" but got code "421", with message "421 4.7.0 Try again later, closing connection. (EHLO) xxx-xxxxxxxxxxxxxxxxxxxxxxxxxx - gsmtp".`

**To reproduce**
1. Go to invoice
2. Click send

**Expected behavior**
should send email

```
System failed to email invoice xxxx
Expected response code "250" but got code "421", with message "421 4.7.0 Try again later, closing connection. (EHLO) xxx-xxxxxxxxxxxxxxxxxxxxxxxxxx - gsmtp".
```

![image](https://user-images.githubusercontent.com/2285841/215121486-c28f470a-add9-4b2e-9c77-f8318fb40915.png)

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:32:52 2023
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:31:11 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by turbo124** [comment]
It looks like you are connecting fine, the 421 may indicate gmail is throttling you.

**Comment by jon91** [comment]
Gmail has a 10,000/day limit on smtp-relay emails. I haven't sent that many in 3 years.

**Comment by jon91** [comment]
After 2 upgrades, system sends them fine. Don't know what caused and/or fixed the issue
