### ISSUE TITLE
new react app fails with 404 errors

### ISSUE THREAD

**Issue by paulwer** [invoiceninja/dockerfiles#495]
@turbo124 after a pull of latest docker image, i wanted to try the new react app.
This fails, due to missing files / not published files from the server. (i get in each case a 404 error)

What is mightly wrong configured on my side?

How do I revert the view back to the flutter version?

**Comment by turbo124** [comment]
@paulwer 

I'll look into this, you'll want to exec into the docker container and run this SQL

UPDATE accounts set_react_as_default_ap = 0;

**Comment by paulwer** [comment]
![Unbenannt](https://user-images.githubusercontent.com/52678724/217791830-3d7749a6-e049-470f-adb1-8a0e1d28101a.png)

**Comment by turbo124** [comment]
this should now be resolved in 5.5.70

**Comment by paulwer** [comment]
@turbo124 still the same issue :(

**Comment by paulwer** [comment]
any help needed here?

**Comment by turbo124** [comment]
@paulwer 

I am planning on looping back onto this tomorrow. unsure why the builds are failing but the react app is a priority for us.

**Comment by turbo124** [comment]
@paulwer I have tagged 5.5.79, I believe the react app should be fixed now.

**Comment by paulwer** [comment]
Its working, thanks for your working on this.
