### ISSUE TITLE
/var/www/app/docker-backup-storage/ not found on restart

### ISSUE THREAD

**Issue by yinshanyang** [invoiceninja/dockerfiles#5]
steps to replicate:

```
docker-compose up
*kill the process*
docker-compose up
```

which will yield this error:

```
app_1  | ls: cannot access /var/www/app/docker-backup-storage/: No such file or directory
invoiceninja_app_1 exited with code 2
```

the work around I had was to run `docker-compose rm app` and then run `docker-compose up` again.

**Comment by lalop** [comment]
I did it directly online so we have to wait for docker hub to rebuild this image but the new image should fix this issue

**Comment by yinshanyang** [comment]
okay, I think this fix introduces another set of ownership issues…

![screen shot 2016-04-20 at 3 52 28 pm](https://cloud.githubusercontent.com/assets/499829/14677030/1f5f8e62-0710-11e6-8586-11db74a56845.png)

**Comment by lalop** [comment]
hummm... I see.
Just send a new build

**Comment by yinshanyang** [comment]
just did a quick check, works great now, cheers

**Comment by lalop** [comment]
good news, thank you
