### ISSUE TITLE
Built in database

### ISSUE THREAD

**Issue by ghost** [invoiceninja/dockerfiles#502]
Please add the function that the database is built in the invoiceninja container, if no external database is connected by envoiremental variables.

This would make the deployment much more efficient and increase security. In addition, errors that arise with the database can be minimized. (For example, if the database container starts after the invoiceninja container, and much more).

Many of the popular server applications have this built in, such as:

- https://nginxproxymanager.com/guide/#quick-setup
- https://www.home-assistant.io/installation/linux
- https://github.com/nextcloud/all-in-one
- ...

**Comment by turbo124** [comment]
Not sure I follow, if you use the docker-compose file everything is prebundled and ready to use?

**Comment by R7JANV1** [comment]
> Not sure I follow, if you use the docker-compose file everything is prebundled and ready to use?

Not all server operating systems support docker compose. For example TrueNAS Scale or Synology.

**Comment by lwj5** [comment]
Hi there,

I'm one of the volunteers that helped to develop the dockerfile and helm chart.

@turbo124 i think what he is asking is to use SQLite with IN.

Does such a db work?

https://laravel.com/docs/10.x/database#sqlite-configuration
