### ISSUE TITLE
Question: How to run PHP commands?

### ISSUE THREAD

**Issue by LeehamElectronics** [invoiceninja/dockerfiles#508]
I am following [this](https://invoiceninja.github.io/docs/self-host-installation/#individual-mail-configurations-per-company) guide where I am told to run the following commands:
```
php artisan config:cache
php artisan config:clear
```
Where exactly and how am I supposed to run these commands? I have tried to use the docker console for the container but I get the following error:
`OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown`

I am using Docker Compose on Ubuntu Server.

Thanks for your help.

**Comment by turbo124** [comment]
@LeehamElectronics 

For docker you only need to reboot the container ie

```
docker-compose down
docker-compose up
```

no need to run any commands (i'll update the docs)
