### ISSUE TITLE
getting access denied after modifying docker-compose.yml

### ISSUE THREAD

**Issue by jorge198506** [invoiceninja/dockerfiles#514]
if i modify the docker-compose.yml file and re  deploy it after invoice ninja has been deployed i get acces denied to the DB

[dockerfiles-app-1]
  SQLSTATE[HY000] [1045] Access denied for user 'ninja'@'172.19.0.3' (usi  
  ng password: YES) (SQL: select * from information_schema.tables where table  
  _schema = ninja and table_name = accounts and table_type = 'BASE TABLE')     
                                                                               
In Connector.php line 70:
                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'ninja'@'172.19.0.3' (usi  
  ng password: YES)                                                            
                                                                               
2023-05-22T03:41:45Z [ERROR] [Entrypoint]: Error connecting to DB

[dockerfiles-db-1]
[System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.33'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.

[dockerfiles-server-1]
2023/05/22 03:48:55 [notice] 1#1: OS: Linux 5.15.0-72-generic
2023/05/22 03:48:55 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/05/22 03:48:55 [notice] 1#1: start worker processes
2023/05/22 03:48:55 [notice] 1#1: start worker process 22
2023/05/22 03:48:55 [notice] 1#1: start worker process 23

if i delete everything and do a new deployment it works just fine.
any ideas would be great.

thanks

**Comment by kierenblack** [comment]
Do you have an update? I have the same issue

**Comment by pmoscode** [comment]
same here

**Comment by hillelcoren** [comment]
Advice from the support forum:

"I believe that when you start the container for the first time, if the database db container has not been created yet, then the db credentials set at that point in time will be used to create the root db user and db user.

If you later change them to another value, that will not change anything. You will want to remove the database image completely. Set your preferred db credentials. And then start up the containers again."

**Comment by pmoscode** [comment]
You will need to delete the volumes too, not just the container/image.
Or you can change the user's password directly in the database, if you don't want to loose existing data.

**Comment by hillelcoren** [comment]
More advice from the support forum:

"I tried to provide a minimal environment on [labs.play-with-docker.com](http://labs.play-with-docker.com/) where I could replicate the error. But there the issue didn’t exist :wink:

I needed to run all these commands to use the custom password. It seems as there was still some DB config that was being used:

```
docker compose down --volumes --remove-orphans
rm -rf ./.env ./nginx ./php ./supervisor
docker image prune -a
docker system prune -a --volumes
docker network rm `docker network ls -q`
cd ..
rm -rf dockerfiles/
```
