### ISSUE TITLE
Recent docker builds are failing due to composer.lock changes

### ISSUE THREAD

**Issue by anojht** [invoiceninja/dockerfiles#520]
I am going to keep this brief as you can already see the docker build failure logs in your Github Actions pipeline.

The following commit which introduced large dependency bumps in the composer.lock file has caused release builds to fail since the commit was introduced: [commit SHA](https://github.com/invoiceninja/invoiceninja/commit/295d6971f659b36e23a7d01a631745d74b5d4e60)

If I revert the composer.lock file to 1 commit before the problematic one, the build works fine. I just pushed a v5.6.10 image for a docker container that I maintain myself for invoiceninja with this manual change. 

I wanted to report it here and tag @turbo124 @lalop in case it helps your troubleshooting.

**Comment by turbo124** [comment]
I attempted to revert the lock file but I'm still seeing issues. 

I'm looking into an appropriate fix for this, thanks for reporting. @anojht

**Comment by anojht** [comment]
> 

I added the following line: `RUN curl -L https://raw.githubusercontent.com/turbo124/invoiceninja/b71e3a19af5c628850a0e7f284d279cc7e5f4d33/composer.lock -o composer.lock`
above the `RUN /usr/local/bin/composer install --no-dev --quiet` line. 

It's very crude but it basically fetches the working version of the composer.lock file and overwrites the one in the directory before installing dependencies. Seems to fix builds for me. 

I unfortunately don't have the expertise when it comes to PHP to narrow down which dependency(s) are the problematic ones. I am a TS/C# guy... 😅

**Comment by anojht** [comment]
Looks like the latest changes fixed the build.

Thanks and great job tracking down the fix! 😄  
Closing this issue now.
