### ISSUE TITLE
The APP_KEY generation failing on latest version. v5.6.15

### ISSUE THREAD

**Issue by QuickSwitchLK** [invoiceninja/dockerfiles#523]
Docker Compose of latest version v5.6.15-C122

As per directions the command...

docker run --rm -it invoiceninja/invoiceninja php artisan key:generate --show

now fails with the following error.

PHP Warning:  require(/var/www/app/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/app/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/app/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/app/artisan:18
Stack trace:
#0 {main}
  thrown in /var/www/app/artisan on line 18

**Expected behavior**
The APP_KEY generation works like older versions.

**Comment by turbo124** [comment]
I've changed the build process to avoid this, available in 5.6.16
