### ISSUE TITLE
Bypass setup

### ISSUE THREAD

**Issue by karneaud** [invoiceninja/dockerfiles#53]
is there anyway to "bypass" the "setup" process when using self hosted docker file installation? Seems that setup would keep overwriting stuff that "undos" my initial docker setup

**Comment by hillelcoren** [comment]
The setup screen is shown when either:
- The tables haven't been created in the database
- The user/account record hasn't been created

Which values are getting undone, the form should be populated with the current settings.

**Comment by karneaud** [comment]
then I guess it must be the user account is there anything built in to set this up or do I need to come up with the seed myself?

**Comment by hillelcoren** [comment]
You can probably modify this seed

https://github.com/invoiceninja/invoiceninja/blob/master/database/seeds/UserTableSeeder.php

**Comment by karneaud** [comment]
noted!

**Comment by hillelcoren** [comment]
Can you explain how you're using the app, are you reselling/redistributing it?

The problem with the seeder is the user won't have a chance to accept the application's terms of service.

**Comment by hillelcoren** [comment]
I believe this may be your question:

https://stackoverflow.com/questions/44604624/creating-app-from-several-sources

I'd suggest reviewing our license to make sure you're in compliance.

https://github.com/invoiceninja/invoiceninja/blob/master/LICENSE

**Comment by karneaud** [comment]
@hillelcoren it is for personal use( I bought my own license) however I did make a public build pack for hosting on heroku https://github.com/karneaud/invoiceninja-buildpack 

Let me know if this is appropriate

**Comment by hillelcoren** [comment]
Thanks for the clarification!

Your project looks good.

**Comment by karneaud** [comment]
@hillelcoren thanks! Initially for some reason everytime I updated "my" source code and the rebuilt the project I kept having to go through "setup" process even though I had a persistent database. However, I believe it maybe because I had a script run post build to "force migrate" 


I note another funny thing is that the application kept going to "/update" but errors out. I assume it was because I was running a previous version and it was trying to auto update?

**Comment by karneaud** [comment]
@hillelcoren BTW the referenced question was related to trying to develop a build pack/ or template for hosting Openshift. However as you can see I'm stuck as I'm not familiar with openshift at the moment

**Comment by hillelcoren** [comment]
What error are you seeing when loading /update?

**Comment by karneaud** [comment]
Here's the thing....when trying to access the site when an earlier version was installed it automatically redirected to /update this kept leading to a 503 Service Unavailable which I'm not sure of because it should have gone to /setup at the time. Now that I am using the latest and already went through the setup everything seems to work. However, I note that going to /update give me the 503 error

**Comment by hillelcoren** [comment]
I'm not sure, you should only see a 503 error if the app is in maintenance mode.

Are there any details in the logs in storage/logs/laravel-error.log

**Comment by karneaud** [comment]
there isn't one. if you want to continue his talk on a more personal level I can email u my gmail and we can google chat about it further

**Comment by hillelcoren** [comment]
Whatever you prefer...
