### ISSUE TITLE
Unable to view / print / download PDF invoices in docker

### ISSUE THREAD

**Issue by markdesouza** [invoiceninja/dockerfiles#534]
## Setup
- Version: v5.7.10-C123
- Environment: Docker-Compose (from https://github.com/invoiceninja/dockerfiles)

## Describe the bug
Unable to view / print / download PDF invoices (the URL is wrong)

eg
http://localhost:8003/client/invoice/K1r9w3ljZCvS1Wuy6dGwVGn5n8huLTg2/download?t=1694075882638
should be
http://in.localhost/client/invoice/K1r9w3ljZCvS1Wuy6dGwVGn5n8huLTg2/download?t=1694075882638

### Steps To Reproduce
Create an invoice attempt to download the pdf

### Expected Behavior
to be able to download the pdf, without manually correcting the URL

## Additional context

Here is the start of my env file....
APP_URL=http://in.localhost
APP_KEY=<REDACTED>
APP_DEBUG=false
REQUIRE_HTTPS=false
PHANTOMJS_PDF_GENERATION=false
PDF_GENERATOR=snappdf
TRUSTED_PROXIES='*'
LOCAL_DOWNLOAD=false
IS_DOCKER=true
QUEUE_CONNECTION=database

```

```

**Comment by markdesouza** [comment]
Nope still sent to the wrong url "http://localhost:8003/client/invoice/<hash>"

It appears like the download invoice button is ignoring the APP_URL environment var

**Comment by turbo124** [comment]
@markdesouza 

In Settings > Client Portal

What is the URL defined for your client portal?

**Comment by markdesouza** [comment]
http://localhost:8003

**Comment by markdesouza** [comment]
ok so:
1) setting that to http://in.localhost
2) saving the settings
3) restarting the container
4) refreshing the browser

fixed the issue

note: didn't work after simply saving the settings
