### ISSUE TITLE
[BUG] Docker selfhosted bug

### ISSUE THREAD

**Issue by mariushosting** [invoiceninja/dockerfiles#542]
## Setup
- Version:  5.7.24
- Environment: Docker

Invoice Ninja does not start anymore. The error logs are the following:

2023-09-30T22:24:58Z [INFO] [Entrypoint]: Initialising Invoice Ninja...
   INFO  Configuration cached successfully.  
   INFO  Caching the framework bootstrap files.  
  config ........................................................... 30ms DONE
  routes ........................................................... 82ms DONE
   INFO  Discovering packages.  
  imdhemy/laravel-purchases ............................................. DONE
  intervention/image .................................................... DONE
  invoiceninja/inspector ................................................ DONE
  laravel/slack-notification-channel .................................... DONE
  laravel/socialite ..................................................... DONE
  laravel/tinker ........................................................ DONE
  laravel/ui ............................................................ DONE
  livewire/livewire ..................................................... DONE
  nesbot/carbon ......................................................... DONE
  nunomaduro/termwind ................................................... DONE
  nwidart/laravel-modules ............................................... DONE
  sentry/sentry-laravel ................................................. DONE
  socialiteproviders/manager ............................................ DONE
  spatie/laravel-data ................................................... DONE
  turbo124/beacon ....................................................... DONE
  webpatser/laravel-countries ........................................... DONE
In ReactBuilder.php line 51:
                                                                               
   RecursiveDirectoryIterator::__construct(/var/www/app/public/react/v5.7.24/)  
  : Failed to open directory: No such file or directory

**Comment by Hybes** [comment]
possibly in relation to the issue im having here: [Port 9000 not open in app on docker](https://forum.invoiceninja.com/t/port-9000-not-open-in-app-on-docker/14254)

**Comment by mariushosting** [comment]
> are you using the standard dockerfile?
> 
> I am unable to replicate this

https://mariushosting.com/how-to-install-invoice-ninja-on-your-synology-nas/

Reported by over 300 users in the last 3 days. I-m using that compose. Only version 5.7.22 is working right now.

**Comment by Hybes** [comment]
perhaps we are referring to different things then, because rolling back to 5.7.22 i still get:
2023/10/02 12:08:21 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.1.55, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://10.0.1.115:9000", host: "<URL>"

**Comment by mariushosting** [comment]
> perhaps we are referring to different things then, because rolling back to 5.7.22 i still get: `2023/10/02 12:08:21 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.1.55, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://10.0.1.115:9000", host: "<URL>"`

Your issue looks like more Firewall issue.

**Comment by turbo124** [comment]
@mariushosting 

The particular issue you are seeing should be resolved in 5.7.25 as now there will be no exception thrown in that directory is not found.

The larger issue is that the React Web App will not be available on those instances if that particular directory is not available.

It should be there as it is part of the build process within the Dockerfile....

**Comment by mariushosting** [comment]
> @mariushosting
> 
> The particular issue you are seeing should be resolved in 5.7.25 as now there will be no exception thrown in that directory is not found.
> 
> The larger issue is that the React Web App will not be available on those instances if that particular directory is not available.
> 
> It should be there as it is part of the build process within the Dockerfile....

looks like everything works now! Thank You Turbo!
