### ISSUE TITLE
Raspberry Pi DB Error

### ISSUE THREAD

**Issue by JoeKep-git** [invoiceninja/dockerfiles#545]
The steps have been followed on the raspberry pi and I have uncommented the `mariadb ` line in the compose file and commented the `mysql` line.

However, there is a database error when running the compose command.

This error is:

`no matching manifest for linux/arm/v8 in the manifest list entries`

I am running a raspberry pi 4 model b

**Comment by karneaud** [comment]
I ran into an issue like this...are you running headless? ensure that the OS is also 64bit and not 32bit

**Comment by JoeKep-git** [comment]
Yh, I am running headless and my Raspberry Pi is also 64 bit

**Comment by karneaud** [comment]
> Yh, I am running headless and my Raspberry Pi is also 64 bit

Yes but ensure your operating system is also 64bits

**Comment by ryangurn** [comment]
Try changing your image to the following without a tag so it uses the latest tag, this worked for me on my raspberry pi 4b.

Change from `image: mariadb:10.4` to `image: mariadb`
