### ISSUE TITLE
Tax line item not displaying in Totals area of invoice

### ISSUE THREAD

**Issue by Condolas** [invoiceninja/dockerfiles#548]
**Setup information**
 docker-compose 

**Describe the bug**
The tax line does not display on the invoice in the totals area. The tax is correctly calculated, and updates the other totals values, however the tax line itself does not display. I have set the invoice design to include the tax. 

**To reproduce**
1. Create invoice with some products/tasks
2. Scroll down to totals
3. Unable to see tax line item

**Expected behavior**
On the invoice, I should see the tax as a line item in the totals area as shown in the invoice designer preview. 

**Screenshots/logs**
![image](https://github.com/invoiceninja/dockerfiles/assets/50589752/d9f379b6-b278-4985-a6a9-8797a9d93000)
![image](https://github.com/invoiceninja/dockerfiles/assets/50589752/01db38f0-2ddb-43e9-919a-504e0a16a712)
![image](https://github.com/invoiceninja/dockerfiles/assets/50589752/04f1f8d4-bd44-4085-9c37-99d2784e0be0)

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:26 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:26 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by turbo124** [comment]
Are you on the latest release? i believe this has been fixed in the latest.

**Comment by Condolas** [comment]
Pulled the latest release and confirmed the issue is resolved. Thanks!
