### ISSUE TITLE
Permissions Error with Lost+Found Directory

### ISSUE THREAD

**Issue by dlford** [invoiceninja/dockerfiles#553]
**Setup information**

Helm

**Describe the bug**
500 error on landing page

**To reproduce**
1. Set up a k8s cluster
2. Install Longhorn storage controller
3. Deploy the Helm chart
4. Visit the landing page
5. See the 500 error

**Expected behavior**
The site has no errors

**Screenshots/logs**

```
production.ERROR: RecursiveDirectoryIterator::__construct(/var/www/app/public/lost+found): Failed to open directory: Permission denied {"exception":"[object] (UnexpectedValueException(code: 0): RecursiveDirectoryIterator::__construct(/var/www/app/public/lost+found): Failed to open directory: Permission denied at /var/www/app/app/Utils/SystemHealth.php:134)
```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
containerd.io version 1.6.24
```

- Output of `helm version`:
```
v3.13.2
```
- Output of `kubectl version`:
```
v1.28.2
```

**Additional context**

Longhorn creates an ext4 partitioned volume for each pv, so the `lost+found` directory exists at the root of each volume and cannot be removed.

**Comment by lwj5** [comment]
Could you set volumePermissions.enabled to true

maybe longhorn does not support fsgroup

**Comment by dlford** [comment]
> Could you set volumePermissions.enabled to true
> 
> maybe longhorn does not support fsgroup

Well that was my bad, `volumePermissions.enabled` does the trick, sorry for wasting your time!
