### ISSUE TITLE
git clone not pulling latest version

### ISSUE THREAD

**Issue by Joey4tunato** [invoiceninja/dockerfiles#555]
Hey guys I am new here so please forgive me if i am spewing newbie garbage! Thanks for all you do! The issue I am having is the the newest version is not pulling with git clone. Not sure what more info you need please let me know and please be gentle on this newbie I am just starting to learn :)

**Comment by turbo124** [comment]
@Joey4tunato 

If you are using the docker-compose file then just run

```
docker-compose down
docker-compose pull
docker-compose up
```

**Comment by Joey4tunato** [comment]
That isn’t working hence why I came to the forum. I also tried installing and updating compose and it throws errors

**Comment by turbo124** [comment]
not sure, if you installed using the readme, this is the typical way to update the app with docker-compose

**Comment by Joey4tunato** [comment]
I'm following the steps in the read me and still nothing. Any ideas?

**Comment by Joey4tunato** [comment]
This is what I'm seeing
![image](https://github.com/invoiceninja/dockerfiles/assets/45377687/e60847d4-c659-4278-8e5c-344237e5fe3c)

**Comment by Joey4tunato** [comment]
Just bumping this to stay top of mind
