### ISSUE TITLE
Http links requested when visiting a https page 

### ISSUE THREAD

**Issue by kloknibor** [invoiceninja/dockerfiles#562]
**Setup information**

docker-compose 

**Describe the bug**
![image](https://github.com/invoiceninja/dockerfiles/assets/10560390/05532120-7c71-4cca-9b28-14d586434037)

**To reproduce**
1. Go to client portal
2. Check console
3. See error

**Expected behavior**
The client portal to properly load

**Screenshots/logs**
![image](https://github.com/invoiceninja/dockerfiles/assets/10560390/f1f084a1-1fad-4afc-8435-63efcf460524)

```
No special errors```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
Docker version 25.0.1, build 29cf629
```
<!-- Additional info if using helm on k8s, add the info below -->
<!-- Delete this block if not applicable -->
- Output of `helm version`:
```
(paste your output here)
```
- Output of `kubectl version`:
```
(paste your output here)
```
<!-- End Additional info if using helm on k8s -->

**Additional context**
I am using an Apache reverse proxy which uses SSL to reach the internal Invoice ninja server. So : Public IP --> SSL --> Reverse proxy --> Traffic without SSL --> Invoice ninja install.

I am also using the react interface (and don't know hot to switch back in docker). I woudl expect if I visit a https link all requested links are also https, this is not the case. Enabling require https makes the installation not accesable.

**Comment by ryangurn** [comment]
What is in your `env` file? 

Do you have `APP_URL=http://in.localhost:8003` set like the example? You may need to update this to be https...

**Comment by chris-cartwright** [comment]
I'm seeing the same issue and have `https` specified for my protocol in `APP_URL`.

I have `REQUIRE_HTTPS` set to `false` in order to run behind a proxy that handles TLS termination.

<img width="544" alt="image" src="https://github.com/user-attachments/assets/2075e167-3572-4673-96ba-a3d00d4e0381">

**Comment by chris-cartwright** [comment]
Following the advice in this StackOverflow post worked for me: https://stackoverflow.com/a/65691937.

Can an option be added to call `URL::forceScheme('https')` within `boot`? I'm patching the file during build at the moment.
