### ISSUE TITLE
Logo does not load neither on the main page nor on invoices - Docker Version

### ISSUE THREAD

**Issue by dbawebtech** [invoiceninja/dockerfiles#571]
I have painfully but proudly installed Invoiceninja on docker for me locally on my pc. Everything is working as expected except the loading of the company logo, this is not reflected neither in the software header or in the pdf templates. The image is loaded in the project correctly in the "storage" folder, but neither Firefox  or chrome reflect the image, this last one is throwing me out this failure in console:

`Failed to load resource: net::ERR_CONNECTION_REFUSED`

here is my docker-compose.yml file:

**Comment by turbo124** [comment]
try adding to your ENV

IS_DOCKER=true

**Comment by dbawebtech** [comment]
this does not work for me
