### ISSUE TITLE
Changes made to env are not updating docker-compose containers

### ISSUE THREAD

**Issue by JackPala** [invoiceninja/dockerfiles#576]
I created a latest instance of invoiceninja using the docker-compose method 

The initial entries I put in the env file seemed to have been ingested into the container

but when I make to env, and then `docker compose down` and then `docker compose up -d` - it appears that the changes I make to the env file do not update the new container.

**Comment by turbo124** [comment]
@JackPala 

Just to confirm, are you changing the .env in the container itself, or in the docker-compose folder? there is a file "env" there which you can make you env changes.
