### ISSUE TITLE
Issues Deploying with Docker

### ISSUE THREAD

**Issue by programster** [invoiceninja/dockerfiles#58]
I'm re-posting this from: https://github.com/invoiceninja/invoiceninja/issues/1718#issuecomment-338502012 as I told this place may be more appropriate.

Hey,
I just wanted to give this tool a whirl and thought the easiest way to deploy it would be with docker. Unfortunately it doesn't appear to be working for me. I just get an "Unable to connect message" in Firefox.

I'm running Ubuntu 16.04.3 with docker and I set up a test mysql database which is listening on 0.0.0.0. The test "ninja" database can be accessed by the ninja user with the ninja password.

I then ran this to get set up:
```
#!/bin/bash

# Create local volume directories
mkdir -p $HOME/invoice-ninja/logo
mkdir -p $HOME/invoice-ninja/storage

docker run -d \
  -e APP_ENV='production' \
  -e APP_DEBUG=0 \
  -e APP_URL='http://10.2.0.11' \
  -e APP_KEY='SomeRandomStringSomeRandomString' \
  -e APP_CIPHER='AES-256-CBC' \
  -e DB_TYPE='mysql' \
  -e DB_STRICT='false' \
  -e DB_HOST='10.2.0.11' \
  -e DB_DATABASE='ninja' \
  -e DB_USERNAME='ninja' \
  -e DB_PASSWORD='ninja' \
  -v $HOME/invoice-ninja/logo:/var/www/app/public/logo \
  -v $HOME/invoice-ninja/storage:/var/www/app/storage \
  -p '80:80' \
  invoiceninja/invoiceninja
```

In this case 10.2.0.11 is the IP of my machine.

I see that the dockerhub page states to go to port 8000, but then goes on to use port 80 in the docker run command example.

Also the [dockerhub page](https://hub.docker.com/r/invoiceninja/invoiceninja/) has the command without the necessary `\` characters to go multi-line, but maybe that would work in some other environment (e.g. not BASH on linux)

The output of my `docker ps` is:
```
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                          NAMES
baa2f0d68ce9        invoiceninja/invoiceninja   "/entrypoint.sh ph..."   3 seconds ago       Up 2 seconds        0.0.0.0:80->80/tcp, 9000/tcp   quizzical_golick
```
I'm not sure what port 9000 is being  used for either.

What am I missing? 

Also, why is there a separate project just for docker instead of having the dockerfiles any anything else necessary for docker within a docker folder? This would allow the application layer and deployment to always be in sync. E.g. if you decided to use a feature from php 7.2 (when it comes out), the developers could make the necessary dockerfile change at the point of using the feature.

**Comment by hillelcoren** [comment]
The app is handled by the Invoice Ninja team, the Docker file is managed by the community led by @lalop

**Comment by programster** [comment]
@hillelcoren thats a shame but makes sense. It's fantastic that you have any docker support at all. 

Now if we can just figure out what is going wrong with my attempts to deploy the dockerhub image.

**Comment by lalop** [comment]
hello @programster, I'm affraid the Readme isn't correct.
The invoiceninja is based on an php-fpm image so you will need to use a web server in front of it.
I will correct the Readme but for now the simplest way to give a try to invoiceninja is by using docker-composer as described in exampale

**Comment by hbadran83** [comment]
cannot save or send a proposal or invoice .. i have an error message: "could not save invoice"

**Comment by hillelcoren** [comment]
I suggest posting to the support forum:

https://www.invoiceninja.com/forums/forum/support/

It'd be helpful if you could check for any related errors in the web server error logs and storage/logs/laravel-error.log
