### ISSUE TITLE
Enable multiple SMTP for multiple company

### ISSUE THREAD

**Issue by Kingwayer** [invoiceninja/dockerfiles#582]
This is not bug, this is feature request, can you enable multiple smtp A/C for multiple company, for example each company has their own smtp A/C to send email.

**Comment by turbo124** [comment]
you now configure the mailservers directly in the interface, not in the .env files.

**Comment by Kingwayer** [comment]
@turbo124  David, yes, I am talk about on the setting- mail setting section
