### ISSUE TITLE
Issue adding initial user/finishing setup

### ISSUE THREAD

**Issue by poxon** [invoiceninja/dockerfiles#59]
Hello, 

I just cloned this repo and did a docker-compose up in the example folder. Everything installed correctly but I am getting an error after trying to go through setup.

`FatalThrowableError in AccountRepository.php line 66:
Call to a member function filter() on null`

Thank you in advance!

Edit:
whole error: https://pastebin.com/4DFy20S3

**Comment by hillelcoren** [comment]
I think this is the problem: https://github.com/invoiceninja/invoiceninja/issues/1738
