### ISSUE TITLE
Possibility of inclusion on https://stackfiles.io/?

### ISSUE THREAD

**Issue by spicypixel-** [invoiceninja/dockerfiles#6]
Would it be possible to edit the docker-compose to work with [cloud.docker.com](cloud.docker.com) and their [stackfiles.io](stackfiles.io) repository?

**Comment by lalop** [comment]
I imagine we can yes but I'm not aware of what is needed to do that.
Have you some more information ?

**Comment by spicypixel-** [comment]
Seem it just needed the nginx port in quotations to parse.

**Comment by lalop** [comment]
@spicypixel- why did you close it ?

**Comment by spicypixel-** [comment]
Yeah due to [the issue](https://github.com/invoiceninja/invoiceninja/issues/827) here with the .env file being broken it doesn't work if you can't volume mount an .env file with SMTP settings pre set.

**Comment by codedge** [comment]
Seems to be outdated? Can we close the issue?
