### ISSUE TITLE
Can't complete InvoiceNinja setup

### ISSUE THREAD

**Issue by unixfy** [invoiceninja/dockerfiles#60]
Hi,

I am using InvoiceNinja in conjunction with a Traefik reverse proxy. Everything works properly after `docker-compose up -d` but I cannot complete the setup wizard. When I click Submit, the page loads for several seconds and then gives me error `Call to a member function filter() on null`. Why is this?

**Comment by hillelcoren** [comment]
I think this is the problem: https://github.com/invoiceninja/invoiceninja/issues/1738

**Comment by unixfy** [comment]
How can I resolve the issue? I'd like to use InvoiceNinja but this error is holding me back.

**Comment by hillelcoren** [comment]
You can manually patch the code or wait for the next release

**Comment by unixfy** [comment]
Hi,

It works after patching the code but I cannot login.

`fopen(/var/www/app/storage/version.txt): failed to open stream: Permission denied`
