### ISSUE TITLE
PO/Invoice can't show shipping address field, it's empty.

### ISSUE THREAD

**Issue by Kingwayer** [invoiceninja/dockerfiles#602]
PO/Invoice can't show shipping address field, it's empty.

![image](https://github.com/invoiceninja/dockerfiles/assets/171299849/093ad4aa-b413-4e1d-8f3b-4c2d62e3ed88)

**Setup information**

docker run / docker-compose / Helm

**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots/logs**

```
Any Error that sucks
```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
(paste your output here)
```

- Output of `helm version`:
```
(paste your output here)
```
- Output of `kubectl version`:
```
(paste your output here)
```

**Additional context**

**Comment by turbo124** [comment]
vendors do not have a shipping address.
