### ISSUE TITLE
Upgrade from 5.4 to 5.5 (or later Versions) error

### ISSUE THREAD

**Issue by lucamarien** [invoiceninja/dockerfiles#606]
**Setup information**
docker compose running in Swarm Mode
Mysql latest V8

**Describe the bug**
With the Upgrade to 5.5 or later Versions I get the following Error in the Application Logs:

```invoiceninja_app.1.bor3abn1tf2a@server|
invoiceninja_app.1.bor3abn1tf2a@server    |    INFO  Running migrations.
invoiceninja_app.1.yvzoh634edsa@server    |    INFO  Configuration cached successfully.
invoiceninja_app.1.bor3abn1tf2a@server    |
invoiceninja_app.1.bor3abn1tf2a@server    |   2022_06_24_141018_upgrade_failed_jobs_table ....................... 2ms FAIL
invoiceninja_app.1.yvzoh634edsa@server    |
invoiceninja_app.1.bor3abn1tf2a@server    |
invoiceninja_app.1.yvzoh634edsa@server    |
invoiceninja_app.1.bor3abn1tf2a@server    | In Connection.php line 760:
invoiceninja_app.1.yvzoh634edsa@server    |    INFO  Caching the framework bootstrap files.
invoiceninja_app.1.bor3abn1tf2a@server    |
invoiceninja_app.1.bor3abn1tf2a@server    |   SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'uuid' (
invoiceninja_app.1.bor3abn1tf2a@server    |   SQL: alter table `failed_jobs` add `uuid` varchar(191) null after `id`)
invoiceninja_app.1.yvzoh634edsa@server    |```

**Docker**:
- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:18:12 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:18:12 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Additional context**
The Error occurs on every version after 5.4
I already tried running:
- `php artisan ninja:check-data` - without any errors
- `php artisan migrate`

**Comment by pippo73** [comment]
Since I have a similar problem, could you explain me how you fixed your problem?

**Comment by lucamarien** [comment]
Hi everyone!
I'm still running into this issue and haven't been able to find a workaround, so I'm stuck on the older version.
I'd really appreciate any advice or guidance the community or maintainers might have. Thanks so much!
