### ISSUE TITLE
[Question] ENV-Variable db_type existing?

### ISSUE THREAD

**Issue by n1smithy** [invoiceninja/dockerfiles#607]
Hi there,

in another post I saw a ENV-variable `DB_TYPE='mysql'`, but I didn't found that in the official ENV-documentation.

I use mariadb 10.4 and I wonder if this should be mentioned in the variable above.

Hope this is no silly question, but I like it to have unclear situations cleared. So thanks a lot!

Greetz

**Comment by turbo124** [comment]
mysql is the appropriate setting in this context for that variable.

**Comment by n1smithy** [comment]
Thanks a lot, David!
