### ISSUE TITLE
Error on reading manifest.json:

### ISSUE THREAD

**Issue by CosmicWebCreator** [invoiceninja/dockerfiles#610]
**Setup information**

 docker-compose 

**Describe the bug**
Unable to load admin page. Error on manifest.json

**To reproduce**

1. go to main site
2. log in
3. i get the following 
`GET https://invoice.domain.com/manifest.json 403 (Forbidden)Understand this error
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.Understand this error
bundle.js:56 TypeError: Cannot read properties of undefined (reading 'includes')
    at pRt (bundle.js:681:540)
    at zde (bundle.js:54:19642)
    at M3e (bundle.js:56:44387)
    at R3e (bundle.js:56:40075)
    at Cdt (bundle.js:56:39998)
    at nB (bundle.js:56:39847)
    at Ste (bundle.js:56:36177)
    at BCe (bundle.js:56:36987)
    at Uw (bundle.js:54:3312)
    at bundle.js:56:34485`
4- enable debugging
5- app works in debugging but not in web mode (react)

**Expected behavior**
should load the admin page

**Screenshots/logs**
![image](https://github.com/user-attachments/assets/a9b7b379-29a3-4cd3-8b00-008f61d7e6bb)
![image](https://github.com/user-attachments/assets/55957cde-2ea2-41e0-990a-4f322dab8318)

no errors really in the logs, mostly 200

`   INFO  No scheduled commands are ready to run.  
172.18.0.37 -  17/Jul/2024:23:03:30 +0000 "GET /index.php" 200
172.18.0.37 -  17/Jul/2024:23:03:31 +0000 "GET /index.php" 200
172.18.0.37 -  17/Jul/2024:23:03:31 +0000 "POST /index.php" 200
`

```
[warn] 46#46: *77 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/6/00/0000000006 while reading upstream, client: 172.18.0.16, server: _, request: "GET /api/v1/statics HTTP/1.1", upstream: "fastcgi://172.18.0.33:9000", host: "invoice.domain.com", referrer: "https://invoice.domain.com/dashboard"
172.18.0.16 - - [17/Jul/2024:19:01:39 -0400] "GET /api/v1/statics HTTP/1.1" 200 295624 "https://invoice.domain.com/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "174.89.225.45, 108.162.242.56"
```
``

**Docker/Kubernetes/Helm**:

Docker version 27.0.3, build 7d4bcd8

**Comment by turbo124** [comment]
can you check if the file public/index.html exists in your container? it may need to be removed.

**Comment by CosmicWebCreator** [comment]
> can you check if the file public/index.html exists in your container? it may need to be removed.

I am using the default nginx and invoice ninja provided in this repo behind traefik. It used to work well both in debug mode and react mode. However, I updated recently  and now I can only access it via debug mode. React shows the above error. 

Which container should I check the index.html be present in? Nginx?

**Comment by turbo124** [comment]
@CosmicWebCreator within the app container 

if public/index.html exists, can you remove it please and restart the container.

alternatively, if you preference index.php in front of index.html in your nginx config this should also achieve the same thing

**Comment by CosmicWebCreator** [comment]
> if you preference index.php in front of index.html in your nginx config this should also achieve the same thin

so there was a index.html and i did remove it . The manifest error went away but still have the blank screen and the following 
![image](https://github.com/user-attachments/assets/fc91901c-bb5f-433a-9262-4ca0d889c5a3)

Weird thing is that i can connect to it via the desktop app or via the client portal ... just the /dashboard that is a blank screen. Nothing to report within the container 

`172.18.0.37 -  18/Jul/2024:00:16:31 +0000 "GET /index.php" 200
172.18.0.37 -  18/Jul/2024:00:16:33 +0000 "GET /index.php" 200
172.18.0.37 -  18/Jul/2024:00:16:33 +0000 "POST /index.php" 200
172.18.0.37 -  18/Jul/2024:00:16:42 +0000 "POST /index.php" 200
172.18.0.37 -  18/Jul/2024:00:16:46 +0000 "GET /index.php" 200
172.18.0.37 -  18/Jul/2024:00:16:47 +0000 "GET /index.php" 200
172.18.0.37 -  18/Jul/2024:00:16:47 +0000 "POST /index.php" 200
   INFO  No scheduled commands are ready to run.  
172.18.0.37 -  18/Jul/2024:00:17:05 +0000 "GET /index.php" 200
   INFO  No scheduled commands are ready to run.  

      `

**Comment by CosmicWebCreator** [comment]
debugging a bit further, using the same browser but with a different user works and works in incognito. However, I cleared all my site data and still can not see /dashboard after sign in.... Not sure what could cause this if it is working via other users on the same computer. No extensions nothing.

**Comment by CosmicWebCreator** [comment]
im going to close this since i don't believe it is a defect from this repo but something around the browser/app data
