### ISSUE TITLE
Docker Compose instructions don't work

### ISSUE THREAD

**Issue by gmpreussner** [invoiceninja/dockerfiles#616]
**Setup information**
docker-compose

**Describe the bug**
Unable to install Invoice Ninja 5 via Docker Compose instructions provided in README

**To reproduce**
1. Clone the _dockerfiles_ repository
2. Run `docker run --rm -it invoiceninja/invoiceninja php artisan key:generate --show`

**Expected behavior**
An app key is generated

**Screenshots/logs**
The following output is produced instead:
```
app-1     | rm: can't remove '/var/www/app/docker-backup-storage/logs': Invalid argument
app-1     | rm: can't remove '/var/www/app/docker-backup-storage/framework/testing': Invalid argument
app-1     | rm: can't remove '/var/www/app/docker-backup-storage/framework/cache': Invalid argument
app-1     | rm: can't remove '/var/www/app/docker-backup-storage/framework/sessions': Invalid argument
app-1     | rm: can't remove '/var/www/app/docker-backup-storage/framework/views': Invalid argument
app-1     | rm: can't remove '/var/www/app/docker-backup-storage/app/public': Invalid argument
```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
Docker Compose version v2.29.2
```

**Additional context**
- The same errors are produced in the container logs when trying to bring up the containers via `docker compose up -d`.
- The `app` container never starts successfully and is stuck in a restart loop.
- The `db` and `server` containers start successfully

I also tried running the following commands prior to generating an app key:
```
chmod 755 docker/app/public
sudo chown -R 1500:1500 docker/app
```

I verified that the folder permissions were applied as indicated above.

I did not modify the `docker-compose.yml` in any way.

**Comment by turbo124** [comment]
Most likely the user you are running the container as is no in that group.
