### ISSUE TITLE
Error adding a gocardless payment

### ISSUE THREAD

**Issue by tecnomur** [invoiceninja/dockerfiles#618]
Hi everyone, I’m having problems with the latest version in docker 5.10.31 when adding a gocardless payment gateway in any client, from the client portal, when I try to add it it comes up “Attempt to read property “hash” on null.” There is correct program connection to the API. Other previous payments have gone smoothly.

![IMG_5441](https://github.com/user-attachments/assets/969cce8a-76ae-4cb4-80fb-ea8b73b0aef7)
![IMG_5440](https://github.com/user-attachments/assets/6b2a256a-9c08-4e43-ac73-e9ad3858b119)

Thanks

**Comment by turbo124** [comment]
i've tagged 5.10.32 which should have this resolved

**Comment by tecnomur** [comment]
@turbo124 David, I have tried and the problem still happens.

**Comment by turbo124** [comment]
@turbo124 are you on 5.10.32 ?

**Comment by tecnomur** [comment]
> @turbo124 are you on 5.10.32 ?

Yes David, thanks again for trying to solve the problem.

**Comment by turbo124** [comment]
@tecnomur which payment method is this for?

**Comment by tecnomur** [comment]
It is for add a Bank account at GoCardless. Normally, a gocardless website would appear to enter the customer's account number.

**Comment by turbo124** [comment]
@tecnomur i'll tag .33 now, perhaps the fix was not merged into the branch prior to release. let me know if .33 still does not have this resolved.

**Comment by tecnomur** [comment]
@turbo124 Thanks so much. It is working now.
