### ISSUE TITLE
403 Forbidden nginx

### ISSUE THREAD

**Issue by PMTGaming** [invoiceninja/dockerfiles#625]
**Setup information**

docker-compose

**Describe the bug**
Cant accsess the invoiceninja login screen.

**To reproduce**
Followed the Instructions (invoiceninja/dockerfiles)
Made an Folder
Downloaded and unziped the dockerfiles
editet the docker-compose.yml and env File
Changed permission on the folder with the `sudo chmod 755 docker/app/public
sudo chown -R 1500:1500 docker/app`
run the docker

**Expected behavior**
Get to the Website

**Screenshots/logs**
![grafik](https://github.com/user-attachments/assets/1c3af903-f666-4343-9051-d9b7ced56e0e)

```
2024/10/24 17:40:28 [error] 29#29: *1 "/var/www/app/public/index.php" is forbidden (13: Permission denied), client: 192.168.0.6, server: _, request: "GET / HTTP/1.1", host: "invoice.marquezinc.eu"
192.168.0.6 - - [24/Oct/2024:17:40:28 +0000] "GET / HTTP/1.1" 403 146 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0" "81.223.85.196"
```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
Docker Compose version v2.29.1-qnap1
```

**Additional context**

**Comment by Ahson-Shaikh** [comment]
Does anybody has found out the issue with this? I believe the this is due to the absence of index.html or php file on that location. Because the permissions are good to go with.

**Comment by dcowan-london** [comment]
I get the same error - in my case, I believe this is due to failure to forward the request to the `app` container, as the `app` container is failing to start. This seems to be due to a lack of any files in the `/tmp/public/` directory in the `app` container, which [the `init.sh` script attempts to move to /var/www/html/public/](https://github.com/invoiceninja/dockerfiles/blob/a0454d3998d3e9f56ca0f191408e30112250c229/debian/scripts/init.sh#L23).

**Comment by AAverin** [comment]
What was the resolution for this one?
Getting the same just following the container setup

**Comment by AAverin** [comment]
The solution is to use `invoiceninja/invoiceninja-debian:latest`

**Comment by DaGloaDone** [comment]
i actually have the same issue. I am running the latest container `invoiceninja/invoiceninja-debian:latest`

And those are the logs of the nginx Container
```/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2025/05/14 15:59:52 [notice] 1#1: using the "epoll" event method
2025/05/14 15:59:52 [notice] 1#1: nginx/1.27.5
2025/05/14 15:59:52 [notice] 1#1: built by gcc 14.2.0 (Alpine 14.2.0) 
2025/05/14 15:59:52 [notice] 1#1: OS: Linux 6.1.0-0.deb11.21-amd64
2025/05/14 15:59:52 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2025/05/14 15:59:52 [notice] 1#1: start worker processes
2025/05/14 15:59:52 [notice] 1#1: start worker process 20
2025/05/14 15:59:52 [notice] 1#1: start worker process 21
2025/05/14 15:59:52 [notice] 1#1: start worker process 22
2025/05/14 15:59:52 [notice] 1#1: start worker process 23
2025/05/14 15:59:52 [notice] 1#1: start worker process 24
2025/05/14 15:59:52 [notice] 1#1: start worker process 25
2025/05/14 15:59:52 [notice] 1#1: start worker process 26
2025/05/14 15:59:52 [notice] 1#1: start worker process 27
2025/05/14 16:00:09 [error] 20#20: *1 directory index of "/var/www/html/public/" is forbidden, client: 192.168.2.48, server: _, request: "GET / HTTP/1.1", host: "192.168.2.182:8081"
192.168.2.48 - - [14/May/2025:16:00:09 +0000] "GET / HTTP/1.1" 403 146 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:138.0) Gecko/20100101 Firefox/138.0" "-"
2025/05/14 16:00:09 [error] 20#20: *1 directory index of "/var/www/html/public/" is forbidden, client: 192.168.2.48, server: _, request: "GET / HTTP/1.1", host: "192.168.2.182:8081"
192.168.2.48 - - [14/May/2025:16:00:09 +0000] "GET / HTTP/1.1" 403 146 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:138.0) Gecko/20100101 Firefox/138.0" "-"
```


it would be really nice if someone could help me with that!
Thank you :)
