### ISSUE TITLE
[Self-hosted] Issue with Chinese Characters (Simplified and Traditional) Not Displaying in PDF Invoice

### ISSUE THREAD

**Issue by nascaline00** [invoiceninja/dockerfiles#626]
hi

After a fresh Docker deployment of the self-hosted service, Chinese characters (both simplified and traditional) are not displaying correctly in the PDF invoice content and page numbers. I do not see any options to select a Chinese font in Settings > Invoice Design.

![_0001](https://github.com/user-attachments/assets/2776838d-b093-4d26-944f-43036afe478b)

**Steps To Reproduce:**
Use Docker version 5.10.43.

Set the language to Chinese (TW) in settings.

Attempt to print or preview any PDFs.

**Comment by nascaline** [comment]
Unfortunately, I’ve just tested the self-hosted service with Docker version 5.10.58 and the issue with Chinese characters not displaying correctly in PDF invoices still persists.
