### ISSUE TITLE
Updating invoiceninja to new version is not possible with debian docker-compose.yml

### ISSUE THREAD

**Issue by benbrummer** [invoiceninja/dockerfiles#649]
**Setup information**

docker run / docker-compose / Helm

**Describe the bug**
invoiceninja stays on the version, which initialy created the volume, cause of https://github.com/invoiceninja/dockerfiles/blob/debian/debian/docker-compose.yml#L19

**To reproduce**
1. Clone https://github.com/invoiceninja/dockerfiles.git -b debian
2. cd to dockerfiles/debian
3. Set image tag to 5.10.56
4. docker compose up
5. docker compose down
6. Change image tag to latest again
7. docker compose up => docker will stay on 5.10.56

**Expected behavior**
invoiceninja is using the version defined in docker-compose.yml

**Comment by benbrummer** [comment]
Basically on the first start the volumes/directories are populated with the files from the image. New files, will be added if a newer tag contains new files at that location. Old/existing files will not be updated anymore after initialization.

I just checked the previous docker-compose.yml file. A similar behaviour can be seen there https://github.com/invoiceninja/dockerfiles/blob/9941847af73a03ac595692d24b9b1fe4b2ee0903/docker-compose.yml#L31

After many updates the public directory contains 2845 files
```
/opt/invoiceninja/docker/app/public# ls -1 | wc -l
2845
```

Without mounting the public folder it contains just  585 files
```
/var/www/html/public# ls -1 | wc -l
585
```

**Comment by turbo124** [comment]
this should resolve the issue: #651

this will use the images public/ directory not the volume.

**Comment by benbrummer** [comment]
https://github.com/invoiceninja/dockerfiles/pull/651 will fix the update issue, but not the continously growing public directory. Files like the index.php will never receive an update, only new files will be taken into account.

**Comment by benbrummer** [comment]
https://github.com/invoiceninja/dockerfiles/blob/3fca330958bcb0e19a70d50d229fa04f561bb4f2/debian/docker-compose.yml#L19 mounts the public directory as read only and will fail the deployment.
```
app-1     | cp: can't create '/var/www/app/public/useResolveCurrencySeparator-30f43bed.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/useShowEditOption-4936ae30.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/useSumTableColumn-16ef5d64.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/useTaskColumns-18a44495.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/utc-07806bdd.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/uz-6a2aa1f1.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/uz-latn-decee507.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/vb-77962f32.js': Read-only file system
app-1     | cp: can't create directory '/var/www/app/public/vendor': Read-only file system
app-1     | cp: can't create '/var/www/app/public/version.json': Read-only file system
app-1     | cp: can't create '/var/www/app/public/vi-0a4183d1.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/vi-56bbb11d.json': Read-only file system
app-1     | cp: can't create '/var/www/app/public/wgsl-e67d25e4.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/x-pseudo-6200fd6d.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/xml-e6335c8f.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/yaml-bcea1b2b.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/yo-95dcdde7.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/zh-51fc9c3b.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/zh-cn-67400750.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/zh-hk-90b238bd.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/zh-tw-246dacfb.js': Read-only file system
app-1     | cp: can't create '/var/www/app/public/zh_TW-0515ce5e.json': Read-only file system
app-1     | cp: can't create '/var/www/app/public/zh_TW-ca98e0c4.js': Read-only file system
```

If write would be allowed modified files will not be updated. 
```
diff public/version public.bak/version
1c1
< 5.10.57
---
> 5.10.48
```

So we need to find a different way to share the public folder between the app and nginx.

**Comment by turbo124** [comment]
I cannot recreate the issue you are seeing. With a completely fresh installation, the containers boot and work as expected.

The symlink, is just a refernence to /public the files are only being written to storage.

**Comment by benbrummer** [comment]
@turbo124  seems you are correct. Looks like I messed something up with the migration from master => debian.

Starting from scratch with docker volumes works, only the symlink inside nginx is invalid
![image](https://github.com/user-attachments/assets/20978be0-2604-4d12-8698-337727ee6f6d)

**Comment by turbo124** [comment]
That symlink looks correct I believe:

Source: /var/www/html/storage/app/public
Target: /var/www/html/public/storage

I do see an issue however when attempting to reach files directly with nginx which may be a path issue.

**Comment by turbo124** [comment]
#653

fixes the issue with symlinks. My testing shows public/storage files are now accessible as expected

**Comment by benbrummer** [comment]
> #653
> 
> fixes the issue with symlinks. My testing shows public/storage files are now accessible as expected

For me the symlink only works if i add the app_storage as volume to nginx

```
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:81:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - app_storage:/var/www/html/storage:ro
      - image-public:/var/www/html/public:ro
```
![image](https://github.com/user-attachments/assets/5fca41f2-4d20-4211-814a-4447d3e627d5)
