### ISSUE TITLE
APP_CIPHER is set to an invalid default value

### ISSUE THREAD

**Issue by xobs** [invoiceninja/dockerfiles#65]
Similar to others, I've run into a problem where the APP_CIPHER is set to an invalid default value.  The Dockerfile sets it to "rijndael-128", when the only valid options are "AES-128-CBC" and "AES-256-CBC".

While it's true the front page documentation says this value should be overridden, it's better to have it fail gracefully when no value is specified.  The existing value should be removed from the Dockerfile, or a valid cipher should be put in its place, or the build should be made to fail when no cipher is specified.

**Comment by lalop** [comment]
You are wright, I updated the docker-compose exemple but not the Dockerfile.

@hillelcoren if the dockerfile is built for production first, it's better to remove `APP_KEY` and `APP_CIPHER` not ? I'm speaking about the image built https://github.com/invoiceninja/dockerfiles/blob/master/Dockerfile#L61-L73 not from the invoiceninja configuration
Same thing for the database maybe...

**Comment by hillelcoren** [comment]
Yes, I think it would be best to remove them.

**Comment by lalop** [comment]
fixed https://github.com/invoiceninja/dockerfiles/commit/4e5022fcc497510b1c7156ba8ca5d1548815012f
