### ISSUE TITLE
Normal that first user created by docker-compose (super admin) not listed in User Management?

### ISSUE THREAD

**Issue by serfriz** [invoiceninja/dockerfiles#652]
Hello, I am not sure if it is a bug, but is it normal that the first user, the one used to log in for the first time after setting up Invoice Ninja via docker-compose (either the default one admin@example.com or a chosen username via the environment variable IN_USER_EMAIL), doesn't show up in the User Management panel? As a result it also can't be assigned to tasks.

Is this the nominal behavior intended to avoid using the super admin user for accounting tasks?

Thank you!

**Comment by turbo124** [comment]
The first user is the owner user. their account details are in Settings > User Details.
