### ISSUE TITLE
Logo not displayed in admin portal

### ISSUE THREAD

**Issue by brdns** [invoiceninja/dockerfiles#657]
**Setup information**

Unit file is trimmed down for sharing purposes.
```
# invoiceninja.container
[Container]
ContainerName=invoiceninja
Entrypoint=["/bin/sh", "-c", "/usr/local/bin/init.sh"]

# Env
EnvironmentFile=.env

# Image
Image=docker.io/invoiceninja/invoiceninja-debian:latest

# Volumes
Volume=.env:/var/www/html/.env:ro,Z
Volume=config/php/php.ini:/usr/local/etc/php/php.ini:ro,Z
Volume=config/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro,Z
Volume=storage:/var/www/html/storage:z
Volume=cache:/var/www/html/bootstrap/cache:z
Volume=public:/var/www/html/public:ro,z
```
Env file is trimmed down for sharing purposes.
```
APP_ENV=production
APP_DEBUG=true
EXPANDED_LOGGING=true
REQUIRE_HTTPS=false
PHANTOMJS_PDF_GENERATION=false
PDF_GENERATOR=snappdf
TRUSTED_PROXIES='*'

CACHE_DRIVER=redis
QUEUE_CONNECTION=redis
SESSION_DRIVER=redis

FILESYSTEM_DISK=debian_docker

IS_DOCKER=true
SCOUT_DRIVER=null
SNAPPDF_CHROMIUM_PATH=/usr/bin/google-chrome-stable
```

**Describe the bug**

- Logo is not displayed in admin portal and shows 404 error if accessed directly. 
- However logo is correctly used for generating pdf files.
- All files and folder correctly have `www-data:www-data` permissions set within `/var/www/html`
- The only odd think I've found is the `.png` file having `775` permissions inside `storage/app/public` instead of `664` as suggested by the `FILESYSTEM_DISK=debian_docker` setting, but `chmod 664 example.png` does not fix the issue.

**To reproduce**
1. Go to `Settings -> Company details -> Logo`
2. Click on `Upload Your Company Logo`
3. Refresh with `CTRL+SHIFT+R`
4. Logo is not displayed in admin portal

**Expected behavior**
Logo should be seen in admin portal.

**Screenshots/logs**
![Capture d’écran du 2024-11-26 14-31-27](https://github.com/user-attachments/assets/457daacb-1641-4cf4-807c-f43fe8a9de7c)
![Capture d’écran du 2024-11-26 14-31-46](https://github.com/user-attachments/assets/4f87e5c5-d999-4945-afa5-4ee73c38f1e3)

```
cat storage/logs/laravel.log : *empty*
cat storage/logs/invoiceninja.log : *empty*
```

Nginx log if accessed in admin portal :
```
127.0.0.1 - - "GET /storage/example/example.png HTTP/1.1" 200 538 "https://example.com/settings/company_details/logo""
```

Nginx log If accessed directly (outside of admin portal) :
```
127.0.0.1 - - "GET /api/v1/statics HTTP/1.1" 200 315707 "https://example.com/storage/example/example.png""
```

- Output of `podman version`:
```
5.2.2
```

**Additional context**
Nginx default.conf :
```
server {

    error_log  /var/log/nginx/error.log debug;
    access_log /var/log/nginx/access.log;

    listen 80 default_server;
    server_name _;
    
    server_tokens off;
    
    root /var/www/html/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }


    location ~* /storage/.*\.php$ {
        return 503;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass invoiceninja:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
    }
 ```

**Comment by benbrummer** [comment]
I'm pretty sure that https://github.com/invoiceninja/dockerfiles/pull/656/commits/6274c432d9ae03eef920f94a131831f76d4c3e43 will fix this.

**Comment by brdns** [comment]
Yes it does ! Will close this issue as soon as your PR is merged. Thanks 👍
