### ISSUE TITLE
Dockerfile optimization proposal

### ISSUE THREAD

**Issue by benbrummer** [invoiceninja/dockerfiles#660]
docker image seems to be quite big, so I try to identify ways to shrink it

### Ideas
- apt-get --no-install-recommends
- Review apt packages: 
  - snappdf requirements: https://github.com/beganovich/snappdf?tab=readme-ov-file#headless-chrome-doesnt-launch-on-unix
- Review php modules
  - https://invoiceninja.github.io/en/self-host-installation/
- https://docs.docker.com/build/building/multi-stage/
- php 8.3

### apt packages
required:
- curl => google-chrome-stable
- gnupg2 => google-chrome-stable
- gosu => init.sh
- default-mysql-client => initial user creation

obsolete (?):
- git
- unzip
- wget
- zip
- ...

### php modules
```
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gmp
hash
iconv
imagick
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
random
readline
redis
Reflection
saxonc
session
SimpleXML
soap
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib
[Zend Modules]
Zend OPcache
```

### Misc
- https://github.com/invoiceninja/dockerfiles/blob/a6d8f663ae24b4ed982c68e68deb258c55ab6863/debian/Dockerfile#L149 seems to do nothing
- Exact versions for php modlues e.g saxon vs no version for other modules?

**Comment by turbo124** [comment]
@benbrummer we can certainly start with the obsolete ones like zip/unzip

**Comment by turbo124** [comment]
@benbrummer 

related #663 I had to roll back the architecture if/fi blocks as they were preventing required dependencies from installing.

**Comment by turbo124** [comment]
The fonts are definitely needed to provide unicode support for PDF generation is regions like China.

The others, if they are dependencies of chrome won't hurt to have in place I would have thought.

**Comment by benbrummer** [comment]
@turbo124

Are these apt packages needed?
I assume the *-dev can be ommited and xfonts-wgy is propably required for pdf?
```
    libonig-dev \
    libpng-dev \
    libxml2-dev \
    xfonts-wqy \
```

**Comment by turbo124** [comment]
I'm not sure if any of these are subdependencies of anything

**Comment by benbrummer** [comment]
If I compare the php list https://invoiceninja.github.io/en/self-host-installation/#server-requirements with the modules, which are installed in the image, the `intl` module is missing.

Additional modules in the image installed with install-php-extensions
-     exif 
-     opcache => Needed for caching/jit
-     pcntl
-     pdo_mysql
-     redis => Needed for redis
-     saxon-12.5.0

@turbo124 can you tell me what are the required ones. E.g pdo_mysql vs mysqli?

**Comment by turbo124** [comment]
mysqli is fine for use,.
exif would be to extract metadata from certain filetypes,
gd is also for image processing
pcntl I think is required for Laravel
saxon definitely needed for xslt transformations
redis - for cache access

**Comment by benbrummer** [comment]
> mysqli is fine for use,. exif would be to extract metadata from certain filetypes, gd is also for image processing pcntl I think is required for Laravel saxon definitely needed for xslt transformations redis - for cache access

I reduced it for a test to just
```
RUN ( curl -sSLf https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions -o - || echo 'return 1' ) | sh -s \
    bcmath \
    # exif \
    gd \
    # gmp \
    # imagick \
    # intl \
    # mysqli \
    # opcache \
    # pcntl \
    pdo_mysql \
    # redis \
    # saxon-${saxon} \
    # soap \
    zip \
    @composer
```
Everything seems to work.

**Comment by turbo124** [comment]
predis is more than sufficient here, i agree.

**Comment by benbrummer** [comment]
@turbo124 I'm not able to find a usage for these modules. Do you have an example, where these modules are used in invoiceninja. Can I somehow produce an error somewhere?

# Modules, which seem to be unused
exif 
gmp 
imagick
intl
mysqli
pcntl
saxon-12.5.0
soap

```
RUN ( curl -sSLf https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions -o - || echo 'return 1' ) | sh -s \
    bcmath \
    gd \
    opcache \
    pdo_mysql \
    zip \
    @composer
```

**Comment by turbo124** [comment]
Soap needed for vat number verification
Saxon for xslt
Imagick for image compression 
Intl also required the exact reason currently escapes me, but I believe around some mb4 support

Pcntl, I believe is needed by Laravel
GMP or bcmath needed 
Some form of php MySQL extension required.

**Comment by turbo124** [comment]
whilst there may be no composer related dependencies, the app directly engages the ones I have mentioned above.

**Comment by benbrummer** [comment]
> whilst there may be no composer related dependencies, the app directly engages the ones I have mentioned above.

So than they should be listed here? https://github.com/invoiceninja/invoiceninja/blob/7b02668d4bd1de6462717a98a88e6ebea706eaa5/composer.json#L33

**Comment by turbo124** [comment]
Not necessarily. The app can certainly work without some of these. We do not enforce all possible extensions.

 The app is installed on a wide range of services including shared hosting which can present challenges for meeting some dependencies.

In environments where we can control the underlying extensions, then it makes sense to use them.

**Comment by benbrummer** [comment]
Understand :-)

Is there a documentation for all the possible extensions and their purpuose?

https://invoiceninja.github.io/en/self-host-installation/#server-requirements should list `pdo_mysql`, database connection does not work (But it works without mysqli). Maybe a list of mandatory modules (or a link to the require section in composer.json) can be added, and a list of optional modules.

pcntl:
seems to be not required by laravel: https://laravel.com/docs/11.x/deployment#server-requirements

**Comment by turbo124** [comment]
```
"suggest": {
        "ext-pcntl": "Required for process control (CLI only)",
        "ext-gd": "Required for image processing",
        "ext-mbstring": "Required for multibyte string handling"
    }
```

We can certainly add the list of non-required extensions into a suggest block.

In regards to pdo_mysql, I believe this is automatically included (at least when using apt) when running apt-get install php-mysql

pnctl is part of PHP core, not really an extension, my guess here is  upstream they check for this flag and replace with a binary that has pnctl enabled or disabled.

given pnctl's role in process control, and laravel does use SIG* commands for process controls, I would assume this is very much needed.

**Comment by benbrummer** [comment]
@turbo124 I tried to to my best and combined all Information (composer.json, laravel docs, invoiceninja docs, the base dockerimages 8.2-8.4-fpm)

```
"require": {
    // php 8.4 works with some notices like PHP Deprecated:  App\Models\CompanyGateway::driver(): Implicitly marking parameter $client as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/app/Models/CompanyGateway.php on line 206
    "php": ">=8.2",
    // https://github.com/invoiceninja/dockerfiles/issues/660#issuecomment-2511321698
    "ext-gd": "*, insall needed",
    "ext-curl": "*",    
    "ext-zip": "*, install needed", 
    "ext-openssl": "*",
    "ext-mbstring": "*",
    "ext-dom": "*",
    "ext-xml": "*",
    "ext-bcmath": "*, install needed",
    "ext-iconv": "*",
    // Additional mandatory module
    "pdo_mysql": "*, Connection.php... could not find driver..., install needed"
    }
```
```
"suggest": {
    "ext-simplexml": "*, ?, was listed in 'require'",
    // All of these are not preinstalled in php:8.2/8.3-fpm
    "ext-exif": "*, ",
    "ext-gmp": "*, ",
    "ext-imagick": "*, suggest for DomPDF suggested",
    "ext-intl": "*, Was missing in previous invoiceninja-debian images, twig/intl requires symfony/intl, but none of them require/suggest ext_intl",
    "ext-mysqli": "*, ?",
    "ext-opcache": "*, caching",
    "ext-pcntl": "*, Required for process control (CLI only), php needs to be compiled for it. Not listed in requirements for Laravel https://laravel.com/docs/11.x/deployment#server-requirements ",
    "ext-saxonc": ">=12.5.0, xslt processing during",
    "ext-soap": "*, VAT validation"        
    }
```

Additional modules listed in documentation https://invoiceninja.github.io/en/self-host-installation/#server-requirements, which are not already listed above
```
"suggest?": {
    "ctype": "*, ?",
    "tokenizer": "*, ?",
    "gmp": "*, ?, install needed",
}
```
php-common will be installed anyway, wehn any php-* package is installed, and it is no php modul itself, so I think it is not needed to list in the docs.

**Comment by turbo124** [comment]
removed gmp requirement as we enforce bcmath.
removed mysqli ? as mysql, mysqlnd, mysqli are viable options?
removed opcache as it requires additional configuration outside the scope of the application

My Suggestion

```
"suggest": {
    "ext-exif": "*, Advanced image meta data collection",
    "ext-imagick": "*, Provides image compression, if available",
    "ext-intl": "*, Required for full intl support in twig",
    "ext-pcntl": "*, Improves parallel performance and provides signal handling for CLI commands",
    "ext-saxonc": ">=12.5.0, xslt processing and validation of xml documents",
    "ext-soap": "*, VAT validation"        
    }
```

**Comment by benbrummer** [comment]
@turbo124 I integrated yourt suggestion https://github.com/invoiceninja/dockerfiles/pull/664/commits/806a340a009aa102330f8850ab9ce1d728791d79#diff-b98298742c5536fa90710aea60f865cdf0149b61c06288c4a0219ce4796ec807R3

Apart of a multistage implementation everything is implemented from this issue. Multistage can be handled, if needed in a different issue.

**Comment by benbrummer** [comment]
Multistage is currently out of scope for this issue
