### ISSUE TITLE
an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/1/00/0000000001 while reading upstream

### ISSUE THREAD

**Issue by benbrummer** [invoiceninja/dockerfiles#662]
`nginx-1  | 2024/11/28 08:48:31 [warn] 21#21: *1 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/1/00/0000000001 while reading upstream, client: 172.19.0.1, server: _, request: "POST /api/v1/refresh?current_company=true&updated_at=1732781608&first_load=true HTTP/1.0", upstream: "fastcgi://172.19.0.4:9000" ...`

Some buffer configuration seems to be necessary for nginx https://nginx.org/en/docs/http/ngx_http_fastcgi_module.html. But I was not yet able to find the right setting.

**Comment by benbrummer** [comment]
I tested already to increase the values but no success. It is only happening after docker compose up. Afterwards no issue. https://github.com/invoiceninja/dockerfiles/blob/baad65c737b0cb8aa658c848a67297f33035708b/debian/nginx/invoiceninja.conf#L4

One other NOTICE/Warning is there for preload

`app-1    | [28-Nov-2024 19:32:08] NOTICE: PHP message: PHP Warning:  Can't preload unlinked class Symfony\Component\Console\Question\ChoiceQuestion@anonymous: Unknown parent Symfony\Component\Console\Question\ChoiceQuestion in /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Choice.php on line 40`

**Comment by turbo124** [comment]
#663
