### ISSUE TITLE
Login client portal 404-error

### ISSUE THREAD

**Issue by tecnomur** [invoiceninja/dockerfiles#668]
**Broken client login.**

404 — Not Found
Check storage/logs for more details

Docker latest 5.10.59

P.D. client area works if is autemticathed before at browser, maybe cached

https://forum.invoiceninja.com/t/client-portal-404-error/17446

**Comment by turbo124** [comment]
@tecnomur which branch are you using? Master or Debian?

**Comment by tecnomur** [comment]
Master

**Comment by turbo124** [comment]
I've just spun up the latest image and the page does not 404.

**Comment by tecnomur** [comment]
> I've just spun up the latest image and the page does not 404.

https://facturacion.tecnomur.synology.me/client

**Comment by tecnomur** [comment]
@turbo124 new update fix the problem.

thanks again for all.

regards.
