### ISSUE TITLE
Broken Client Portal 5.10.59

### ISSUE THREAD

**Issue by 12nick12** [invoiceninja/dockerfiles#669]
## Setup
- Version: 5.10.59
- Environment: Docker

## Interface
- Flutter: []
- React: []
- Both: []

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?: no
- Have you searched existing issues?: yes
- Have you reported this to Slack/forum before posting?: no
- Have you inspected the logs in storage/logs/laravel.log for any errors?: yes and no errors

## Describe the bug
When I try to go to https://billing.domain.com/client I get a ` 404 — Not Found ` error

### Steps To Reproduce
Go to https://billing.domain.com/client

### Expected Behavior
I expect it to show the client portal

## Additional context
To update to the new version I did the following
1. Updated `image: invoiceninja/invoiceninja:5.10.59` in the docker-compose file
2. did a docker compose down
3. docker compose pull
4. git pull
5. git checkout 5.10.59
6. docker compose up -d
Now the client portal is showing a 404

When that failed I did, and still no luck
1. docker compose exec app composer i -o --no-dev
2. docker compose exec app php artisan migrate
3. docker compose exec app php artisan optimize:clear

### Screenshots
![image](https://github.com/user-attachments/assets/1b0a8a84-a301-48d9-bcf3-17781a858b3c)

### Logs
 tail -f docker/app/storage/logs/laravel.log
"}
[2024-11-30 06:20:00] production.INFO: Performing Autobilling 2024-11-30 06:20:00
[2024-11-30 23:30:01] production.INFO: updating currencies
[2024-12-01 06:20:00] production.INFO: Performing Autobilling 2024-12-01 06:20:00
[2024-12-01 23:30:02] production.INFO: updating currencies
[2024-12-02 06:20:00] production.INFO: Performing Autobilling 2024-12-02 06:20:00
[2024-12-02 23:30:03] production.INFO: updating currencies
[2024-12-03 06:20:02] production.INFO: Performing Autobilling 2024-12-03 06:20:02
[2024-12-03 23:30:01] production.INFO: updating currencies
[2024-12-04 06:20:00] production.INFO: Performing Autobilling 2024-12-04 06:20:00

**Comment by turbo124** [comment]
I think I understand what may be happening here.

In Settings > Client Portal is the client portal URL you are attempting to reach populated?

![image](https://github.com/user-attachments/assets/d70815a8-723d-4538-ba52-9b3c72a86e62)


I've added a fallback to catch when this field is blank. The issue leaving it blank is if you have multiple companies, then the correct one may not be displayed.

**Comment by 12nick12** [comment]
Yes, it's populated, just for the sake of it I changed it to something else, saved, then back to what it was and still no luck.

**Comment by turbo124** [comment]
I'm tagging a new release now with a fallback for this.

**Comment by turbo124** [comment]
should be resolved in .60
