### ISSUE TITLE
intl php extension seems to be unused

### ISSUE THREAD

**Issue by benbrummer** [invoiceninja/dockerfiles#671]
intl seems to be unnecessary

Intl is not listed in composer.json for twig/intl-extra and symfony/intl

- https://github.com/twigphp/intl-extra/blob/4eeab2a3f8d04d1838be7251ab2d183f817aea7b/composer.json#L17
- https://github.com/symfony/symfony/blob/cc1802d9583349cc19f8982a854f4e96d0c9d4de/src/Symfony/Component/Intl/composer.json#L26

So I assume we can remove this from the dockerfile.

**Comment by turbo124** [comment]
I'd prefer to leave this one. I believe that whilst it is not suggested, the base twig/intl package only provide partial support for intl
