### ISSUE TITLE
Issue: HTTPS Not Working Despite Configuration

### ISSUE THREAD

**Issue by AdrianoNicolucci** [invoiceninja/dockerfiles#679]
I have successfully launched my server following the documentation with Docker using version 5.11.7

However, I am encountering issues with enabling HTTPS. I followed the steps in the documentation, and here's what I have configured:

**.env File Configuration**
`APP_URL=https://subdomain.domain.com:8012`
`REQUIRE_HTTPS=true`  

**docker-compose.yml File Configuration**
In addition to the documentation, I also mounted a volume for Let's Encrypt:

`/etc/letsencrypt/archive:/etc/letsencrypt/archive:ro  `
(Note: This volume mount is not mentioned in the documentation.)

**Current Behavior**
When REQUIRE_HTTPS=false in the .env file, I can access my site using HTTP.
However, when REQUIRE_HTTPS=true, I am unable to access the site via HTTPS.

**Domain Setup**
The domain appears to be configured correctly since HTTP works when HTTPS is disabled.
I have also added the A name record in my domain controller which maps my IP address of the server to the subdomain I want to use.

**Comment by turbo124** [comment]
This is not an issue with the app, REQUIRE_HTTPS only forces http:// to https://

This sounds like a configuration issue of HTTPS in your container.

Try setting this up over port 443.

**Comment by AdrianoNicolucci** [comment]
Thanks @turbo124 . Can you elaborate on what "try setting this up over port 443 means? Are there additional updates we need to make to the docker-compose file?  I forgot to mention, in the docker-compose file I added:

ports:
      - "80:80"
      - "443:443"

But it doesn't help.

**Comment by turbo124** [comment]
you only have to define those if they are different... also, the ports would need to be 8012:80  or 8012:443 if you want to expose that port to https

**Comment by AdrianoNicolucci** [comment]
Ok, so I updated the ports in the docker-compose file to be:

ports:
- "8012:443"

but https URL doesn't work. Is there another step I'm missing?

**Comment by AdrianoNicolucci** [comment]
@turbo124,  It seems the issue is that Nginx isn't configured to use the SSL certificates. In the docker-compose file, I've passed the locations of the certificates (e.g., `fullchain.pem` and `privkey.pem`) to the Nginx container, but Invoice Ninja is missing the necessary Nginx instructions to apply these certificates. I think I need to modify the Nginx configuration file (e.g., ./nginx/default.conf) to ensure it listens on port 443, uses the mounted SSL certificates, and redirects HTTP traffic to HTTPS.   It's just unclear how to deploy this into the docker container...any suggestions?


I think the code should look something like this that needs to be deployed:
```
server {
    listen 443 ssl;
    server_name subdomain.domain.com;

    ssl_certificate /etc/nginx/cert/fullchain.pem;
    ssl_certificate_key /etc/nginx/cert/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'HIGH:!aNULL:!MD5';

    location / {
        proxy_pass http://app:8080;  # Assuming the app runs on port 8080 inside Docker
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name subdomain.domain.com;
    return 301 https://$host$request_uri;  # Redirect HTTP to HTTPS
}
```

**Comment by AdrianoNicolucci** [comment]
**Solution**: Enable HTTPS with Let's Encrypt & Docker for InvoiceNinja
I've successfully configured HTTPS for my InvoiceNinja Docker deployment using Let's Encrypt. The key was updating the Nginx configuration to handle SSL and redirect HTTP traffic.

Steps:

Generate SSL Certificates: First, I generated the necessary SSL certificates using Let's Encrypt. Ensure these are accessible to your Nginx container. In my setup, I mapped them to /etc/nginx/cert/.

Update Nginx Configuration: I modified the invoiceninja.conf file (typically found in your debian/nginx folder or the relevant Nginx configuration directory for your Docker setup).

The updated configuration includes two server blocks:

One listens on port 443 for SSL traffic.
The other listens on port 80 and redirects all HTTP traffic to HTTPS.
Make sure to replace [subdomain].[domain] with your actual domain.

Nginx
```
server {
    listen 443 ssl;
    server_name [subdomain].[domain];

    # Ensure these paths correctly point to your Let's Encrypt certificates
    ssl_certificate /etc/nginx/cert/fullchain.pem;
    ssl_certificate_key /etc/nginx/cert/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'HIGH:!aNULL:!MD5';

    client_max_body_size 100M;
    root /var/www/html/public; # Or your specific InvoiceNinja public root

    index index.php; # Added for clarity, often helpful

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # Ensure 'app:9000' matches your PHP-FPM container name and port
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

server {
    listen 80;
    server_name [subdomain].[domain];
    return 301 https://$host$request_uri;  # Permanent redirect HTTP to HTTPS
}
```
Key Changes:

The first server block is configured for SSL on port 443, with ssl_certificate and ssl_certificate_key directives pointing to the Let's Encrypt certificate files.
The second server block listens on port 80 and uses return 301 https://$host$request_uri; to enforce HTTPS by redirecting all HTTP requests.
This setup ensures that all traffic to the site is secure. Remember to adjust paths and container names based on your specific Docker environment.
