### ISSUE TITLE
DB User Access Denied.

### ISSUE THREAD

**Issue by smholsen** [invoiceninja/dockerfiles#68]
Hi,
First off I am sorry if this is the wrong place to post this, but I am having some issues with the DB setup for running the docker image. 
After running the docker image I am trying to test the db connection. 
I have added a user 'ninja' and granted privileges as described in the Setup description.
However, when testing the connection I get the following error: 
    SQLSTATE[HY000] [1045] Access denied for user 'ninja'@'xxxx.xxxx.xxxx.xxxx' (using password: YES)

I have verified that the password is correct, and I am able to connect and use the user on the db directly from the container. 
I can connect to mysql with user and password from terminal like this :
mysql -u ninja -p 
*enter password*

And then I can use the db and I have verified it has all privileges. 

If I try to use the root user instead of the ninja user from the setup page with the root password, it seems to work, but not with the created ninja user. Does this have something to do with me having created the user @'localhost', and when it tries to connect from the application, it has an ip? (the error shows an IP adress, not 'localhost'.

**Comment by smholsen** [comment]
I am not as steady as I might should've been on MySQL and docker, but adding the ninja user with the wildcard @'%' solved the isse. Which I guess makes sense, but is this really required as the application is running on the same server? if so, maybe it should also be part of the setup description?

**Comment by lalop** [comment]
hey @smholsen 
In the docker world containers are linked on an internal network that reflects a normal one, each one has its own ip, they aren't aware of the host.

It seems that your environment's variables aren't set correctly.
Can you share your docker-compose ?

**Comment by lalop** [comment]
I updated the docker-compose exemple to add the DB_DATABASE environment variable.
Can you check that you have this variable correectly setted in your instance ?

**Comment by lalop** [comment]
cool, so I close this issue

**Comment by githubatf2f10** [comment]
Hi lalop,
I tried dockerfiles  with docker-compose and .env. I modified .env as followings,
MYSQL_DATABASE=ninja
MYSQL_ROOT_PASSWORD=Nfjtyueggeg

APP_DEBUG=0
APP_URL=http://192.168.140.248:8000
APP_KEY=RoFb3WJhgqFNfljyfhshkeshrtfg
APP_CIPHER=AES-256-CBC
DB_USERNAME=ninja
DB_PASSWORD=Roafafafdafasf
DB_HOST=mysql
DB_DATABASE=ninja
MAIL_HOST=box.f2f10.com    
MAIL_USERNAME=accounting@f2f10.com
MAIL_PASSWORD=1Sfk7yu2jruyutuwgfg
MAIL_DRIVER=smtp
MAIL_FROM_NAME="F2F10 Inc."
MAIL_FROM_ADDRESS=accounting@f2f10.com

But, I see this error when testing DB connection....

Invoice Ninja Setup
If you need help you can either post to our support forum or email us at contact@invoiceninja.com.

-- Commands to create a MySQL database and user
CREATE SCHEMA `ninja` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'ninja'@'localhost' IDENTIFIED BY 'ninja';
GRANT ALL PRIVILEGES ON `ninja`.* TO 'ninja'@'localhost';
FLUSH PRIVILEGES;

What would be the issue? How do I correct it?

thanks
