### ISSUE TITLE
docker-compose doesn't work for invoiceninja:4.4.0

### ISSUE THREAD

**Issue by sestegra** [invoiceninja/dockerfiles#70]

**Comment by lalop** [comment]
Can You provide some details ?

**Comment by sestegra** [comment]
First, mysql:8 doesn't support user/password by default.
As a result, DB test connection on setup page doesn't work.

Then, data volume for app image needs www-data rights to run:
As a result, impossible to create .env file and then read php files.

**Comment by lalop** [comment]
Can you please try with the last build and mysql 5 ?

**Comment by sestegra** [comment]
FIxed
