### ISSUE TITLE
Some small documentation issues with this repository

### ISSUE THREAD

**Issue by jbzdak** [invoiceninja/dockerfiles#71]
I have recently used **modified** version of docker compose from this script to succesfully deploy invoice ninja for a client.

However, as a person without PHP experience, i have run into some issues: 

1. It appears that ``APP_KEY`` needs to conform to specified format (proper length, etc). It would be usefull to have this information in documentation here; 
2. Somehow storage folders had botched owner (root:root) while (at least partially) they need to be write-able by www-data (e.g. session storage); 

Anyways thanks for this repository it is great :)

**Comment by lalop** [comment]
@jbzdak thank you for this comment.

@hillelcoren I'm right If I add in documentation that we can generate a key via the `key:generate` command ?
The complete command for us will be `docker run -e APP_CIPHER='AES-256-CBC' -it --rm invoiceninja/invoiceninja php artisan key:generate --show`

**Comment by hillelcoren** [comment]
Do users see the /setup screen when they first launch the app?

When the setup form is submitted the app should automatically call key:generate

**Comment by lalop** [comment]
In docker the environment variable is set via docker so the .env file shouldn't be updated by the app.

**Comment by lalop** [comment]
Is that necessary to generate de APP_KEY ?

**Comment by lalop** [comment]
Do you have any complete documentation on this kind of variable to add a link in the Readme ?

**Comment by hillelcoren** [comment]
Sorry, I'm not sure I understand. 

Here's where PHANTOMJS_SECRET is mentioned in the docs: http://docs.invoiceninja.com/en/latest/configure.html#phantomjs

**Comment by jbzdak** [comment]
I have added a PR that shows what updates would be helpful for me when I was deploying invoice ninja.

**Comment by JamesK852** [comment]
This really helped me as I never used the php key:generate function before.

**Comment by grahamPegNetwork** [comment]
This issue is over a year old, from what I can see it is impossible to get the docker file running without these instructions, please update the README with full instructions on how to get them running.
