### ISSUE TITLE
SQL Database Password Error

### ISSUE THREAD

**Issue by JamesK852** [invoiceninja/dockerfiles#74]
Trying to deploy from docker-compose script. Everything goes smoothly until I get to the configuration page and even thought i've set the MYSQL_ROOT_PASSWORD and user password in the .env file I keep getting this error

`  SQLSTATE[HY000] [1045] Access denied for user 'ninja'@'172.26.0.3' (using password: YES)
`
This is the copy of my .env file I'm testing

```

MYSQL_DATABASE=ninja
MYSQL_ROOT_PASSWORD=2RuEFalje34fM

APP_DEBUG=0
APP_URL=http://localhost:8000
APP_KEY=base64:{key}
APP_CIPHER=AES-256-CBC
DB_USERNAME=ninja
DB_PASSWORD=ninja
DB_HOST=mysql
DB_DATABASE=ninja
MAIL_HOST=mail.service.host
MAIL_USERNAME=username
MAIL_PASSWORD=password
MAIL_DRIVER=smtp
MAIL_FROM_NAME="My name"
MAIL_FROM_ADDRESS=user@mail.com
```

Many thanks for the help.

**Comment by hillelcoren** [comment]
Have you tried testing the user/pass directly to make sure it can be used to access the database?

**Comment by JamesK852** [comment]
Hi @hillelcoren,

I attached directly to invoiceninja_db_1 and the username and password variables I set in the .env do not allow me to access mysql database for both root user and ninja user.

**Comment by JamesK852** [comment]
Oops nevermind. My noob mistake, didn't realize the db volume is already being used by another....sorry

**Comment by hillelcoren** [comment]
Maybe the user needs to be setup as 'ninja'@'%' rather than 'ninja'@'172.26.0.3'

**Comment by JamesK852** [comment]
Still no luck. Even the pereodic CRON job throws the same access denied error. Not sure what is causing this.

I noticed these warning through are they normal?
```

db_1    | 2018-06-04T13:17:41.606522Z 0 [Note] Server socket created on IP: '::'.
db_1    | 2018-06-04T13:17:41.623059Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1    | 2018-06-04T13:17:41.625831Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1    | 2018-06-04T13:17:41.625960Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1    | 2018-06-04T13:17:41.625979Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1    | 2018-06-04T13:17:41.626000Z 0 [Warning] 'user' entry 'ninja@localhost' ignored in --skip-name-resolve mode.
db_1    | 2018-06-04T13:17:41.626044Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1    | 2018-06-04T13:17:41.626082Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1    | 2018-06-04T13:17:41.626091Z 0 [Warning] 'db' entry 'ninja ninja@localhost' ignored in --skip-name-resolve mode.
db_1    | 2018-06-04T13:17:41.626117Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1    | 2018-06-04T13:17:41.743834Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1    | 2018-06-04T13:17:41.744246Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1    | 2018-06-04T13:17:41.779032Z 0 [Note] Event Scheduler: Loaded 0 events
db_1    | 2018-06-04T13:17:41.788320Z 0 [Note] mysqld: ready for connections.


```

**Comment by lalop** [comment]
@JamesK852 I don't see MYSQL_USER and MYSQL_PASSWORD in your env, did you create this user manually from the root user ?

**Comment by JamesK852** [comment]
Sorry what is the difference between MYSQL_USER, MYSQL_PASSWORD and DB_USERNAME, DB_PASSWORD?

**Comment by lalop** [comment]
the DB_* ones are for invoiceninja the MYSQL_* are for mysql

**Comment by JamesK852** [comment]
Adding those two to the ENV helped me get passed the setup screen with the user accounts testing successfully however now it just displays 

"Whoops, looks like something went wrong."

Some warnings are displayed by docker too

> app_1   | [28-Jun-2018 04:03:45] WARNING: [pool www] child 10 said into stderr: "[2018-06-28 04:03:45] production.ERROR: ***ErrorException*** [0] : /var/www/app/app/Http/Middleware/StartupCheck.php [Line 71] => fopen(/var/www/app/storage/version.txt): failed to open stream: Permission denied  {"context":"PHP","user_id":0,"account_id":0,"user_name":"","method":"GET","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","locale":"en","ip":"10.0.50.2","count":9,"is_console":"no","is_api":"no","db_server":"mysql","url":"login"} []"

**Comment by JamesK852** [comment]
This fixed it

https://github.com/invoiceninja/invoiceninja/issues/1965

Thanks for the help!!

**Comment by hillelcoren** [comment]
@lalop do you think we should add it to the readme, a number of people have run into the same issue. Or is there a different underlying problem?

**Comment by lalop** [comment]
I think we can fix it in the entrypoint but I can't find any time to look at the origine of the issue

**Comment by hillelcoren** [comment]
Ok, no worries. I think just adding it to the readme for now would be a big help.
