### ISSUE TITLE
How to add custom omnipay drivers to the docker version?

### ISSUE THREAD

**Issue by ovizii** [invoiceninja/dockerfiles#80]
I'd like to use this one: https://github.com/mikoweb/omnipay-paypal-plus 
The docs say: https://invoice-ninja.readthedocs.io/en/latest/configure.html#omnipay 

Unfortunately I don't see how to add this to my docker version without this being lost with newer updates. 
Can this somehow be done?

**Comment by hillelcoren** [comment]
I don't believe it's supported

**Comment by ovizii** [comment]
hm, thanks. Any chance Paypal Plus can be officially added to invoiceninja without requiring code changes, maybe in a future 4.x version? 
here is more information about Paypal Plus: https://www.paypal.com/de/webapps/mpp/paypal-plus

**Comment by hillelcoren** [comment]
You can create an issue to request it.

**Comment by ovizii** [comment]
https://github.com/invoiceninja/invoiceninja/issues/2269
