### ISSUE TITLE
cannot connect to docker; not listening on port tcp/80 (only tcp6/80)

### ISSUE THREAD

**Issue by corbolais** [invoiceninja/dockerfiles#84]
Hi,
Thanks for providing a docker file.

As explained in by programster in issue https://github.com/invoiceninja/invoiceninja/issues/1718 there is no way to connect to the nginx instance running inside docker.

Before the issue got closed the IO was asked (https://github.com/invoiceninja/invoiceninja/issues/1718#issuecomment-338502012) to post in this repo.

So far, this issue is still prevailing.

Any hints?

cheers

**Comment by corbolais** [comment]
I read in https://github.com/invoiceninja/dockerfiles/issues/58#issuecomment-339253567 that the README file would be corrected. It is not.

The docker image listens on port tcp/80, tcp6/80 and it seems port 9000. What is this all about?

Also, it is unclear why the docker instance is listening on all those ports and yet the user is to run a webserver in front of it.

Any clarification very welcome.

Thanks

**Comment by lalop** [comment]
The image is based on php-fpm, port 9000 is the default port of php-fpm, if you want to use this image directly and not the docker-compose version you have to put a web-server in front of it (like we do in the docker-compose file)

**Comment by paoloposo** [comment]
As of early April 2019, the README still doesn't provide a working example to deploy Invoice Ninja.

**Comment by gknoop** [comment]
Yeah, I've been having crazy amounts of trouble setting this up with Docker-compose and Traefik. Been going off of cursory searches for issues and a lone Reddit comment, but I still can't get it working beyond the setup screen.

**Comment by hillelcoren** [comment]
Is this still an issue, @lalop is there anything we can do to fix this?

**Comment by codedge** [comment]
We reworked the documentation and the docker-compose files a lot. Additionally we updated the `alpine` image.

Please give it a try, have a look at the readme and let us know about anything unclear.

Unfortunately we cannot assist every docker setup you might want to run. So for any problems with Traefik or Docker swarm we are not able to help.

Feel free to open new issues, specific to one use-case.
