### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Mzngit** [invoiceninja/dockerfiles#87]
I upgraded to the latest self-hosted release using latest Docker image. There were no issues with the upgraded itself, and the docker container properties revealed that it's indeed the latest version. Unfortunately, when I load up the site, it is showing me the prior version of 4.5.5. Also, the file version.txt is also showing 4.5.5 

Thanks.

**Comment by lalop** [comment]
I can't reproduce it 

```
docker run --rm invoiceninja/invoiceninja more public/version
clone public directory
start
::::::::::::::
public/version
::::::::::::::
4.5.6
```

Maybe you mount the public directory, isn't it ?

**Comment by Mzngit** [comment]
I haven't changed the .yml, .env, or the nginx.conf files from the prior updates. The database files/locations are also unchanged. Nothing different was mounted or unmounted.
