### ISSUE TITLE
Upgrade issues

### ISSUE THREAD

**Issue by Mzngit** [invoiceninja/dockerfiles#89]
When I tried to upgrade to v4.5.8, it still has the 4.5.7 image. The invoiceninja/invoiceninja image that it tries to download is apparently on Docker hub (https://hub.docker.com/r/invoiceninja/invoiceninja/tags).
I know of this request in the past, but is there any brief tutorial that you can post on how to build the docker image ourselves directly from invoiceninja.org?
I know of the v4.5.8 image already posted by anojht/invoiceninja but I don't know if that's the official version or not.
Thanks.

**Comment by lalop** [comment]
hello @Mzngit I updated the repos to the 4.5.8 but I see that this didn't launch a new build on docker hub.
I launch it manually

**Comment by Mzngit** [comment]
Thanks. Works fine now. I'm presuming the brief tutorial is not an option?

**Comment by lalop** [comment]
I'm not sure to understand, you want to know how to build the dockerfile in this repository ?
