### ISSUE TITLE
 Possibility of volume to persist data like uploads and logos

### ISSUE THREAD

**Issue by thiagoalmeidasa** [invoiceninja/dockerfiles#9]
I've made my image from your example in https://github.com/moss-it/docker-invoiceninja , basically  integrating nginx to the image.
Now I'm wondering how I can use docker volumes to persist with logos and others uploads, but I don't know the laravel directory structure. Can you help me or indicate some lecture link?

**Comment by lalop** [comment]
hi @thiagoalmeidasa,
all you need to persist is `public/logo` and `storage`

**Comment by thiagoalmeidasa** [comment]
Thanks. I'll test then.

**Comment by lalop** [comment]
Could you close this issue if it's good for you ?
