### ISSUE TITLE
Push to 4.5.11

### ISSUE THREAD

**Issue by jamieboy05** [invoiceninja/dockerfiles#92]
I keep getting update notifications telling me to update to 4.5.11  The latest version tag for the dockerhub install is 4.5.9.   Are there plans to push an update for 4.5.11 to the dockerfile?

**Comment by lalop** [comment]
the repository is ready for this version but the autobuild is broken https://github.com/invoiceninja/dockerfiles/issues/93
It should be avalaible soon

**Comment by lalop** [comment]
the 2 tags exist now

**Comment by ovizii** [comment]
latest still says: Last update: 2 months ago - any new instructions?

**Comment by lalop** [comment]
I just come to launch a new build https://hub.docker.com/r/invoiceninja/invoiceninja/tags
