### ISSUE TITLE
Auto build for docker hub

### ISSUE THREAD

**Issue by arubacao** [invoiceninja/dockerfiles#93]
I've noticed that docker hub is not in sync and the last version was tagged over 1 month ago.
https://hub.docker.com/r/invoiceninja/invoiceninja/tags

It would be great if docker builds would be automated.
I've never tried it, but it looks like a 1-click configuration.
https://docs.docker.com/docker-hub/builds/

**Comment by lalop** [comment]
hum this was configured but it seems that the link between github and docker hub is broken.
@hillelcoren I tried to renew the token, You should have a mail to validate this access I think.

**Comment by hillelcoren** [comment]
Thanks, I've approved it
