### ISSUE TITLE
Error 404 with traefik

### ISSUE THREAD

**Issue by Soarnoa** [invoiceninja/dockerfiles#95]
Hello,

When I start docker up, everything starts fine, up until I try to access the site, and I start getting errors with the css and .js files. 

![invoiceninja](https://user-images.githubusercontent.com/16331365/54318403-3d83fa00-45b4-11e9-9116-22be587c3be7.PNG)

Here are the related files:
Docker-compose: https://hastebin.com/dulafazonu.http
nginx.conf: https://hastebin.com/ipadevened.nginx
.env: https://hastebin.com/lehipuxure.ini

Any help would be extremely appreciated, Thanks!

**Comment by hillelcoren** [comment]
Maybe this will help?

https://github.com/invoiceninja/dockerfiles/issues/14#issuecomment-241860289

**Comment by Soarnoa** [comment]
Thanks, but I already have fastcgi_param HTTPS 1 in my nginx config, unless there's something else I'm not noticing in there.

**Comment by Soarnoa** [comment]
Fixed it with the following: docker-compose file. https://hastebin.com/ixeviwowit.http
Added an extra volume for /var/www/app/public and linked them to nginx as well. Also redid my .env file just to make sure, but it's all the same info.

**Comment by ellis** [comment]
@Soarnoa Could you please post the docker-compose file here?  The "hastebin" link is empty, and I'd love to see how you got it working!

**Comment by Soarnoa** [comment]
> @Soarnoa Could you please post the docker-compose file here? The "hastebin" link is empty, and I'd love to see how you got it working!

Sorry, here it is.

Docker-compose: https://pastebin.com/yNjyARid
.env: https://pastebin.com/AAQ4PkPF

**Comment by ellis** [comment]
Thanks, @Soarnoa, your files helped me get it running!
