### ISSUE TITLE
recurring invoices not sending

### ISSUE THREAD

**Issue by jacobalberty** [invoiceninja/dockerfiles#96]
I noticed this months invoices didn't send out, popped in container and artisan is not executable.  I modified my docker-compose cron entry to call /usr/local/bin/php ./artisan instead and it seems to be working fine now. but the default configuration as it is doesn't seem to be working any more

You can confirm this with `docker run --rm -it invoiceninja/invoiceninja:latest ./artisan` you'll get permission denied, however if you call `docker run --rm -it invoiceninja/invoiceninja:latest /usr/local/bin/php ./artisan` the artisan binary sucessfully gets called.

**Comment by almereyda** [comment]
It seems the PHP path prefix can be added to

https://github.com/invoiceninja/dockerfiles/blob/e0fcb50ecb0d6b6d920ca1bacdf4c113ba9aad14/docker-compose/docker-compose.yml#L64-L65

and sending of recurring invoices should return to a nominal state?

**Comment by jacobalberty** [comment]
Yes, that does seem to correct it

**Comment by lalop** [comment]
We need to make artisan executable

**Comment by lalop** [comment]
@turbo124 I see you changed the permission on artisan here https://github.com/invoiceninja/invoiceninja/commit/aefe133ba02f28d9fd585ae731765ad5b7cdffe3 from executable to not executable, is there a reason for that ?

**Comment by glassbase** [comment]
Just noticed this too when my customer called and said they aren't receiving my invoices for my monthly services. Now I will have to explain to all my customers that for 2 or 3 months you did not get my monthly services invoices, please pay up

**Comment by glassbase** [comment]
Not to mention, why can't it be smart enough to know it missed sending a previous reoccurring and create multiple reoccurring invoices.

**Comment by turbo124** [comment]
@lalop the directory and file permission were set recursively to best practice which is 755 for directories and 644 for files.

**Comment by turbo124** [comment]
apologies for the oversight, this has been fixed #2827

**Comment by lalop** [comment]
:+1: thank you
